/**
 * One-shot port of the handoff's prototype data modules into ES modules.
 *
 * The handoff ships content as browser globals (`window.PORTFOLIO_PROJECTS = {…}`)
 * followed by an IIFE that merges the modules together at load time. This script
 * strips the IIFEs and rewrites the globals as named exports; the merge is
 * re-implemented explicitly in src/data/index.ts.
 *
 * Run: node scripts/port-data.mjs <handoff-design-dir>
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

const srcDir = process.argv[2]
if (!srcDir) {
  console.error('usage: node scripts/port-data.mjs <handoff-design-dir>')
  process.exit(1)
}

const outDir = 'src/data'
mkdirSync(outDir, { recursive: true })

/** @type {{file: string, out: string, globals: string[]}[]} */
const MODULES = [
  { file: 'portfolio-projects.js', out: 'projects.ts', globals: ['PORTFOLIO_PROJECTS', 'PROJECT_TECH'] },
  { file: 'portfolio-deepdive.js', out: 'deepdive.ts', globals: ['PORTFOLIO_DEEPDIVE'] },
  { file: 'portfolio-pm.js', out: 'pm.ts', globals: ['PORTFOLIO_PM'] },
  { file: 'portfolio-enhancements.js', out: 'enhancements.ts', globals: ['PORTFOLIO_ENHANCEMENTS'] },
  { file: 'agent-studies.js', out: 'agentStudies.ts', globals: ['AGENT_STUDIES', 'AGENT_EXTRAS', 'AGENT_TECH'] },
]

for (const mod of MODULES) {
  let src = readFileSync(join(srcDir, mod.file), 'utf8')

  // Drop the trailing merge IIFE — the merge now lives in src/data/index.ts.
  src = src.replace(/\n\(function \(\) \{[\s\S]*?\}\)\(\);\s*$/, '\n')

  // `window.X = {…}` becomes a named export; `window.X.key = {…}` becomes an
  // assignment onto the already-exported object.
  for (const g of mod.globals) {
    src = src.split(`window.${g} = `).join(`export const ${g}: Record<string, any> = `)
    src = src.split(`window.${g}.`).join(`${g}.`)
  }

  // AGENT_STUDIES is an array, not a keyed record.
  src = src.replace(
    'export const AGENT_STUDIES: Record<string, any> = [',
    'export const AGENT_STUDIES: any[] = [',
  )

  const banner = [
    '// Generated by scripts/port-data.mjs from the design handoff package.',
    `// Source: design_handoff_portfolio_site/design/${mod.file}`,
    '// Content is the source of truth for copy — edit here, not in the handoff.',
    '',
  ].join('\n')

  writeFileSync(join(outDir, mod.out), banner + src)
  console.log(`${mod.file} -> ${outDir}/${mod.out}`)
}
