// Generated by scripts/port-template.mjs from the design handoff package.
// Region: Agent deep-dive modal (prototype lines 2392–2703).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'

import { Fragment } from 'react'
import { css, arr } from '@/lib/style'
import type { ViewModel } from '@/lib/useViewModel'

export function AgentModal({ v }: { v: ViewModel }) {
  return (
    <>
      {v.haSel ? (
        <>
          <div onClick={v.closeHA} style={{ position: "fixed", inset: "0", background: "rgba(0,0,0,0.74)", zIndex: "60", backdropFilter: "blur(12px)", animation: "fadeIn 0.3s ease" }} />
          <div style={{ position: "fixed", inset: "0", zIndex: "61", overflowY: "auto", overscrollBehavior: "contain" }}>
            <div style={{ maxWidth: "1060px", margin: "0 auto", padding: "44px 20px 90px" }}>
              <div style={{ background: "#0a0a12", border: "1px solid rgba(255,255,255,0.08)", borderRadius: "20px", overflow: "hidden", animation: "modalSlide 0.5s cubic-bezier(.2,.7,.2,1)", position: "relative" }}>
                <button type="button" onClick={v.closeHA} style={{ position: "absolute", top: "18px", right: "18px", zIndex: "5", background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: "8px", width: "34px", height: "34px", color: "#c8c8d0", fontSize: "18px", cursor: "pointer", lineHeight: "1" }} className="hv-32">
                  ×
                </button>
                <div style={css(v.haSel.topBarStyle)} />
                <div style={{ padding: "34px 40px 40px" }} className="ha-card">
                  <div style={{ display: "flex", alignItems: "center", gap: "12px", flexWrap: "wrap" }}>
                    <span style={css(v.haSel.labelStyle)}>
                      {v.haSel.industry} · {v.haSel.vertical}
                    </span>
                    <span style={css(v.haSel.statusStyle)}>
                      {v.haSel.status}
                    </span>
                    {v.haSel.hasExample ? (
                      <>
                        <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8.5px", letterSpacing: "0.06em", color: "#8f8f9b", border: "1px solid rgba(255,255,255,0.1)", borderRadius: "4px", padding: "3px 9px" }}>
                          ↳ modeled on {v.haSel.example}
                        </span>
                      </>
                    ) : null}
                  </div>
                  <div style={{ display: "flex", alignItems: "center", gap: "12px", margin: "16px 0 0" }}>
                    <span style={css(v.haSel.dotStyle)} />
                    <h2 style={{ fontSize: "clamp(24px, 3vw, 34px)", fontWeight: "700", letterSpacing: "-0.03em", margin: "0", color: "#f0f0f4" }}>
                      {v.haSel.agent}
                    </h2>
                  </div>
                  <p style={{ fontSize: "15px", lineHeight: "1.5", color: "#b0b0bb", margin: "12px 0 0", maxWidth: "72ch" }}>
                    {v.haSel.tagline}
                  </p>
                  <div style={{ display: "flex", flexWrap: "wrap", gap: "7px", marginTop: "16px" }}>
                    <span style={css(v.haSel.stackTagStyle)}>
                      Stack
                    </span>
                    {arr(v.haSel.stack).map((s: any, sIndex: number) => (
                      <Fragment key={sIndex}>
                        <span style={css(v.haSel.stackChipStyle)}>
                          {s}
                        </span>
                      </Fragment>
                    ))}
                  </div>
                  {v.haSel.hasTech ? (
                    <>
                      <div style={{ display: "flex", gap: "4px", marginTop: "26px", borderBottom: "1px solid rgba(255,255,255,0.08)" }}>
                        {arr(v.haSel.tabs).map((tb: any, tbIndex: number) => (
                          <Fragment key={tbIndex}>
                            <button type="button" onClick={tb.onClick} style={css(tb.style)}>
                              {tb.label}
                            </button>
                          </Fragment>
                        ))}
                      </div>
                    </>
                  ) : null}
                  {v.haSel.showOverview ? (
                    <>
                      <div>
                        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px", marginTop: "30px" }}>
                          <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", padding: "20px" }}>
                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#fb7185", marginBottom: "10px" }}>
                              The problem
                            </div>
                            <p style={{ fontSize: "13px", lineHeight: "1.65", color: "#9a9aa5", margin: "0" }}>
                              {v.haSel.problem}
                            </p>
                          </div>
                          <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", padding: "20px" }}>
                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "10px" }}>
                              What the agent does
                            </div>
                            <p style={{ fontSize: "13px", lineHeight: "1.65", color: "#9a9aa5", margin: "0" }}>
                              {v.haSel.goal}
                            </p>
                          </div>
                        </div>
                        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: "1px", background: "rgba(255,255,255,0.05)", borderRadius: "12px", overflow: "hidden", marginTop: "16px" }}>
                          {arr(v.haSel.metrics).map((mt: any, mtIndex: number) => (
                            <Fragment key={mtIndex}>
                              <div style={{ background: "#0a0a12", padding: "20px 18px" }}>
                                <div style={css(v.haSel.metricValStyle)}>
                                  {mt.v}
                                </div>
                                <div style={{ fontSize: "10.5px", color: "#c8c8d0", marginTop: "9px", lineHeight: "1.3" }}>
                                  {mt.l}
                                </div>
                                <div style={{ fontSize: "9px", color: "#5a5a64", marginTop: "4px", lineHeight: "1.3" }}>
                                  {mt.s}
                                </div>
                              </div>
                            </Fragment>
                          ))}
                        </div>
                        {v.haSel.hasRationale ? (
                          <>
                            <div style={css(v.haSel.rationaleStyle)}>
                              <div style={css(v.haSel.rationaleTagStyle)}>
                                Why this model &amp; framework
                              </div>
                              <p style={{ fontSize: "13px", lineHeight: "1.65", color: "#c8c8d0", margin: "0" }}>
                                {v.haSel.rationale}
                              </p>
                            </div>
                          </>
                        ) : null}
                        <div style={{ marginTop: "38px" }}>
                          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#f0f0f4", marginBottom: "4px" }}>
                            Agent Workflow
                          </div>
                          <p style={{ fontSize: "12.5px", color: "#8a8a95", margin: "0 0 18px" }}>
                            Left to right — how a single request moves between the clinician, the agent, and the systems it plugs into.
                          </p>
                          <div style={{ display: "flex", flexDirection: "column", gap: "8px" }} className="swimlane-wrap">
                            {arr(v.haSel.lanes).map((lane: any, laneIndex: number) => (
                              <Fragment key={laneIndex}>
                                <div style={{ display: "grid", gridTemplateColumns: "148px repeat(5, 1fr)", gap: "8px", alignItems: "stretch" }} className="swimlane-row">
                                  <div style={{ display: "flex", alignItems: "center", gap: "8px", padding: "8px 12px", borderRadius: "8px", background: "rgba(255,255,255,0.025)" }}>
                                    <span style={css(lane.dotStyle)} />
                                    <span style={css(lane.labelStyle)}>
                                      {lane.name}
                                    </span>
                                  </div>
                                  {arr(lane.cells).map((cell: any, cellIndex: number) => (
                                    <Fragment key={cellIndex}>
                                      <div style={{ minHeight: "72px", display: "flex" }}>
                                        {cell.active ? (
                                          <>
                                            <div style={css(cell.cardStyle)}>
                                              <span style={css(cell.numStyle)}>
                                                {cell.num}
                                              </span>
                                              <span style={{ fontSize: "10.5px", lineHeight: "1.42", color: "#d0d0d8" }}>
                                                {cell.label}
                                              </span>
                                            </div>
                                          </>
                                        ) : null}
                                      </div>
                                    </Fragment>
                                  ))}
                                </div>
                              </Fragment>
                            ))}
                          </div>
                        </div>
                        <div style={{ marginTop: "38px" }}>
                          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#f0f0f4", marginBottom: "4px" }}>
                            What It Plugs Into
                          </div>
                          <p style={{ fontSize: "12.5px", color: "#8a8a95", margin: "0 0 18px" }}>
                            The data sources, model, callable tools, and governance the agent needs to run in production.
                          </p>
                          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(232px, 1fr))", gap: "14px" }}>
                            {arr(v.haSel.integrations).map((grp: any, grpIndex: number) => (
                              <Fragment key={grpIndex}>
                                <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", padding: "16px" }}>
                                  <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "13px" }}>
                                    <span style={css(grp.dotStyle)} />
                                    <span style={css(grp.labelStyle)}>
                                      {grp.layer}
                                    </span>
                                  </div>
                                  <div style={{ display: "flex", flexDirection: "column", gap: "9px" }}>
                                    {arr(grp.items).map((it: any, itIndex: number) => (
                                      <Fragment key={itIndex}>
                                        <div style={{ fontSize: "11.5px", lineHeight: "1.45", color: "#9a9aa5", paddingLeft: "13px", position: "relative" }}>
                                          <span style={css(grp.bulletStyle)} />
                                          {it}{' '}
                                        </div>
                                      </Fragment>
                                    ))}
                                  </div>
                                </div>
                              </Fragment>
                            ))}
                          </div>
                        </div>
                        <div style={{ marginTop: "38px" }}>
                          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#f0f0f4", marginBottom: "4px" }}>
                            How It's Evaluated
                          </div>
                          <p style={{ fontSize: "12.5px", color: "#8a8a95", margin: "0 0 18px" }}>
                            Offline gates that must pass before any change ships — and the online signals watched in production.
                          </p>
                          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" }}>
                            <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(var(--aRGB,52,211,153),0.14)", borderRadius: "12px", padding: "18px 20px" }}>
                              <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "6px" }}>
                                Offline · Pre-ship gates
                              </div>
                              {arr(v.haSel.evalsOffline).map((ev: any, evIndex: number) => (
                                <Fragment key={evIndex}>
                                  <div style={{ display: "flex", alignItems: "flex-start", gap: "10px", padding: "12px 0", borderBottom: "1px solid rgba(255,255,255,0.04)" }}>
                                    <span style={{ color: "var(--a,#34d399)", fontSize: "13px", lineHeight: "1.4", flexShrink: "0" }}>
                                      ✓
                                    </span>
                                    <div style={{ flex: "1" }}>
                                      <div style={{ display: "flex", alignItems: "center", gap: "8px", flexWrap: "wrap" }}>
                                        <span style={{ fontSize: "12.5px", color: "#e0e0e6", fontWeight: "600" }}>
                                          {ev.c}
                                        </span>
                                        {ev.hard ? (
                                          <>
                                            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "7.5px", letterSpacing: "0.08em", color: "#fb7185", background: "rgba(251,113,133,0.1)", border: "1px solid rgba(251,113,133,0.3)", borderRadius: "3px", padding: "1px 5px" }}>
                                              HARD GATE
                                            </span>
                                          </>
                                        ) : null}
                                      </div>
                                      <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10.5px", color: "#9a9aa5", marginTop: "4px", lineHeight: "1.4" }}>
                                        {ev.g}
                                      </div>
                                    </div>
                                  </div>
                                </Fragment>
                              ))}
                            </div>
                            <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(34,211,238,0.14)", borderRadius: "12px", padding: "18px 20px" }}>
                              <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#22d3ee", marginBottom: "6px" }}>
                                Online · Production signals
                              </div>
                              {arr(v.haSel.evalsOnline).map((ev: any, evIndex: number) => (
                                <Fragment key={evIndex}>
                                  <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "12px", padding: "12px 0", borderBottom: "1px solid rgba(255,255,255,0.04)" }}>
                                    <span style={{ fontSize: "12.5px", color: "#d0d0d8" }}>
                                      {ev.m}
                                    </span>
                                    <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", color: "#22d3ee", whiteSpace: "nowrap" }}>
                                      {ev.t}
                                    </span>
                                  </div>
                                </Fragment>
                              ))}
                            </div>
                          </div>
                        </div>
                        {v.haSel.hasRollout ? (
                          <>
                            <div style={{ marginTop: "38px" }}>
                              <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#f0f0f4", marginBottom: "4px" }}>
                                Rollout — Earn Autonomy in Phases
                              </div>
                              <p style={{ fontSize: "12.5px", color: "#8a8a95", margin: "0 0 18px" }}>
                                Ship narrow and supervised, then widen only as each phase clears its error budget.
                              </p>
                              <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "14px" }}>
                                {arr(v.haSel.rollout).map((ph: any, phIndex: number) => (
                                  <Fragment key={phIndex}>
                                    <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", padding: "18px" }}>
                                      <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "11px" }}>
                                        <span style={css(ph.numStyle)}>
                                          {ph.num}
                                        </span>
                                        <span style={{ fontSize: "13.5px", fontWeight: "700", color: "#f0f0f4" }}>
                                          {ph.p}
                                        </span>
                                      </div>
                                      <p style={{ fontSize: "12.5px", lineHeight: "1.6", color: "#a8a8b2", margin: "0" }}>
                                        {ph.d}
                                      </p>
                                    </div>
                                  </Fragment>
                                ))}
                              </div>
                            </div>
                          </>
                        ) : null}
                        {v.haSel.hasFailure ? (
                          <>
                            <div style={{ marginTop: "38px" }}>
                              <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#f0f0f4", marginBottom: "4px" }}>
                                Failure Modes &amp; Guardrails
                              </div>
                              <p style={{ fontSize: "12.5px", color: "#8a8a95", margin: "0 0 18px" }}>
                                What can go wrong — and the specific control that catches it before it reaches a person.
                              </p>
                              <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                                {arr(v.haSel.failureModes).map((fm: any, fmIndex: number) => (
                                  <Fragment key={fmIndex}>
                                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "14px", background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", padding: "15px 18px" }}>
                                      <div style={{ display: "flex", alignItems: "flex-start", gap: "9px" }}>
                                        <span style={{ color: "#fb7185", fontSize: "12px", lineHeight: "1.5", flexShrink: "0" }}>
                                          ▸
                                        </span>
                                        <span style={{ fontSize: "12px", lineHeight: "1.5", color: "#e0e0e6" }}>
                                          {fm.r}
                                        </span>
                                      </div>
                                      <div style={{ display: "flex", alignItems: "flex-start", gap: "9px", borderLeft: "1px solid rgba(255,255,255,0.06)", paddingLeft: "14px" }}>
                                        <span style={{ color: "var(--a,#34d399)", fontSize: "12px", lineHeight: "1.5", flexShrink: "0" }}>
                                          ✓
                                        </span>
                                        <span style={{ fontSize: "12px", lineHeight: "1.5", color: "#b0b0bb" }}>
                                          {fm.m}
                                        </span>
                                      </div>
                                    </div>
                                  </Fragment>
                                ))}
                              </div>
                            </div>
                          </>
                        ) : null}
                        <p style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9.5px", letterSpacing: "0.06em", color: "#63636d", margin: "30px 0 0" }}>
                          Values are illustrative of the design — targets and metrics vary by deployment and payer / provider contract.
                        </p>
                      </div>
                    </>
                  ) : null}
                  {v.haSel.showDeep ? (
                    <>
                      <div>
                        <div style={{ marginTop: "30px" }}>
                          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#f0f0f4", marginBottom: "4px" }}>
                            Worked Example — One Request, End to End
                          </div>
                          <p style={{ fontSize: "12.5px", color: "#8a8a95", margin: "0 0 18px" }}>
                            A single request traced through the agent — who acts, what it calls, and exactly where a human steps in.
                          </p>
                          <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                            {arr(v.haSel.techExample).map((ex: any, exIndex: number) => (
                              <Fragment key={exIndex}>
                                <div style={{ display: "flex", alignItems: "flex-start", gap: "12px", background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "10px", padding: "12px 14px" }}>
                                  <span style={css(ex.chipStyle)}>
                                    {ex.who}
                                  </span>
                                  <span style={{ fontSize: "13px", lineHeight: "1.6", color: "#d0d0d8" }}>
                                    {ex.t}
                                  </span>
                                </div>
                              </Fragment>
                            ))}
                          </div>
                        </div>
                        <div style={{ marginTop: "38px" }}>
                          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#f0f0f4", marginBottom: "4px" }}>
                            Architecture — the Agent Loop
                          </div>
                          <p style={{ fontSize: "12.5px", color: "#8a8a95", margin: "0 0 18px" }}>
                            Plan → act → observe → gate: the control loop every run follows.
                          </p>
                          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "14px" }}>
                            {arr(v.haSel.techArch).map((ar: any, arIndex: number) => (
                              <Fragment key={arIndex}>
                                <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", padding: "16px" }}>
                                  <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "10px" }}>
                                    <span style={css(ar.numStyle)}>
                                      {ar.num}
                                    </span>
                                    <span style={{ fontSize: "13px", fontWeight: "700", color: "#f0f0f4" }}>
                                      {ar.s}
                                    </span>
                                  </div>
                                  <p style={{ fontSize: "12.5px", lineHeight: "1.6", color: "#a8a8b2", margin: "0" }}>
                                    {ar.d}
                                  </p>
                                </div>
                              </Fragment>
                            ))}
                          </div>
                        </div>
                        <div style={{ marginTop: "38px" }}>
                          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#f0f0f4", marginBottom: "4px" }}>
                            Tool Contracts — I/O per Callable
                          </div>
                          <p style={{ fontSize: "12.5px", color: "#8a8a95", margin: "0 0 18px" }}>
                            Every action the agent can take: arguments in, structured result out, and whether it only reads or writes / acts.
                          </p>
                          <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                            {arr(v.haSel.techContracts).map((tc: any, tcIndex: number) => (
                              <Fragment key={tcIndex}>
                                <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "10px", padding: "13px 15px" }}>
                                  <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "10px", flexWrap: "wrap" }}>
                                    <span style={css(tc.nStyle)}>
                                      {tc.n}
                                    </span>
                                    <span style={css(tc.effStyle)}>
                                      {tc.e}
                                    </span>
                                  </div>
                                  <div style={{ display: "grid", gridTemplateColumns: "auto 1fr", gap: "5px 12px", marginTop: "10px" }}>
                                    <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8.5px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#5a5a64", paddingTop: "2px" }}>
                                      args
                                    </span>
                                    <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", lineHeight: "1.4", color: "#9a9aa5" }}>
                                      {tc.a}
                                    </span>
                                    <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8.5px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#5a5a64", paddingTop: "2px" }}>
                                      returns
                                    </span>
                                    <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", lineHeight: "1.4", color: "#9a9aa5" }}>
                                      {tc.r}
                                    </span>
                                  </div>
                                </div>
                              </Fragment>
                            ))}
                          </div>
                        </div>
                        <div style={{ marginTop: "38px" }}>
                          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#f0f0f4", marginBottom: "4px" }}>
                            Context &amp; Memory Design
                          </div>
                          <p style={{ fontSize: "12.5px", color: "#8a8a95", margin: "0 0 18px" }}>
                            How the agent is prompted, what it retrieves, and what it remembers between calls.
                          </p>
                          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(232px, 1fr))", gap: "14px" }}>
                            {arr(v.haSel.techContext).map((cx: any, cxIndex: number) => (
                              <Fragment key={cxIndex}>
                                <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", padding: "16px" }}>
                                  <div style={{ fontSize: "12px", fontWeight: "700", color: "#e0e0e6", marginBottom: "8px" }}>
                                    {cx.k}
                                  </div>
                                  <p style={{ fontSize: "12.5px", lineHeight: "1.6", color: "#a8a8b2", margin: "0" }}>
                                    {cx.d}
                                  </p>
                                </div>
                              </Fragment>
                            ))}
                          </div>
                        </div>
                        <div style={{ marginTop: "38px" }}>
                          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#f0f0f4", marginBottom: "4px" }}>
                            Cost · Latency · Scale
                          </div>
                          <p style={{ fontSize: "12.5px", color: "#8a8a95", margin: "0 0 18px" }}>
                            The rough operating envelope per run — illustrative of the design.
                          </p>
                          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: "1px", background: "rgba(255,255,255,0.05)", borderRadius: "12px", overflow: "hidden" }}>
                            {arr(v.haSel.techBudget).map((bd: any, bdIndex: number) => (
                              <Fragment key={bdIndex}>
                                <div style={{ background: "#0a0a12", padding: "18px 16px" }}>
                                  <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#8f8f9b" }}>
                                    {bd.k}
                                  </div>
                                  <div style={{ fontSize: "17px", fontWeight: "700", color: "#f0f0f4", marginTop: "8px", letterSpacing: "-0.01em" }}>
                                    {bd.v}
                                  </div>
                                </div>
                              </Fragment>
                            ))}
                          </div>
                        </div>
                        <div style={{ marginTop: "38px" }}>
                          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#f0f0f4", marginBottom: "4px" }}>
                            Autonomy &amp; Escalation Logic
                          </div>
                          <p style={{ fontSize: "12.5px", color: "#8a8a95", margin: "0 0 18px" }}>
                            The decision thresholds — when the agent acts on its own, asks a human, or hard-stops.
                          </p>
                          <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                            {arr(v.haSel.techAutonomy).map((au: any, auIndex: number) => (
                              <Fragment key={auIndex}>
                                <div style={{ display: "grid", gridTemplateColumns: "auto 1fr auto", gap: "14px", alignItems: "start", background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "10px", padding: "13px 15px" }}>
                                  <span style={css(au.dotStyle)} />
                                  <div>
                                    <div style={{ fontSize: "12px", lineHeight: "1.45", color: "#e0e0e6" }}>
                                      {au.w}
                                    </div>
                                    <div style={{ fontSize: "11.5px", lineHeight: "1.45", color: "#8a8a95", marginTop: "3px" }}>
                                      → {au.a}
                                    </div>
                                  </div>
                                  <span style={css(au.badgeStyle)}>
                                    {au.badge}
                                  </span>
                                </div>
                              </Fragment>
                            ))}
                          </div>
                        </div>
                        <p style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9.5px", letterSpacing: "0.06em", color: "#63636d", margin: "30px 0 0" }}>
                          Deep-dive figures are illustrative of the design — schemas, budgets, and thresholds are tuned per deployment.
                        </p>
                      </div>
                    </>
                  ) : null}
                </div>
              </div>
            </div>
          </div>
        </>
      ) : null}
    </>
  )
}
