// Generated by scripts/port-template.mjs from the design handoff package.
// Region: Assistant chat dock (prototype lines 1802–1852).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'

import { Fragment } from 'react'
import { arr } from '@/lib/style'
import type { ViewModel } from '@/lib/useViewModel'

export function AssistantChat({ v }: { v: ViewModel }) {
  return (
    <>
      <div style={{ position: "fixed", bottom: "24px", right: "24px", zIndex: "45", display: "flex", flexDirection: "column", alignItems: "flex-end", gap: "12px" }}>
        {v.chatOpen ? (
          <>
            <div style={{ width: "340px", maxHeight: "480px", background: "#0c0c14", border: "1px solid rgba(var(--aRGB,52,211,153),0.15)", borderRadius: "16px", overflow: "hidden", animation: "modalSlide 0.3s cubic-bezier(.2,.7,.2,1)", boxShadow: "0 8px 40px rgba(0,0,0,0.5), 0 0 30px rgba(var(--aRGB,52,211,153),0.05)" }}>
              <div style={{ padding: "14px 16px", background: "rgba(var(--aRGB,52,211,153),0.04)", borderBottom: "1px solid rgba(255,255,255,0.04)", display: "flex", alignItems: "center", gap: "10px" }}>
                <div style={{ width: "28px", height: "28px", borderRadius: "8px", background: "rgba(var(--aRGB,52,211,153),0.1)", border: "1px solid rgba(var(--aRGB,52,211,153),0.2)", display: "flex", alignItems: "center", justifyContent: "center" }}>
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--a,#34d399)" strokeWidth="2" strokeLinecap="round">
                    <circle cx="12" cy="12" r="3" />
                    <path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83" />
                  </svg>
                </div>
                <div style={{ flex: "1" }}>
                  <div style={{ fontSize: "13px", fontWeight: "600", color: "#f0f0f4" }}>
                    Muwahib's Assistant
                  </div>
                  <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", color: "var(--a,#34d399)", letterSpacing: "0.08em", display: "flex", alignItems: "center", gap: "4px" }}>
                    <span style={{ width: "4px", height: "4px", borderRadius: "50%", background: "var(--a,#34d399)", animation: "pulseDot 2.4s ease-in-out infinite" }} />
                    ONLINE
                  </div>
                </div>
                <button type="button" onClick={v.toggleChat} aria-label="Open assistant chat" style={{ background: "none", border: "none", cursor: "pointer", color: "#63636d", fontSize: "16px", padding: "4px", transition: "color 0.2s" }} className="hv-1">
                  ✕
                </button>
              </div>
              <div style={{ padding: "16px", maxHeight: "320px", overflowY: "auto", display: "flex", flexDirection: "column", gap: "12px" }}>
                {arr(v.chatMessages).map((msg: any, msgIndex: number) => (
                  <Fragment key={msgIndex}>
                    {msg.isBot ? (
                      <>
                        <div style={{ display: "flex", gap: "8px", alignItems: "flex-start" }}>
                          <div style={{ width: "22px", height: "22px", borderRadius: "6px", background: "rgba(var(--aRGB,52,211,153),0.1)", border: "1px solid rgba(var(--aRGB,52,211,153),0.15)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: "0", marginTop: "2px" }}>
                            <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="var(--a,#34d399)" strokeWidth="2.5">
                              <circle cx="12" cy="12" r="3" />
                            </svg>
                          </div>
                          <div style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "10px 10px 10px 2px", padding: "10px 12px", fontSize: "12.5px", lineHeight: "1.6", color: "#9a9aa5", maxWidth: "260px" }}>
                            {msg.text}
                          </div>
                        </div>
                      </>
                    ) : null}
                    {msg.isUser ? (
                      <>
                        <div style={{ display: "flex", justifyContent: "flex-end" }}>
                          <div style={{ background: "rgba(var(--aRGB,52,211,153),0.1)", border: "1px solid rgba(var(--aRGB,52,211,153),0.15)", borderRadius: "10px 10px 2px 10px", padding: "10px 12px", fontSize: "12.5px", lineHeight: "1.6", color: "var(--a,#34d399)", maxWidth: "260px" }}>
                            {msg.text}
                          </div>
                        </div>
                      </>
                    ) : null}
                  </Fragment>
                ))}
                {v.chatReplies.length ? (
                  <>
                    <div style={{ display: "flex", flexDirection: "column", gap: "6px", marginTop: "4px" }}>
                      {arr(v.chatReplies).map((reply: any, replyIndex: number) => (
                        <Fragment key={replyIndex}>
                          <button type="button" onClick={reply.onClick} style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(var(--aRGB,52,211,153),0.12)", borderRadius: "8px", padding: "9px 12px", cursor: "pointer", fontFamily: "var(--font-space-grotesk), system-ui, sans-serif", fontSize: "12px", color: "#9a9aa5", textAlign: "left", display: "flex", alignItems: "center", gap: "8px", transition: "all 0.2s" }} className="hv-27">
                            <span>
                              {reply.icon}
                            </span>
                            <span>
                              {reply.label}
                            </span>
                          </button>
                        </Fragment>
                      ))}
                    </div>
                  </>
                ) : null}
              </div>
            </div>
          </>
        ) : null}
        <button type="button" onClick={v.toggleChat} aria-label="Open assistant chat" style={{ width: "52px", height: "52px", borderRadius: "14px", background: "var(--a,#34d399)", border: "none", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", boxShadow: "0 4px 20px rgba(var(--aRGB,52,211,153),0.4), 0 0 40px rgba(var(--aRGB,52,211,153),0.15)", transition: "all 0.3s" }} className="hv-28">
          <svg width="26" height="26" viewBox="0 0 32 32" fill="#07070e">
            <path d="M6 4l4 7h12l4-7v11a2 2 0 01-2 2h-1l-1 4a2 2 0 01-2 1.5h-8A2 2 0 0111 21l-1-4H8a2 2 0 01-2-2V4z" />
            <circle cx="11.5" cy="11" r="1.8" fill="var(--a,#34d399)" />
            <circle cx="20.5" cy="11" r="1.8" fill="var(--a,#34d399)" />
            <ellipse cx="16" cy="14.5" rx="1.5" ry="1" fill="var(--a,#34d399)" />
            <path d="M13.5 16.5q2.5 2 5 0" stroke="var(--a,#34d399)" strokeWidth="0.8" fill="none" strokeLinecap="round" />
            <line x1="7" y1="12" x2="3" y2="11" stroke="#07070e" strokeWidth="0.7" />
            <line x1="7" y1="13.5" x2="3" y2="14" stroke="#07070e" strokeWidth="0.7" />
            <line x1="25" y1="12" x2="29" y2="11" stroke="#07070e" strokeWidth="0.7" />
            <line x1="25" y1="13.5" x2="29" y2="14" stroke="#07070e" strokeWidth="0.7" />
          </svg>
        </button>
      </div>
    </>
  )
}
