// Generated by scripts/port-template.mjs from the design handoff package.
// Region: Fixed background layers (prototype lines 86–88).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'



export function BackgroundLayers() {
  return (
    <>
      <canvas data-neural-bg="1" style={{ position: "fixed", inset: "0", width: "100%", height: "100%", pointerEvents: "none", zIndex: "0", opacity: "0.5" }} />
      <div data-progress="1" style={{ position: "fixed", top: "0", left: "0", height: "2px", width: "0", background: "linear-gradient(90deg, var(--a,#34d399), #6ee7b7)", zIndex: "100", boxShadow: "0 0 14px rgba(var(--aRGB,52,211,153),0.7)" }} />
      <div data-glow="1" style={{ position: "fixed", left: "-1000px", top: "-1000px", width: "500px", height: "500px", borderRadius: "50%", background: "radial-gradient(circle, rgba(var(--aRGB,52,211,153),0.07), transparent 60%)", mixBlendMode: "screen", pointerEvents: "none", zIndex: "5", transform: "translate(-50%, -50%)" }} />
    </>
  )
}
