// Generated by scripts/port-template.mjs from the design handoff package.
// Region: Full filterable catalog (prototype lines 1652–1707).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'

import { Fragment } from 'react'
import { css, arr } from '@/lib/style'
import { ImageSlot } from '@/components/ImageSlot'
import type { ViewModel } from '@/lib/useViewModel'

export function CatalogView({ v }: { v: ViewModel }) {
  return (
    <>
      <main data-screen-label="Project Catalog" style={{ maxWidth: "1200px", margin: "0 auto", padding: "70px 48px 120px", position: "relative" }}>
        <button type="button" onClick={v.goHome} style={{ background: "none", border: "none", padding: "0", cursor: "pointer", fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "12px", color: "#63636d", transition: "color 0.2s", marginBottom: "36px" }} className="hv-25">
          ← Back home
        </button>
        <h2 data-glitch="1" style={{ fontSize: "clamp(30px, 3.6vw, 42px)", fontWeight: "700", letterSpacing: "-0.03em", margin: "0", color: "#f0f0f4" }}>
          Project Catalog
        </h2>
        <p style={{ fontSize: "15px", lineHeight: "1.65", color: "#9a9aa5", maxWidth: "54ch", margin: "16px 0 0" }}>
          AI deployments, strategy executions, and agentic workflows.
        </p>
        <div style={{ display: "flex", alignItems: "center", gap: "14px", flexWrap: "wrap", marginTop: "36px" }}>
          <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#63636d" }}>
            Filter:
          </span>
          <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
            {arr(v.filters).map((f: any, fIndex: number) => (
              <Fragment key={fIndex}>
                <button type="button" onClick={f.onClick} style={css(f.style)}>
                  {f.label}
                </button>
              </Fragment>
            ))}
          </div>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: "14px", flexWrap: "wrap", marginTop: "12px" }}>
          <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#63636d" }}>
            Industry:
          </span>
          <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
            {arr(v.industryFilters).map((f: any, fIndex: number) => (
              <Fragment key={fIndex}>
                <button type="button" onClick={f.onClick} style={css(f.style)}>
                  {f.label}
                </button>
              </Fragment>
            ))}
          </div>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "18px", marginTop: "44px" }}>
          {arr(v.catalogCards).map((p: any, pIndex: number) => (
            <Fragment key={pIndex}>
              <article data-reveal="1" data-delay={pIndex} onClick={p.onClick} style={{ cursor: "pointer", position: "relative", background: "#0c0c14", border: "1px solid rgba(var(--aRGB,52,211,153),0.1)", borderRadius: "14px", overflow: "hidden", display: "flex", flexDirection: "column", transition: "border-color 0.3s, box-shadow 0.3s" }} className="hv-26">
                <div style={{ display: "flex", flexDirection: "column", flex: "1" }}>
                  <div style={{ position: "relative", height: "170px", background: "#08080f" }}>
                    {p.thumbSrc ? (
                      <>
                        <div style={css(`width: 100%; height: 100%; background-image: url(${p.thumbSrc}); background-size: cover; background-position: top center;`)} />
                      </>
                    ) : null}
                    {p.noThumb ? (
                      <>
                        <ImageSlot label={p.imgHint} />
                      </>
                    ) : null}
                    <span style={{ position: "absolute", top: "10px", left: "10px", fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.08em", color: "var(--a,#34d399)", background: "rgba(var(--aRGB,52,211,153),0.08)", border: "1px solid rgba(var(--aRGB,52,211,153),0.2)", borderRadius: "4px", padding: "4px 10px" }}>
                      {p.badge}
                    </span>
                    {p.studyFlag ? (
                      <>
                        <span style={css(`position: absolute; top: 10px; right: 10px; font-family: var(--font-ibm-plex-mono), monospace; font-size: 8.5px; letter-spacing: 0.1em; font-weight: 600; border-radius: 4px; padding: 4px 9px; ${p.studyFlagStyle}`)}>
                          {p.studyFlag}
                        </span>
                      </>
                    ) : null}
                  </div>
                  <div style={{ padding: "20px 20px 22px", display: "flex", flexDirection: "column", flex: "1" }}>
                    <h3 style={{ fontSize: "17px", fontWeight: "600", letterSpacing: "-0.01em", margin: "0", color: "#f0f0f4" }}>
                      {p.name}
                    </h3>
                    <p style={{ fontSize: "13px", lineHeight: "1.6", color: "#9a9aa5", margin: "8px 0 0" }}>
                      {p.desc}
                    </p>
                    <div style={{ display: "flex", gap: "6px", flexWrap: "wrap", marginTop: "auto", paddingTop: "16px" }}>
                      {arr(p.tags).map((t: any, tIndex: number) => (
                        <Fragment key={tIndex}>
                          <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.06em", color: "#8f8f9b", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 8px" }}>
                            {t}
                          </span>
                        </Fragment>
                      ))}
                    </div>
                  </div>
                </div>
              </article>
            </Fragment>
          ))}
          {v.catalogEmpty ? (
            <>
              <div style={{ gridColumn: "1 / -1", textAlign: "center", padding: "90px 20px", border: "1px dashed rgba(255,255,255,0.08)", borderRadius: "14px" }}>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#63636d" }}>
                  No matches
                </div>
                <p style={{ fontSize: "14px", color: "#9a9aa5", margin: "12px 0 0" }}>
                  No projects match this filter combination — try clearing one of the filters.
                </p>
              </div>
            </>
          ) : null}
        </div>
      </main>
    </>
  )
}
