// Generated by scripts/port-template.mjs from the design handoff package.
// Region: First-visit ⌘K hint (prototype lines 2720–2734).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'

import type { ViewModel } from '@/lib/useViewModel'

export function CommandHint({ v }: { v: ViewModel }) {
  return (
    <>
      {v.kHint ? (
        <>
          <div style={{ position: "fixed", bottom: "22px", right: "22px", zIndex: "90", maxWidth: "300px", background: "rgba(10,10,18,0.96)", border: "1px solid rgba(var(--aRGB,52,211,153),0.28)", borderRadius: "12px", padding: "14px 16px", boxShadow: "0 18px 50px rgba(0,0,0,0.5)", backdropFilter: "blur(16px)", animation: "fadeIn 0.3s ease" }} data-khint="1">
            <div style={{ display: "flex", alignItems: "flex-start", gap: "10px" }}>
              <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", fontWeight: "700", color: "#07070e", background: "var(--a,#34d399)", borderRadius: "5px", padding: "3px 7px", flexShrink: "0" }}>
                ⌘K
              </span>
              <div>
                <div style={{ fontSize: "12.5px", fontWeight: "600", color: "#f0f0f4", lineHeight: "1.4" }}>
                  Tip: press ⌘K for quick navigation
                </div>
                <div style={{ fontSize: "11px", color: "#9a9aa5", lineHeight: "1.5", marginTop: "3px" }}>
                  Jump to any section or case study. Optional — everything on the page is clickable too.
                </div>
                <div style={{ display: "flex", gap: "8px", marginTop: "10px" }}>
                  <button type="button" onClick={v.openTermFromHint} style={{ background: "var(--a,#34d399)", color: "#07070e", border: "none", borderRadius: "6px", padding: "6px 12px", cursor: "pointer", fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", fontWeight: "600", letterSpacing: "0.06em", textTransform: "uppercase" }}>
                    Try it
                  </button>
                  <button type="button" onClick={v.dismissKHint} style={{ background: "none", border: "none", color: "#8f8f9b", cursor: "pointer", fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.06em", textTransform: "uppercase" }}>
                    Dismiss
                  </button>
                </div>
              </div>
            </div>
          </div>
        </>
      ) : null}
    </>
  )
}
