// Generated by scripts/port-template.mjs from the design handoff package.
// Region: Achievement marquee (prototype lines 242–275).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'



export function HomeMarquee() {
  return (
    <>
      <div style={{ position: "relative", overflow: "hidden", padding: "18px 0", borderBottom: "1px solid rgba(255,255,255,0.04)", background: "rgba(var(--aRGB,52,211,153),0.015)" }}>
        <div style={{ position: "absolute", left: "0", top: "0", bottom: "0", width: "80px", background: "linear-gradient(90deg, #07070e, transparent)", zIndex: "2", pointerEvents: "none" }} />
        <div style={{ position: "absolute", right: "0", top: "0", bottom: "0", width: "80px", background: "linear-gradient(-90deg, #07070e, transparent)", zIndex: "2", pointerEvents: "none" }} />
        <div style={{ display: "flex", animation: "marqueeScroll 45s linear infinite", width: "max-content" }}>
          <div style={{ display: "flex", gap: "48px", padding: "0 24px", alignItems: "center", flexShrink: "0" }}>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--a,#34d399)", whiteSpace: "nowrap", display: "flex", alignItems: "center", gap: "8px" }}>
              <span style={{ width: "4px", height: "4px", borderRadius: "50%", background: "var(--a,#34d399)", boxShadow: "0 0 6px var(--a,#34d399)" }} />
              Amazon · Rivigo · Gulf Cryo
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#63636d", whiteSpace: "nowrap" }}>
              28 Products Shipped
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#63636d", whiteSpace: "nowrap" }}>
              +35% Delivery Efficiency
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#22d3ee", whiteSpace: "nowrap" }}>
              50K+ Monthly Deliveries
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#63636d", whiteSpace: "nowrap" }}>
              4 AI Agents in Production
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#63636d", whiteSpace: "nowrap" }}>
              800+ Tickets/mo Auto-Resolved
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#a78bfa", whiteSpace: "nowrap" }}>
              92% Forecast Accuracy
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#63636d", whiteSpace: "nowrap" }}>
              10 Countries · 27 Plants
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#63636d", whiteSpace: "nowrap" }}>
              12 Healthcare Case Studies
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#f472b6", whiteSpace: "nowrap" }}>
              CSPO · Azure AI Engineer
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#63636d", whiteSpace: "nowrap" }}>
              3h/Day Saved per User
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#22d3ee", whiteSpace: "nowrap" }}>
              5 Enterprise Systems Unified
            </span>
          </div>
          <div style={{ display: "flex", gap: "48px", padding: "0 24px", alignItems: "center", flexShrink: "0" }}>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--a,#34d399)", whiteSpace: "nowrap", display: "flex", alignItems: "center", gap: "8px" }}>
              <span style={{ width: "4px", height: "4px", borderRadius: "50%", background: "var(--a,#34d399)", boxShadow: "0 0 6px var(--a,#34d399)" }} />
              Amazon · Rivigo · Gulf Cryo
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#63636d", whiteSpace: "nowrap" }}>
              28 Products Shipped
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#63636d", whiteSpace: "nowrap" }}>
              +35% Delivery Efficiency
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#22d3ee", whiteSpace: "nowrap" }}>
              50K+ Monthly Deliveries
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#63636d", whiteSpace: "nowrap" }}>
              4 AI Agents in Production
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#63636d", whiteSpace: "nowrap" }}>
              800+ Tickets/mo Auto-Resolved
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#a78bfa", whiteSpace: "nowrap" }}>
              92% Forecast Accuracy
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#63636d", whiteSpace: "nowrap" }}>
              10 Countries · 27 Plants
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#63636d", whiteSpace: "nowrap" }}>
              12 Healthcare Case Studies
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#f472b6", whiteSpace: "nowrap" }}>
              CSPO · Azure AI Engineer
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#63636d", whiteSpace: "nowrap" }}>
              3h/Day Saved per User
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", color: "#22d3ee", whiteSpace: "nowrap" }}>
              5 Enterprise Systems Unified
            </span>
          </div>
        </div>
      </div>
    </>
  )
}
