// Generated by scripts/port-template.mjs from the design handoff package.
// Region: Delivery roadmap (prototype lines 1373–1545).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'



export function HomeRoadmap() {
  return (
    <>
      <section id="roadmap" data-ps="1" style={{ position: "relative", maxWidth: "1200px", margin: "0 auto", padding: "100px 48px 0" }}>
        <div data-reveal="1">
          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "14px" }}>
            {"// Delivery Roadmap"}
          </div>
          <div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: "24px", flexWrap: "wrap", marginBottom: "12px" }}>
            <h2 data-glitch="1" style={{ fontSize: "clamp(28px, 3.2vw, 42px)", fontWeight: "700", letterSpacing: "-0.03em", margin: "0", color: "#f0f0f4" }}>
              What I'm Building Now
            </h2>
            <div style={{ display: "flex", gap: "24px" }}>
              <div style={{ textAlign: "center" }}>
                <div style={{ fontSize: "28px", fontWeight: "700", color: "#f0f0f4", lineHeight: "1" }}>
                  11
                </div>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#63636d", marginTop: "4px" }}>
                  Active
                </div>
              </div>
              <div style={{ textAlign: "center" }}>
                <div style={{ fontSize: "28px", fontWeight: "700", color: "var(--a,#34d399)", lineHeight: "1" }}>
                  18
                </div>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#63636d", marginTop: "4px" }}>
                  Pipeline
                </div>
              </div>
              <div style={{ textAlign: "center" }}>
                <div style={{ fontSize: "28px", fontWeight: "700", color: "#8f8f9b", lineHeight: "1" }}>
                  20+
                </div>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#63636d", marginTop: "4px" }}>
                  Shipped
                </div>
              </div>
            </div>
          </div>
          <p style={{ fontSize: "15px", color: "#8f8f9b", margin: "0" }}>
            A single view of what's live and what's next.
          </p>
        </div>
        <div data-reveal="1" style={{ border: "1px solid rgba(var(--aRGB,52,211,153),0.2)", borderRadius: "16px", background: "linear-gradient(135deg, rgba(var(--aRGB,52,211,153),0.04), rgba(12,12,20,0.8))", padding: "28px 32px", marginBottom: "32px", position: "relative", overflow: "hidden" }}>
          <div style={{ position: "absolute", top: "0", left: "0", width: "25%", height: "2px", background: "linear-gradient(90deg, transparent, rgba(var(--aRGB,52,211,153),0.5), transparent)", animation: "scanH 5s linear infinite" }} />
          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "12px", display: "flex", alignItems: "center", gap: "6px" }}>
            <span style={{ width: "6px", height: "6px", borderRadius: "50%", background: "var(--a,#34d399)", animation: "pulseDot 2.4s ease-in-out infinite" }} />
            Big Impact Project 
          </div>
          <div style={{ display: "flex", alignItems: "baseline", gap: "12px", flexWrap: "wrap", marginBottom: "14px" }}>
            <h3 style={{ fontSize: "24px", fontWeight: "700", letterSpacing: "-0.02em", margin: "0", color: "#f0f0f4" }}>
              Asset Tracking Revamp
            </h3>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", color: "var(--a,#34d399)", background: "rgba(var(--aRGB,52,211,153),0.1)", border: "1px solid rgba(var(--aRGB,52,211,153),0.2)", borderRadius: "4px", padding: "3px 8px" }}>
              OX
            </span>
          </div>
          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.08em", color: "#8f8f9b", marginBottom: "12px" }}>
            SCOPE · 6 WORKSTREAMS
          </div>
          <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
            <span style={{ fontSize: "12px", color: "#9a9aa5", background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: "6px", padding: "6px 12px" }}>
              Revamped Production Process
            </span>
            <span style={{ fontSize: "12px", color: "#9a9aa5", background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: "6px", padding: "6px 12px" }}>
              Gate Security
            </span>
            <span style={{ fontSize: "12px", color: "#9a9aa5", background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: "6px", padding: "6px 12px" }}>
              Enhanced Delivery System
            </span>
            <span style={{ fontSize: "12px", color: "#9a9aa5", background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: "6px", padding: "6px 12px" }}>
              Inter &amp; Intra-Org Deliveries
            </span>
            <span style={{ fontSize: "12px", color: "#9a9aa5", background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: "6px", padding: "6px 12px" }}>
              Automated Rentals &amp; Asset Tracking
            </span>
            <span style={{ fontSize: "12px", color: "#9a9aa5", background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: "6px", padding: "6px 12px" }}>
              App-Side Enhancement
            </span>
          </div>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1.4fr", gap: "18px", alignItems: "start" }}>
          <div data-reveal="1" style={{ background: "rgba(12,12,20,0.6)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "14px", padding: "24px" }}>
            <div style={{ display: "flex", alignItems: "baseline", gap: "8px", marginBottom: "18px" }}>
              <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "18px", fontWeight: "700", color: "var(--a,#34d399)", opacity: "0.5" }}>
                01
              </span>
              <span style={{ fontSize: "14px", fontWeight: "600", color: "#f0f0f4" }}>
                Active Major Projects
              </span>
              <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", color: "#63636d", marginLeft: "auto" }}>
                11
              </span>
            </div>
            <div style={{ display: "grid", gap: "4px" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "9px 12px", borderRadius: "8px", background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.04)" }}>
                <span style={{ width: "5px", height: "5px", borderRadius: "50%", background: "var(--a,#34d399)", flexShrink: "0" }} />
                <span style={{ fontSize: "12.5px", color: "#e0e0e6", flex: "1" }}>
                  AI Based Route Planning
                </span>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "9px 12px", borderRadius: "8px", background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.04)" }}>
                <span style={{ width: "5px", height: "5px", borderRadius: "50%", background: "var(--a,#34d399)", flexShrink: "0" }} />
                <span style={{ fontSize: "12.5px", color: "#e0e0e6", flex: "1" }}>
                  E-DN &amp; Paperless Deliveries
                </span>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "9px 12px", borderRadius: "8px", background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.04)" }}>
                <span style={{ width: "5px", height: "5px", borderRadius: "50%", background: "#60a5fa", flexShrink: "0" }} />
                <span style={{ fontSize: "12.5px", color: "#e0e0e6", flex: "1" }}>
                  PowerBI Dashboard for Safety
                </span>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "9px 12px", borderRadius: "8px", background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.04)" }}>
                <span style={{ width: "5px", height: "5px", borderRadius: "50%", background: "#60a5fa", flexShrink: "0" }} />
                <span style={{ fontSize: "12.5px", color: "#e0e0e6", flex: "1" }}>
                  PowerBI Dashboard for Distribution &amp; Operations
                </span>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "9px 12px", borderRadius: "8px", background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.04)" }}>
                <span style={{ width: "5px", height: "5px", borderRadius: "50%", background: "#60a5fa", flexShrink: "0" }} />
                <span style={{ fontSize: "12.5px", color: "#e0e0e6", flex: "1" }}>
                  Synapse — Data Model
                </span>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "9px 12px", borderRadius: "8px", background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.04)" }}>
                <span style={{ width: "5px", height: "5px", borderRadius: "50%", background: "var(--a,#34d399)", flexShrink: "0" }} />
                <span style={{ fontSize: "12.5px", color: "#e0e0e6", flex: "1" }}>
                  Item Code Creation Process
                </span>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "9px 12px", borderRadius: "8px", background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.04)" }}>
                <span style={{ width: "5px", height: "5px", borderRadius: "50%", background: "var(--a,#34d399)", flexShrink: "0" }} />
                <span style={{ fontSize: "12.5px", color: "#e0e0e6", flex: "1" }}>
                  User Access Management
                </span>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "9px 12px", borderRadius: "8px", background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.04)" }}>
                <span style={{ width: "5px", height: "5px", borderRadius: "50%", background: "var(--a,#34d399)", flexShrink: "0" }} />
                <span style={{ fontSize: "12.5px", color: "#e0e0e6", flex: "1" }}>
                  Driver Working-Hours Changes
                </span>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "9px 12px", borderRadius: "8px", background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.04)" }}>
                <span style={{ width: "5px", height: "5px", borderRadius: "50%", background: "#c084fc", flexShrink: "0" }} />
                <span style={{ fontSize: "12.5px", color: "#e0e0e6", flex: "1" }}>
                  SafeCount App
                </span>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "9px 12px", borderRadius: "8px", background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.04)" }}>
                <span style={{ width: "5px", height: "5px", borderRadius: "50%", background: "#c084fc", flexShrink: "0" }} />
                <span style={{ fontSize: "12.5px", color: "#e0e0e6", flex: "1" }}>
                  LetterHead Management App
                </span>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "9px 12px", borderRadius: "8px", background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.04)" }}>
                <span style={{ width: "5px", height: "5px", borderRadius: "50%", background: "var(--a,#34d399)", flexShrink: "0" }} />
                <span style={{ fontSize: "12.5px", color: "#e0e0e6", flex: "1" }}>
                  Customer Notification Module
                </span>
              </div>
            </div>
          </div>
          <div data-reveal="1" data-delay="1" style={{ background: "rgba(12,12,20,0.6)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "14px", padding: "24px" }}>
            <div style={{ display: "flex", alignItems: "baseline", gap: "8px", marginBottom: "18px" }}>
              <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "18px", fontWeight: "700", color: "var(--a,#34d399)", opacity: "0.5" }}>
                02
              </span>
              <span style={{ fontSize: "14px", fontWeight: "600", color: "#f0f0f4" }}>
                Pipeline Projects
              </span>
              <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", color: "#63636d", marginLeft: "auto" }}>
                18
              </span>
            </div>
            <div style={{ marginBottom: "16px" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "6px", marginBottom: "10px", paddingBottom: "6px", borderBottom: "1px solid rgba(var(--aRGB,52,211,153),0.08)" }}>
                <span style={{ width: "5px", height: "5px", borderRadius: "50%", background: "var(--a,#34d399)" }} />
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.1em", color: "var(--a,#34d399)" }}>
                  OX
                </span>
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", color: "#63636d" }}>
                  Operational Excellence
                </span>
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", color: "#63636d", marginLeft: "auto" }}>
                  10
                </span>
              </div>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "4px" }}>
                <div style={{ fontSize: "12px", color: "#9a9aa5", padding: "4px 8px", background: "rgba(255,255,255,0.01)", borderRadius: "6px" }}>
                  WeighScale Integration
                </div>
                <div style={{ fontSize: "12px", color: "#9a9aa5", padding: "4px 8px", background: "rgba(255,255,255,0.01)", borderRadius: "6px" }}>
                  ZFScalar — Sensor Data
                </div>
                <div style={{ fontSize: "12px", color: "#9a9aa5", padding: "4px 8px", background: "rgba(255,255,255,0.01)", borderRadius: "6px" }}>
                  Trip Scheduling Enhancement
                </div>
                <div style={{ fontSize: "12px", color: "#9a9aa5", padding: "4px 8px", background: "rgba(255,255,255,0.01)", borderRadius: "6px" }}>
                  E-DN / Paperless Deliveries
                </div>
                <div style={{ fontSize: "12px", color: "#9a9aa5", padding: "4px 8px", background: "rgba(255,255,255,0.01)", borderRadius: "6px" }}>
                  Customer Notification Rollout
                </div>
                <div style={{ fontSize: "12px", color: "#9a9aa5", padding: "4px 8px", background: "rgba(255,255,255,0.01)", borderRadius: "6px" }}>
                  Centralized Control Tower
                </div>
                <div style={{ fontSize: "12px", color: "#9a9aa5", padding: "4px 8px", background: "rgba(255,255,255,0.01)", borderRadius: "6px" }}>
                  DOA On-Site / Cancellation
                </div>
                <div style={{ fontSize: "12px", color: "#9a9aa5", padding: "4px 8px", background: "rgba(255,255,255,0.01)", borderRadius: "6px" }}>
                  Customer Specific Delivery Process
                </div>
              </div>
            </div>
            <div style={{ marginBottom: "16px" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "6px", marginBottom: "10px", paddingBottom: "6px", borderBottom: "1px solid rgba(96,165,250,0.08)" }}>
                <span style={{ width: "5px", height: "5px", borderRadius: "50%", background: "#60a5fa" }} />
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.1em", color: "#60a5fa" }}>
                  DATA ANALYTICS
                </span>
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", color: "#63636d" }}>
                  Data &amp; BI
                </span>
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", color: "#63636d", marginLeft: "auto" }}>
                  2
                </span>
              </div>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "4px" }}>
                <div style={{ fontSize: "12px", color: "#9a9aa5", padding: "4px 8px", background: "rgba(255,255,255,0.01)", borderRadius: "6px" }}>
                  PowerBI Reports for Operations, Last Mile &amp; QHSE
                </div>
                <div style={{ fontSize: "12px", color: "#9a9aa5", padding: "4px 8px", background: "rgba(255,255,255,0.01)", borderRadius: "6px" }}>
                  MS Fabric &amp; Ontology
                </div>
              </div>
            </div>
            <div style={{ marginBottom: "16px" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "6px", marginBottom: "10px", paddingBottom: "6px", borderBottom: "1px solid rgba(192,132,252,0.08)" }}>
                <span style={{ width: "5px", height: "5px", borderRadius: "50%", background: "#c084fc" }} />
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.1em", color: "#c084fc" }}>
                  AI
                </span>
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", color: "#63636d" }}>
                  AI / Applications
                </span>
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", color: "#63636d", marginLeft: "auto" }}>
                  5
                </span>
              </div>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "4px" }}>
                <div style={{ fontSize: "12px", color: "#9a9aa5", padding: "4px 8px", background: "rgba(255,255,255,0.01)", borderRadius: "6px" }}>
                  GPT For ERP
                </div>
                <div style={{ fontSize: "12px", color: "#9a9aa5", padding: "4px 8px", background: "rgba(255,255,255,0.01)", borderRadius: "6px" }}>
                  Foundry — Agent Builder
                </div>
                <div style={{ fontSize: "12px", color: "#9a9aa5", padding: "4px 8px", background: "rgba(255,255,255,0.01)", borderRadius: "6px" }}>
                  Talent Acquisition System
                </div>
                <div style={{ fontSize: "12px", color: "#9a9aa5", padding: "4px 8px", background: "rgba(255,255,255,0.01)", borderRadius: "6px" }}>
                  Training &amp; Development
                </div>
                <div style={{ fontSize: "12px", color: "#9a9aa5", padding: "4px 8px", background: "rgba(255,255,255,0.01)", borderRadius: "6px" }}>
                  Consequence Management
                </div>
              </div>
            </div>
            <div style={{ marginBottom: "16px" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "6px", marginBottom: "10px", paddingBottom: "6px", borderBottom: "1px solid rgba(251,146,60,0.08)" }}>
                <span style={{ width: "5px", height: "5px", borderRadius: "50%", background: "#fb923c" }} />
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.1em", color: "#fb923c" }}>
                  EX
                </span>
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", color: "#63636d" }}>
                  Employee Experience
                </span>
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", color: "#63636d", marginLeft: "auto" }}>
                  1
                </span>
              </div>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "4px" }}>
                <div style={{ fontSize: "12px", color: "#9a9aa5", padding: "4px 8px", background: "rgba(255,255,255,0.01)", borderRadius: "6px" }}>
                  Driver Bonus Module
                </div>
              </div>
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", padding: "14px 16px", background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "10px" }}>
              <span style={{ fontSize: "20px", fontWeight: "700", color: "var(--a,#34d399)" }}>
                +15
              </span>
              <div>
                <div style={{ fontSize: "12px", fontWeight: "500", color: "#e0e0e6" }}>
                  Small-scale enhancements
                </div>
                <div style={{ fontSize: "10px", color: "#63636d", marginTop: "2px" }}>
                  Minor quick-win improvements bundled across streams.
                </div>
              </div>
            </div>
          </div>
        </div>
        <div data-reveal="1" style={{ marginTop: "32px", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "14px", background: "rgba(12,12,20,0.6)", padding: "24px" }}>
          <div style={{ display: "flex", alignItems: "baseline", gap: "8px", marginBottom: "16px" }}>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "18px", fontWeight: "700", color: "var(--a,#34d399)", opacity: "0.5" }}>
              03
            </span>
            <span style={{ fontSize: "14px", fontWeight: "600", color: "#f0f0f4" }}>
              Recently Shipped
            </span>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", color: "#63636d", marginLeft: "auto" }}>
              20+
            </span>
          </div>
          <div style={{ display: "flex", gap: "6px", flexWrap: "wrap" }}>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(var(--aRGB,52,211,153),0.04)", border: "1px solid rgba(var(--aRGB,52,211,153),0.08)", borderRadius: "4px", padding: "5px 10px" }}>
              AI Based Route Planning
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              ML Model 2.0 + Trip Scheduling
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              Control Tower (Track &amp; Trace)
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              Vue 3 — New UI
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              Azure Synapse Data Model
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              E-Delivery Note Notifications
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              QHSE KPI Report
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              ECR — Empty Collection Receipt
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              User Access Management Revamp
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              Driver Working Hours — Off-Site
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              Driver Hours — SMS Alert
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              DOA for On-Site Order
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              Multiple Order Cancellation
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              Assets / Drivers Notification Report
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              Unassigned / Open Orders Report
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              Delivery Receipt Config
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              Repair &amp; Maintenance Planning
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              Rescheduled Date Reason Codes
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              Delivery Enhancement — Specific Customers
            </span>
            <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)", borderRadius: "4px", padding: "5px 10px" }}>
              Driver Hours in Trip Plan
            </span>
          </div>
        </div>
      </section>
    </>
  )
}
