// Generated by scripts/port-template.mjs from the design handoff package.
// Region: AI agent case studies (prototype lines 710–769).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'

import { Fragment } from 'react'
import { css, arr } from '@/lib/style'
import type { ViewModel } from '@/lib/useViewModel'

export function HomeAgents({ v }: { v: ViewModel }) {
  return (
    <>
      <section id="healthagents" data-ps="1" style={{ position: "relative", maxWidth: "1200px", margin: "0 auto", padding: "100px 48px 0" }}>
        <div data-reveal="1" style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: "20px", flexWrap: "wrap" }}>
          <div>
            <div style={{ display: "inline-flex", alignItems: "center", gap: "8px", border: "1px solid rgba(167,139,250,0.35)", background: "rgba(167,139,250,0.08)", borderRadius: "999px", padding: "5px 12px", marginBottom: "14px" }}>
              <span style={{ width: "6px", height: "6px", borderRadius: "50%", background: "#a78bfa", boxShadow: "0 0 8px #a78bfa" }} />
              <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9.5px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#a78bfa" }}>
                Signature Work · AI Agents across industries
              </span>
            </div>
            <h2 data-glitch="1" style={{ fontSize: "clamp(30px, 3.6vw, 46px)", fontWeight: "700", letterSpacing: "-0.03em", margin: "0", color: "#f0f0f4" }}>
              Agent Case Studies, by Industry
            </h2>
            <p style={{ fontSize: "15px", color: "#8f8f9b", margin: "10px 0 0", maxWidth: "74ch" }}>
              Each card is one agent — the workflow it runs, the systems it plugs into, the evaluation gates it must clear, and the numbers it moves. Healthcare studies reflect shipped and piloted work. The others are framework samples: what the same playbook — best-in-class models, plugins, and orchestration — would build for that industry.
            </p>
          </div>
          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#63636d", whiteSpace: "nowrap" }}>
            Workflow · Integrations · Testing · Impact
          </div>
        </div>
        <div data-reveal="1" style={{ display: "flex", flexWrap: "wrap", gap: "8px", marginTop: "26px" }}>
          {arr(v.haIndustries).map((ind: any, indIndex: number) => (
            <Fragment key={indIndex}>
              <button type="button" onClick={ind.onClick} style={css(ind.style)}>
                {ind.label}
              </button>
            </Fragment>
          ))}
        </div>
        <div data-reveal="1" style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))", gap: "16px", marginTop: "40px" }}>
          {arr(v.haCards).map((c: any, cIndex: number) => (
            <Fragment key={cIndex}>
              <div onClick={c.onClick} style={{ cursor: "pointer", background: "#0c0c14", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "14px", overflow: "hidden", display: "flex", flexDirection: "column", transition: "transform 0.25s cubic-bezier(.2,.7,.2,1), border-color 0.25s" }} className="hv-15">
                <div style={css(c.barStyle)} />
                <div style={{ padding: "20px 20px 18px", display: "flex", flexDirection: "column", gap: "13px", flex: "1" }}>
                  <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "8px" }}>
                    <span style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                      <span style={{ display: "flex", gap: "4px" }}>
                        <span style={{ width: "7px", height: "7px", borderRadius: "50%", background: "#ff5f56" }} />
                        <span style={{ width: "7px", height: "7px", borderRadius: "50%", background: "#ffbd2e" }} />
                        <span style={{ width: "7px", height: "7px", borderRadius: "50%", background: "#27c93f" }} />
                      </span>
                      <span style={css(c.labelStyle)}>
                        {c.vertical}
                      </span>
                    </span>
                    <span style={css(c.statusStyle)}>
                      {c.status}
                    </span>
                  </div>
                  <div>
                    <div style={{ display: "flex", alignItems: "center", gap: "9px" }}>
                      <span style={css(c.dotStyle)} />
                      <h3 style={{ fontSize: "17px", fontWeight: "700", margin: "0", color: "#f0f0f4", letterSpacing: "-0.01em" }}>
                        {c.agent}
                      </h3>
                    </div>
                    <p style={{ fontSize: "12.5px", lineHeight: "1.5", color: "#8a8a95", margin: "9px 0 0" }}>
                      {c.tagline}
                    </p>
                    {c.hasExample ? (
                      <>
                        <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8.5px", letterSpacing: "0.04em", color: "#5a5a64", margin: "8px 0 0" }}>
                          ↳ modeled on {c.example}
                        </div>
                      </>
                    ) : null}
                  </div>
                  <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px" }}>
                    <div style={{ background: "rgba(255,255,255,0.02)", borderRadius: "8px", padding: "11px 12px" }}>
                      <div style={{ fontSize: "20px", fontWeight: "700", color: "#f0f0f4", letterSpacing: "-0.02em" }}>
                        {c.m0v}
                      </div>
                      <div style={{ fontSize: "9.5px", lineHeight: "1.35", color: "#8f8f9b", marginTop: "4px" }}>
                        {c.m0l}
                      </div>
                    </div>
                    <div style={{ background: "rgba(255,255,255,0.02)", borderRadius: "8px", padding: "11px 12px" }}>
                      <div style={{ fontSize: "20px", fontWeight: "700", color: "#f0f0f4", letterSpacing: "-0.02em" }}>
                        {c.m1v}
                      </div>
                      <div style={{ fontSize: "9.5px", lineHeight: "1.35", color: "#8f8f9b", marginTop: "4px" }}>
                        {c.m1l}
                      </div>
                    </div>
                  </div>
                  <div style={{ display: "flex", flexWrap: "wrap", gap: "5px" }}>
                    {arr(c.stackChips).map((s: any, sIndex: number) => (
                      <Fragment key={sIndex}>
                        <span style={css(c.stackChipStyle)}>
                          {s}
                        </span>
                      </Fragment>
                    ))}
                  </div>
                  <div style={{ marginTop: "auto", paddingTop: "13px", display: "flex", alignItems: "center", justifyContent: "space-between", gap: "8px", borderTop: "1px solid rgba(255,255,255,0.05)" }}>
                    <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8.5px", letterSpacing: "0.06em", textTransform: "uppercase", color: "#63636d" }}>
                      {c.toolCount} tools · {c.intCount} integrations
                    </span>
                    <span style={css(c.arrowStyle)}>
                      View case study →
                    </span>
                  </div>
                </div>
              </div>
            </Fragment>
          ))}
        </div>
      </section>
    </>
  )
}
