// Generated by scripts/port-template.mjs from the design handoff package.
// Region: Who I am & what I do (prototype lines 1587–1603).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'



export function HomeAbout() {
  return (
    <>
      <section id="about" data-ps="1" style={{ position: "relative", maxWidth: "1200px", margin: "0 auto", padding: "100px 48px 0" }}>
        <div data-reveal="1">
          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "14px" }}>
            {"// Who I Am &amp; What I Do"}
          </div>
          <h2 style={{ fontSize: "clamp(24px, 3vw, 36px)", fontWeight: "700", letterSpacing: "-0.02em", lineHeight: "1.2", margin: "0 0 20px", color: "#f0f0f4", maxWidth: "900px" }}>
            I&rsquo;m a product manager who builds the tools real businesses run on &mdash; and gives them an AI edge.
          </h2>
          <p style={{ fontSize: "16px", lineHeight: "1.8", color: "#9a9aa5", margin: "0 0 40px", maxWidth: "820px" }}>
            For six years I&rsquo;ve worked across Amazon, Rivigo, and Gulf Cryo &mdash; in logistics, supply chain, and enterprise AI. At Gulf Cryo I lead the AI and logistics products, including Last Mile Platform, a delivery platform now running in 10 countries. My approach is simple: find where people waste time, build software that fixes it, and prove it worked with real numbers. Recently I&rsquo;ve applied the same approach to healthcare &mdash; twelve product studies across the UAE&rsquo;s health systems.
          </p>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: "14px" }}>
            <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", padding: "24px" }}>
              <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "12px" }}>
                I build, not just plan
              </div>
              <p style={{ fontSize: "14px", lineHeight: "1.65", color: "#9a9aa5", margin: "0" }}>
                I set the vision and the roadmap, but I also get hands-on with the technical work &mdash; so ideas actually ship instead of sitting in a slide deck.
              </p>
            </div>
            <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", padding: "24px" }}>
              <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#22d3ee", marginBottom: "12px" }}>
                I make data useful
              </div>
              <p style={{ fontSize: "14px", lineHeight: "1.65", color: "#9a9aa5", margin: "0" }}>
                I turn scattered company data into clear answers people can trust and act on &mdash; with the safeguards that make AI safe to use in serious settings like healthcare.
              </p>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
