// Generated by scripts/port-template.mjs from the design handoff package.
// Region: GCC product teardowns (prototype lines 774–806).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'

import { Fragment } from 'react'
import { css, arr } from '@/lib/style'
import type { ViewModel } from '@/lib/useViewModel'

export function HomeTeardowns({ v }: { v: ViewModel }) {
  return (
    <>
      <section id="gccteardowns" data-ps="1" style={{ position: "relative", maxWidth: "1200px", margin: "0 auto", padding: "60px 48px 0" }}>
        <div data-reveal="1" style={{ background: "#0c0c14", border: "1px solid rgba(129,140,248,0.14)", borderRadius: "14px", overflow: "hidden" }}>
          <div style={{ padding: "14px 18px 12px", borderBottom: "1px solid rgba(255,255,255,0.04)", display: "flex", alignItems: "center", gap: "8px", flexWrap: "wrap" }}>
            <span style={{ width: "6px", height: "6px", borderRadius: "50%", background: "#818cf8" }} />
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#818cf8" }}>
              GCC Product Teardowns
            </span>
            <a href="Product%20Studies%20Cheat%20Sheet.dc.html" style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#818cf8", marginLeft: "auto", textDecoration: "none", border: "1px solid rgba(129,140,248,0.25)", borderRadius: "5px", padding: "4px 10px", transition: "all 0.2s" }} className="hv-16">
              Teardown Playbook &#8599;
            </a>
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#63636d" }}>
              What they built &amp; what I&rsquo;d improve
            </span>
          </div>
          <div style={{ padding: "14px 18px" }}>
            <button type="button" onClick={v.toggleGcc} style={{ width: "100%", background: "rgba(129,140,248,0.06)", border: "1px solid rgba(129,140,248,0.22)", borderRadius: "9px", padding: "12px 16px", cursor: "pointer", fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.08em", textTransform: "uppercase", color: "#a5b4fc", display: "flex", alignItems: "center", justifyContent: "center", gap: "8px", transition: "all 0.2s" }} className="hv-17">
              {v.gccToggleLabel}
            </button>
          </div>
          {v.gccOpen ? (
            <>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)" }}>
                {arr(v.gccGroups).map((g: any, gIndex: number) => (
                  <Fragment key={gIndex}>
                    <div style={{ borderRight: "1px solid rgba(255,255,255,0.04)" }}>
                      <div style={{ padding: "14px 16px 8px", display: "flex", alignItems: "center", gap: "8px" }}>
                        <span style={css(g.dotStyle)} />
                        <span style={css(g.labelStyle)}>
                          {g.label}
                        </span>
                      </div>
                      <div style={{ padding: "2px 8px 12px" }}>
                        {arr(g.items).map((s: any, sIndex: number) => (
                          <Fragment key={sIndex}>
                            <div onClick={s.onClick} data-proj={s.key} onMouseEnter={v.hoverIn} onMouseLeave={v.hoverOut} style={{ cursor: "pointer", padding: "10px 9px", borderRadius: "7px", transition: "background 0.2s" }} className="hv-18">
                              <div style={{ fontSize: "12.5px", fontWeight: "600", color: "#d6d8dd", letterSpacing: "-0.01em" }}>
                                {s.name}
                              </div>
                              <div style={{ fontSize: "10.5px", lineHeight: "1.5", color: "#9a9aa5", marginTop: "4px" }}>
                                {s.desc}
                              </div>
                            </div>
                          </Fragment>
                        ))}
                      </div>
                    </div>
                  </Fragment>
                ))}
              </div>
            </>
          ) : null}
        </div>
      </section>
    </>
  )
}
