// Generated by scripts/port-template.mjs from the design handoff package.
// Region: Method (prototype lines 1548–1575).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'



export function HomeMethod() {
  return (
    <>
      <section id="method" data-ps="1" style={{ position: "relative", maxWidth: "1200px", margin: "0 auto", padding: "100px 48px 0" }}>
        <div data-reveal="1">
          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "14px" }}>
            {"// Method"}
          </div>
          <h2 data-glitch="1" style={{ fontSize: "clamp(28px, 3.2vw, 42px)", fontWeight: "700", letterSpacing: "-0.03em", margin: "0 0 44px", color: "#f0f0f4" }}>
            How I Do It
          </h2>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "1px", background: "rgba(255,255,255,0.04)", borderRadius: "16px", overflow: "hidden" }}>
          <div data-reveal="1" style={{ background: "rgba(7,7,14,0.95)", padding: "36px 28px", transition: "background 0.2s" }} className="hv-21">
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "28px", fontWeight: "700", color: "var(--a,#34d399)", opacity: "0.5" }}>
              01
            </span>
            <h3 style={{ fontSize: "16px", fontWeight: "600", margin: "16px 0 0", color: "#f0f0f4" }}>
              Find the friction
            </h3>
            <p style={{ fontSize: "13.5px", lineHeight: "1.65", color: "#8f8f9b", margin: "10px 0 0" }}>
              Shadow the people doing the work — drivers, planners, finance. The product starts where the hours leak.
            </p>
          </div>
          <div data-reveal="1" data-delay="1" style={{ background: "rgba(7,7,14,0.95)", padding: "36px 28px", transition: "background 0.2s" }} className="hv-21">
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "28px", fontWeight: "700", color: "var(--a,#34d399)", opacity: "0.5" }}>
              02
            </span>
            <h3 style={{ fontSize: "16px", fontWeight: "600", margin: "16px 0 0", color: "#f0f0f4" }}>
              Prototype in days
            </h3>
            <p style={{ fontSize: "13.5px", lineHeight: "1.65", color: "#8f8f9b", margin: "10px 0 0" }}>
              Claude and the Power Platform get a working slice in front of real users within a week.
            </p>
          </div>
          <div data-reveal="1" data-delay="2" style={{ background: "rgba(7,7,14,0.95)", padding: "36px 28px", transition: "background 0.2s" }} className="hv-21">
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "28px", fontWeight: "700", color: "var(--a,#34d399)", opacity: "0.5" }}>
              03
            </span>
            <h3 style={{ fontSize: "16px", fontWeight: "600", margin: "16px 0 0", color: "#f0f0f4" }}>
              Ship enterprise-grade
            </h3>
            <p style={{ fontSize: "13.5px", lineHeight: "1.65", color: "#8f8f9b", margin: "10px 0 0" }}>
              Harden on Azure and AWS — REST integrations into Dynamics 365, security review, rollout country by country.
            </p>
          </div>
          <div data-reveal="1" data-delay="3" style={{ background: "rgba(7,7,14,0.95)", padding: "36px 28px", transition: "background 0.2s" }} className="hv-21">
            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "28px", fontWeight: "700", color: "var(--a,#34d399)", opacity: "0.5" }}>
              04
            </span>
            <h3 style={{ fontSize: "16px", fontWeight: "600", margin: "16px 0 0", color: "#f0f0f4" }}>
              Measure, then scale
            </h3>
            <p style={{ fontSize: "13.5px", lineHeight: "1.65", color: "#8f8f9b", margin: "10px 0 0" }}>
              Every launch carries a number. What moves the metric scales to all 10 countries.
            </p>
          </div>
        </div>
      </section>
    </>
  )
}
