// Generated by scripts/port-template.mjs from the design handoff package.
// Region: Career arc (prototype lines 955–1368).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'

import { Fragment } from 'react'
import { css, arr } from '@/lib/style'
import type { ViewModel } from '@/lib/useViewModel'

export function HomeCareer({ v }: { v: ViewModel }) {
  return (
    <>
      <section id="career" data-ps="1" style={{ position: "relative", maxWidth: "1200px", margin: "0 auto", padding: "100px 48px 0" }}>
        <div data-reveal="1" style={{ marginBottom: "48px" }}>
          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "14px" }}>
            {"// Deployment Log"}
          </div>
          <h2 data-glitch="1" style={{ fontSize: "clamp(28px, 3.2vw, 42px)", fontWeight: "700", letterSpacing: "-0.03em", margin: "0", color: "#f0f0f4" }}>
            Career Trajectory
          </h2>
          <p style={{ fontSize: "15px", color: "#8f8f9b", margin: "8px 0 0" }}>
            Six years across Amazon, Rivigo, and Gulf Cryo — each role scaling complexity and impact.
          </p>
        </div>
        <div data-reveal="1" style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(184px, 1fr))", gap: "1px", background: "rgba(255,255,255,0.04)", borderRadius: "16px", overflow: "hidden", marginBottom: "48px" }}>
          <div style={{ background: "rgba(7,7,14,0.95)", padding: "34px 26px" }}>
            <div style={{ fontSize: "44px", fontWeight: "700", letterSpacing: "-0.03em", color: "#f0f0f4", lineHeight: "1" }}>
              10
            </div>
            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--a,#34d399)", margin: "12px 0 8px" }}>
              Countries live
            </div>
            <p style={{ fontSize: "12.5px", lineHeight: "1.6", color: "#8f8f9b", margin: "0" }}>
              AI + CRM products rolled out country by country across the Gulf Cryo footprint.
            </p>
          </div>
          <div style={{ background: "rgba(7,7,14,0.95)", padding: "34px 26px" }}>
            <div style={{ fontSize: "44px", fontWeight: "700", letterSpacing: "-0.03em", color: "#f0f0f4", lineHeight: "1" }}>
              28
            </div>
            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--a,#34d399)", margin: "12px 0 8px" }}>
              Products shipped
            </div>
            <p style={{ fontSize: "12.5px", lineHeight: "1.6", color: "#8f8f9b", margin: "0" }}>
              Enterprise platforms, AI applications, and autonomous agents across three companies.
            </p>
          </div>
          <div style={{ background: "rgba(7,7,14,0.95)", padding: "34px 26px" }}>
            <div style={{ fontSize: "44px", fontWeight: "700", letterSpacing: "-0.03em", color: "#f0f0f4", lineHeight: "1" }}>
              300
              <span style={{ fontSize: "24px" }}>
                + hrs
              </span>
            </div>
            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--a,#34d399)", margin: "12px 0 8px" }}>
              Manual hours removed
            </div>
            <p style={{ fontSize: "12.5px", lineHeight: "1.6", color: "#8f8f9b", margin: "0" }}>
              Average planning and back-office effort cut by agents that draft, route, and reconcile.
            </p>
          </div>
          <div style={{ background: "rgba(7,7,14,0.95)", padding: "34px 26px" }}>
            <div style={{ fontSize: "44px", fontWeight: "700", letterSpacing: "-0.03em", color: "#f0f0f4", lineHeight: "1" }}>
              &lt;1
              <span style={{ fontSize: "24px" }}>
                 wk
              </span>
            </div>
            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--a,#34d399)", margin: "12px 0 8px" }}>
              Problem to prototype
            </div>
            <p style={{ fontSize: "12.5px", lineHeight: "1.6", color: "#8f8f9b", margin: "0" }}>
              A working slice in front of real users within days, on Claude and the Power Platform.
            </p>
          </div>
          <div style={{ background: "rgba(7,7,14,0.95)", padding: "34px 26px" }}>
            <div style={{ fontSize: "44px", fontWeight: "700", letterSpacing: "-0.03em", color: "#f0f0f4", lineHeight: "1" }}>
              6
              <span style={{ fontSize: "24px" }}>
                 yrs
              </span>
            </div>
            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--a,#34d399)", margin: "12px 0 8px" }}>
              Shipping products
            </div>
            <p style={{ fontSize: "12.5px", lineHeight: "1.6", color: "#8f8f9b", margin: "0" }}>
              Amazon &rarr; Rivigo &rarr; Gulf Cryo — each role scaling complexity and impact.
            </p>
          </div>
        </div>
        <div style={{ display: "grid", gap: "20px" }}>
          <div data-reveal="1" style={{ background: "#0c0c14", border: "1px solid rgba(var(--aRGB,52,211,153),0.15)", borderRadius: "16px", overflow: "hidden", position: "relative" }}>
            <div style={{ position: "absolute", top: "0", left: "0", width: "25%", height: "2px", background: "linear-gradient(90deg, transparent, rgba(var(--aRGB,52,211,153),0.5), transparent)", animation: "scanH 5s linear infinite" }} />
            <div style={{ padding: "32px 32px 0" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "6px" }}>
                <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--a,#34d399)", animation: "pulseDot 2.4s ease-in-out infinite" }} />
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--a,#34d399)" }}>
                  Active Deployment
                </span>
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", color: "#63636d", marginLeft: "auto" }}>
                  Nov 2022 – Present
                </span>
              </div>
              <h3 style={{ fontSize: "22px", fontWeight: "700", letterSpacing: "-0.02em", margin: "8px 0 0", color: "#f0f0f4" }}>
                Product Lead
              </h3>
              <div style={{ fontSize: "14px", color: "var(--a,#34d399)", marginTop: "4px" }}>
                Gulf Cryo · Dubai · 10 countries across MENA
              </div>
              <p style={{ fontSize: "14px", lineHeight: "1.7", color: "#9a9aa5", margin: "16px 0 0", maxWidth: "72ch" }}>
                Led 'Last Mile Platform', an AI-powered last-mile logistics platform across 10 countries. Built Auto-Plan (AI scheduling), SafeCount (inventory reconciliation), and a centralized data warehouse. Drove AI adoption across 200+ operations staff with Claude and Copilot.
              </p>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: "1px", background: "rgba(255,255,255,0.03)", marginTop: "24px" }}>
              <div style={{ background: "rgba(7,7,14,0.95)", padding: "18px 20px", textAlign: "center", cursor: "help" }} title="Delivery efficiency = DIFOT (delivered in-full, on-time) × fulfillment rate — measured on platform data, post-Last Mile Platform vs the pre-platform baseline across 10 markets.">
                <div style={{ fontSize: "24px", fontWeight: "700", color: "var(--a,#34d399)", letterSpacing: "-0.03em" }}>
                  +35%
                </div>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.1em", color: "#63636d", marginTop: "4px", textTransform: "uppercase" }}>
                  Delivery Efficiency
                </div>
                <div style={{ fontSize: "9px", lineHeight: "1.35", color: "#8f8f9b", marginTop: "6px", letterSpacing: "0" }}>
                  DIFOT + fulfillment %, before vs after
                </div>
              </div>
              <div style={{ background: "rgba(7,7,14,0.95)", padding: "18px 20px", textAlign: "center", cursor: "help" }} title="Open orders = orders still unassigned vs assigned for delivery, measured before vs after Last Mile Platform on the same order definition.">
                <div style={{ fontSize: "24px", fontWeight: "700", color: "#f0f0f4", letterSpacing: "-0.03em" }}>
                  −27%
                </div>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.1em", color: "#63636d", marginTop: "4px", textTransform: "uppercase" }}>
                  Open Orders
                </div>
                <div style={{ fontSize: "9px", lineHeight: "1.35", color: "#8f8f9b", marginTop: "6px", letterSpacing: "0" }}>
                  orders unassigned vs assigned, before vs after
                </div>
              </div>
              <div style={{ background: "rgba(7,7,14,0.95)", padding: "18px 20px", textAlign: "center", cursor: "help" }} title="Platform-recorded completed deliveries per month, summed across all 10 countries.">
                <div style={{ fontSize: "24px", fontWeight: "700", color: "#f0f0f4", letterSpacing: "-0.03em" }}>
                  50K+
                </div>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.1em", color: "#63636d", marginTop: "4px", textTransform: "uppercase" }}>
                  Monthly Deliveries
                </div>
                <div style={{ fontSize: "9px", lineHeight: "1.35", color: "#8f8f9b", marginTop: "6px", letterSpacing: "0" }}>
                  completed deliveries logged, 10 countries
                </div>
              </div>
              <div style={{ background: "rgba(7,7,14,0.95)", padding: "18px 20px", textAlign: "center", cursor: "help" }} title="Production AI apps and autonomous agents live across the group.">
                <div style={{ fontSize: "24px", fontWeight: "700", color: "#f0f0f4", letterSpacing: "-0.03em" }}>
                  10+
                </div>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.1em", color: "#63636d", marginTop: "4px", textTransform: "uppercase" }}>
                  AI Apps &amp; Agents
                </div>
                <div style={{ fontSize: "9px", lineHeight: "1.35", color: "#8f8f9b", marginTop: "6px", letterSpacing: "0" }}>
                  production apps &amp; agents live across the group
                </div>
              </div>
              <div style={{ background: "rgba(7,7,14,0.95)", padding: "18px 20px", textAlign: "center", cursor: "help" }} title="Count of production reports live on the shared data warehouse.">
                <div style={{ fontSize: "24px", fontWeight: "700", color: "#f0f0f4", letterSpacing: "-0.03em" }}>
                  20+
                </div>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.1em", color: "#63636d", marginTop: "4px", textTransform: "uppercase" }}>
                  Power BI Reports
                </div>
                <div style={{ fontSize: "9px", lineHeight: "1.35", color: "#8f8f9b", marginTop: "6px", letterSpacing: "0" }}>
                  production reports live on the warehouse
                </div>
              </div>
            </div>
            <div style={{ padding: "20px 32px 28px" }}>
              <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#63636d", marginBottom: "10px" }}>
                Products Shipped
              </div>
              <div style={{ display: "flex", gap: "6px", flexWrap: "wrap" }}>
                <span style={{ fontSize: "11px", color: "var(--a,#34d399)", background: "rgba(var(--aRGB,52,211,153),0.06)", border: "1px solid rgba(var(--aRGB,52,211,153),0.12)", borderRadius: "4px", padding: "4px 10px" }}>
                  Last-Mile Dispatch Platform
                </span>
                <span style={{ fontSize: "11px", color: "var(--a,#34d399)", background: "rgba(var(--aRGB,52,211,153),0.06)", border: "1px solid rgba(var(--aRGB,52,211,153),0.12)", borderRadius: "4px", padding: "4px 10px" }}>
                  REST API Integrations
                </span>
                <span style={{ fontSize: "11px", color: "var(--a,#34d399)", background: "rgba(var(--aRGB,52,211,153),0.06)", border: "1px solid rgba(var(--aRGB,52,211,153),0.12)", borderRadius: "4px", padding: "4px 10px" }}>
                  AI Driver Behaviour Dashcams
                </span>
                <span style={{ fontSize: "11px", color: "var(--a,#34d399)", background: "rgba(var(--aRGB,52,211,153),0.06)", border: "1px solid rgba(var(--aRGB,52,211,153),0.12)", borderRadius: "4px", padding: "4px 10px" }}>
                  Power BI Reporting
                </span>
                <span style={{ fontSize: "11px", color: "var(--a,#34d399)", background: "rgba(var(--aRGB,52,211,153),0.06)", border: "1px solid rgba(var(--aRGB,52,211,153),0.12)", borderRadius: "4px", padding: "4px 10px" }}>
                  Data Warehouse — Synapse
                </span>
                <span style={{ fontSize: "11px", color: "var(--a,#34d399)", background: "rgba(var(--aRGB,52,211,153),0.06)", border: "1px solid rgba(var(--aRGB,52,211,153),0.12)", borderRadius: "4px", padding: "4px 10px" }}>
                  Claude Agents
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  Document Letterhead Management
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  SCM Tech Hub — PM Tool
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  Item Code Creation App
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  IT Ticket Auto-Creation
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  E-DN &amp; Paperless Deliveries
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  Customer Notifications
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  Control Tower
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  Auto-Plan (AI Scheduling)
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  SafeCount
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  Shopfloor Management
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  Driver Digitisation
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  CAPEX Automation
                </span>
              </div>
            </div>
            <div style={{ padding: "4px 32px 28px" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "8px" }}>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--a,#34d399)" }}>
                  {"// Ask Me About"}
                </div>
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.06em", color: "#63636d" }}>
                  tap a question &middot; STAR-ready answers
                </span>
              </div>
              <div style={{ border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", overflow: "hidden" }}>
                {arr(v.careerGulf).map((cq: any, cqIndex: number) => (
                  <Fragment key={cqIndex}>
                    <div style={css(`border-bottom: 1px solid rgba(255,255,255,0.04); ${cq.rowStyle}`)}>
                      <div onClick={cq.onClick} style={{ cursor: "pointer", display: "flex", alignItems: "center", gap: "12px", padding: "14px 18px", transition: "background 0.2s" }} className="hv-7">
                        <span style={css(`font-family: var(--font-ibm-plex-mono), monospace; font-size: 8px; letter-spacing: 0.08em; font-weight: 600; border-radius: 4px; padding: 3px 8px; white-space: nowrap; flex-shrink: 0; ${cq.tagStyle}`)}>
                          {cq.tag}
                        </span>
                        <span style={{ fontSize: "13.5px", fontWeight: "600", color: "#e0e0e6", flex: "1", lineHeight: "1.4" }}>
                          {cq.q}
                        </span>
                        <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "18px", color: "var(--a,#34d399)", flexShrink: "0", lineHeight: "1" }}>
                          {cq.chevron}
                        </span>
                      </div>
                      {cq.open ? (
                        <>
                          <div style={{ padding: "4px 18px 20px" }}>
                            {cq.isStar ? (
                              <>
                                <div style={{ display: "grid", gridTemplateColumns: "24px 1fr", gap: "10px 14px", fontSize: "13px", lineHeight: "1.6", color: "#9a9aa5" }}>
                                  <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontWeight: "600", color: "var(--a,#34d399)" }}>
                                    S
                                  </span>
                                  <span>
                                    {cq.star.s}
                                  </span>
                                  <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontWeight: "600", color: "var(--a,#34d399)" }}>
                                    T
                                  </span>
                                  <span>
                                    {cq.star.t}
                                  </span>
                                  <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontWeight: "600", color: "var(--a,#34d399)" }}>
                                    A
                                  </span>
                                  <span>
                                    {cq.star.a}
                                  </span>
                                  <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontWeight: "600", color: "var(--a,#34d399)" }}>
                                    R
                                  </span>
                                  <span style={{ color: "#d0d0d8", fontWeight: "500" }}>
                                    {cq.star.r}
                                  </span>
                                </div>
                              </>
                            ) : null}
                            {cq.isList ? (
                              <>
                                <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                                  {arr(cq.bullets).map((b: any, bIndex: number) => (
                                    <Fragment key={bIndex}>
                                      <div style={{ display: "flex", gap: "10px", fontSize: "13px", lineHeight: "1.55", color: "#9a9aa5" }}>
                                        <span style={{ color: "rgba(var(--aRGB,52,211,153),0.5)", flexShrink: "0" }}>
                                          ▸
                                        </span>
                                        <span>
                                          {b}
                                        </span>
                                      </div>
                                    </Fragment>
                                  ))}
                                </div>
                              </>
                            ) : null}
                            {cq.isText ? (
                              <>
                                <p style={{ fontSize: "13px", lineHeight: "1.65", color: "#9a9aa5", margin: "0" }}>
                                  {cq.body}
                                </p>
                              </>
                            ) : null}
                            {cq.isMetrics ? (
                              <>
                                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" }}>
                                  <div style={{ background: "rgba(var(--aRGB,52,211,153),0.03)", border: "1px solid rgba(var(--aRGB,52,211,153),0.12)", borderRadius: "10px", padding: "14px 16px" }}>
                                    <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "12px" }}>
                                      Dispatch Web App
                                    </div>
                                    <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                                      {arr(cq.webApp).map((m: any, mIndex: number) => (
                                        <Fragment key={mIndex}>
                                          <div style={{ display: "flex", flexDirection: "column", gap: "2px" }}>
                                            <span style={{ fontSize: "12px", color: "#e0e0e6", fontWeight: "500" }}>
                                              {m.k}
                                            </span>
                                            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", color: "var(--a,#34d399)" }}>
                                              {m.v}
                                            </span>
                                          </div>
                                        </Fragment>
                                      ))}
                                    </div>
                                  </div>
                                  <div style={{ background: "rgba(167,139,250,0.03)", border: "1px solid rgba(167,139,250,0.15)", borderRadius: "10px", padding: "14px 16px" }}>
                                    <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#a78bfa", marginBottom: "12px" }}>
                                      Driver App · Android
                                    </div>
                                    <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                                      {arr(cq.driverApp).map((m: any, mIndex: number) => (
                                        <Fragment key={mIndex}>
                                          <div style={{ display: "flex", flexDirection: "column", gap: "2px" }}>
                                            <span style={{ fontSize: "12px", color: "#e0e0e6", fontWeight: "500" }}>
                                              {m.k}
                                            </span>
                                            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", color: "#a78bfa" }}>
                                              {m.v}
                                            </span>
                                          </div>
                                        </Fragment>
                                      ))}
                                    </div>
                                  </div>
                                </div>
                              </>
                            ) : null}
                            {cq.note ? (
                              <>
                                <div style={{ marginTop: "14px", background: "rgba(var(--aRGB,52,211,153),0.04)", border: "1px solid rgba(var(--aRGB,52,211,153),0.12)", borderRadius: "8px", padding: "10px 14px", fontSize: "12px", lineHeight: "1.55", color: "#9a9aa5" }}>
                                  {cq.note}
                                </div>
                              </>
                            ) : null}
                          </div>
                        </>
                      ) : null}
                    </div>
                  </Fragment>
                ))}
              </div>
            </div>
          </div>
          <div data-reveal="1" data-delay="1" style={{ background: "#0c0c14", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "16px", overflow: "hidden" }}>
            <div style={{ padding: "32px 32px 0" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "6px" }}>
                <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "#1e1e2a", border: "2px solid rgba(255,255,255,0.2)" }} />
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#8f8f9b" }}>
                  Completed
                </span>
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", color: "#63636d", marginLeft: "auto" }}>
                  Jan 2021 – Oct 2022
                </span>
              </div>
              <h3 style={{ fontSize: "22px", fontWeight: "700", letterSpacing: "-0.02em", margin: "8px 0 0", color: "#f0f0f4" }}>
                Technical Program Manager — CEO's Office
              </h3>
              <div style={{ fontSize: "14px", color: "#8f8f9b", marginTop: "4px" }}>
                Rivigo (Mahindra Logistics) · India · B2B full-truckload relay platform
              </div>
              <p style={{ fontSize: "14px", lineHeight: "1.7", color: "#9a9aa5", margin: "16px 0 0", maxWidth: "72ch" }}>
                Managed 8+ simultaneous strategic workstreams reporting directly to the CEO. Enhanced API integrations with Flipkart. Deployed shopfloor management tech at relay-point hubs. Redesigned relay-point workflows across 500+ enterprise contracts.
              </p>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "1px", background: "rgba(255,255,255,0.03)", marginTop: "24px" }}>
              <div style={{ background: "rgba(7,7,14,0.95)", padding: "18px 20px", textAlign: "center", cursor: "help" }} title="Freight volume moved for Flipkart after the API integration vs the comparable prior period.">
                <div style={{ fontSize: "24px", fontWeight: "700", color: "#f0f0f4", letterSpacing: "-0.03em" }}>
                  +15%
                </div>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.1em", color: "#63636d", marginTop: "4px", textTransform: "uppercase" }}>
                  Flipkart Throughput
                </div>
                <div style={{ fontSize: "9px", lineHeight: "1.35", color: "#8f8f9b", marginTop: "6px", letterSpacing: "0" }}>
                  real-time visibility + automated POD
                </div>
              </div>
              <div style={{ background: "rgba(7,7,14,0.95)", padding: "18px 20px", textAlign: "center", cursor: "help" }} title="Hub turnaround = avg truck handover + bay time per relay cycle, and the end-to-end TAT of the full delivery cycle from first-mile pickup to end-user delivery — after the cell-based shopfloor tech vs before (also freed 3.1 idle hrs).">
                <div style={{ fontSize: "24px", fontWeight: "700", color: "#f0f0f4", letterSpacing: "-0.03em" }}>
                  −28%
                </div>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.1em", color: "#63636d", marginTop: "4px", textTransform: "uppercase" }}>
                  Hub Turnaround
                </div>
                <div style={{ fontSize: "9px", lineHeight: "1.35", color: "#8f8f9b", marginTop: "6px", letterSpacing: "0" }}>
                  hub handover + end-to-end TAT, first-mile to delivery
                </div>
              </div>
              <div style={{ background: "rgba(7,7,14,0.95)", padding: "18px 20px", textAlign: "center", cursor: "help" }} title="Breached contracts / total enterprise contracts after the relay-point redesign vs baseline.">
                <div style={{ fontSize: "24px", fontWeight: "700", color: "#f0f0f4", letterSpacing: "-0.03em" }}>
                  −24%
                </div>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.1em", color: "#63636d", marginTop: "4px", textTransform: "uppercase" }}>
                  SLA Breach Rate
                </div>
                <div style={{ fontSize: "9px", lineHeight: "1.35", color: "#8f8f9b", marginTop: "6px", letterSpacing: "0" }}>
                  standardised relay-point workflow
                </div>
              </div>
              <div style={{ background: "rgba(7,7,14,0.95)", padding: "18px 20px", textAlign: "center", cursor: "help" }} title="Active enterprise contracts on the network the redesign applied to.">
                <div style={{ fontSize: "24px", fontWeight: "700", color: "#f0f0f4", letterSpacing: "-0.03em" }}>
                  500+
                </div>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.1em", color: "#63636d", marginTop: "4px", textTransform: "uppercase" }}>
                  Contracts Improved
                </div>
                <div style={{ fontSize: "9px", lineHeight: "1.35", color: "#8f8f9b", marginTop: "6px", letterSpacing: "0" }}>
                  enterprise contracts on the network
                </div>
              </div>
            </div>
            <div style={{ padding: "20px 32px 28px" }}>
              <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#63636d", marginBottom: "10px" }}>
                Key Workstreams
              </div>
              <div style={{ display: "flex", gap: "6px", flexWrap: "wrap" }}>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  Flipkart API Integrations
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  Relay-Point Redesign
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  Shopfloor Management
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  Driver Welfare Ops
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  Enterprise Integrations
                </span>
              </div>
            </div>
            <div style={{ padding: "4px 32px 28px" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "8px" }}>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--a,#34d399)" }}>
                  {"// Ask Me About"}
                </div>
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.06em", color: "#63636d" }}>
                  tap a question &middot; STAR-ready answers
                </span>
              </div>
              <div style={{ border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", overflow: "hidden" }}>
                {arr(v.careerRivigo).map((cq: any, cqIndex: number) => (
                  <Fragment key={cqIndex}>
                    <div style={css(`border-bottom: 1px solid rgba(255,255,255,0.04); ${cq.rowStyle}`)}>
                      <div onClick={cq.onClick} style={{ cursor: "pointer", display: "flex", alignItems: "center", gap: "12px", padding: "14px 18px", transition: "background 0.2s" }} className="hv-7">
                        <span style={css(`font-family: var(--font-ibm-plex-mono), monospace; font-size: 8px; letter-spacing: 0.08em; font-weight: 600; border-radius: 4px; padding: 3px 8px; white-space: nowrap; flex-shrink: 0; ${cq.tagStyle}`)}>
                          {cq.tag}
                        </span>
                        <span style={{ fontSize: "13.5px", fontWeight: "600", color: "#e0e0e6", flex: "1", lineHeight: "1.4" }}>
                          {cq.q}
                        </span>
                        <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "18px", color: "var(--a,#34d399)", flexShrink: "0", lineHeight: "1" }}>
                          {cq.chevron}
                        </span>
                      </div>
                      {cq.open ? (
                        <>
                          <div style={{ padding: "4px 18px 20px" }}>
                            {cq.isStar ? (
                              <>
                                <div style={{ display: "grid", gridTemplateColumns: "24px 1fr", gap: "10px 14px", fontSize: "13px", lineHeight: "1.6", color: "#9a9aa5" }}>
                                  <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontWeight: "600", color: "var(--a,#34d399)" }}>
                                    S
                                  </span>
                                  <span>
                                    {cq.star.s}
                                  </span>
                                  <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontWeight: "600", color: "var(--a,#34d399)" }}>
                                    T
                                  </span>
                                  <span>
                                    {cq.star.t}
                                  </span>
                                  <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontWeight: "600", color: "var(--a,#34d399)" }}>
                                    A
                                  </span>
                                  <span>
                                    {cq.star.a}
                                  </span>
                                  <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontWeight: "600", color: "var(--a,#34d399)" }}>
                                    R
                                  </span>
                                  <span style={{ color: "#d0d0d8", fontWeight: "500" }}>
                                    {cq.star.r}
                                  </span>
                                </div>
                              </>
                            ) : null}
                            {cq.isList ? (
                              <>
                                <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                                  {arr(cq.bullets).map((b: any, bIndex: number) => (
                                    <Fragment key={bIndex}>
                                      <div style={{ display: "flex", gap: "10px", fontSize: "13px", lineHeight: "1.55", color: "#9a9aa5" }}>
                                        <span style={{ color: "rgba(var(--aRGB,52,211,153),0.5)", flexShrink: "0" }}>
                                          ▸
                                        </span>
                                        <span>
                                          {b}
                                        </span>
                                      </div>
                                    </Fragment>
                                  ))}
                                </div>
                              </>
                            ) : null}
                            {cq.isText ? (
                              <>
                                <p style={{ fontSize: "13px", lineHeight: "1.65", color: "#9a9aa5", margin: "0" }}>
                                  {cq.body}
                                </p>
                              </>
                            ) : null}
                            {cq.isMetrics ? (
                              <>
                                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" }}>
                                  <div style={{ background: "rgba(var(--aRGB,52,211,153),0.03)", border: "1px solid rgba(var(--aRGB,52,211,153),0.12)", borderRadius: "10px", padding: "14px 16px" }}>
                                    <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "12px" }}>
                                      Dispatch Web App
                                    </div>
                                    <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                                      {arr(cq.webApp).map((m: any, mIndex: number) => (
                                        <Fragment key={mIndex}>
                                          <div style={{ display: "flex", flexDirection: "column", gap: "2px" }}>
                                            <span style={{ fontSize: "12px", color: "#e0e0e6", fontWeight: "500" }}>
                                              {m.k}
                                            </span>
                                            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", color: "var(--a,#34d399)" }}>
                                              {m.v}
                                            </span>
                                          </div>
                                        </Fragment>
                                      ))}
                                    </div>
                                  </div>
                                  <div style={{ background: "rgba(167,139,250,0.03)", border: "1px solid rgba(167,139,250,0.15)", borderRadius: "10px", padding: "14px 16px" }}>
                                    <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#a78bfa", marginBottom: "12px" }}>
                                      Driver App · Android
                                    </div>
                                    <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                                      {arr(cq.driverApp).map((m: any, mIndex: number) => (
                                        <Fragment key={mIndex}>
                                          <div style={{ display: "flex", flexDirection: "column", gap: "2px" }}>
                                            <span style={{ fontSize: "12px", color: "#e0e0e6", fontWeight: "500" }}>
                                              {m.k}
                                            </span>
                                            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", color: "#a78bfa" }}>
                                              {m.v}
                                            </span>
                                          </div>
                                        </Fragment>
                                      ))}
                                    </div>
                                  </div>
                                </div>
                              </>
                            ) : null}
                            {cq.note ? (
                              <>
                                <div style={{ marginTop: "14px", background: "rgba(var(--aRGB,52,211,153),0.04)", border: "1px solid rgba(var(--aRGB,52,211,153),0.12)", borderRadius: "8px", padding: "10px 14px", fontSize: "12px", lineHeight: "1.55", color: "#9a9aa5" }}>
                                  {cq.note}
                                </div>
                              </>
                            ) : null}
                          </div>
                        </>
                      ) : null}
                    </div>
                  </Fragment>
                ))}
              </div>
            </div>
          </div>
          <div data-reveal="1" data-delay="2" style={{ background: "#0c0c14", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "16px", overflow: "hidden" }}>
            <div style={{ padding: "32px 32px 0" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "6px" }}>
                <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "#1e1e2a", border: "2px solid rgba(255,255,255,0.2)" }} />
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#8f8f9b" }}>
                  Completed
                </span>
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", color: "#63636d", marginLeft: "auto" }}>
                  May 2020 – Jan 2021
                </span>
              </div>
              <h3 style={{ fontSize: "22px", fontWeight: "700", letterSpacing: "-0.02em", margin: "8px 0 0", color: "#f0f0f4" }}>
                Data Analyst — Operations &amp; Supply Chain
              </h3>
              <div style={{ fontSize: "14px", color: "#8f8f9b", marginTop: "4px" }}>
                Amazon · South India · Fulfilment Centres &amp; Last-Mile Delivery
              </div>
              <p style={{ fontSize: "14px", lineHeight: "1.7", color: "#9a9aa5", margin: "16px 0 0", maxWidth: "72ch" }}>
                Partnered with the Site Lead to overhaul middle-mile linehaul scheduling and last-mile delivery station workflows. Modelled shift allocation for productivity uplift. Built SQL-based operational reporting — loss, connected, breach, and shift/handover reports.
              </p>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "1px", background: "rgba(255,255,255,0.03)", marginTop: "24px" }}>
              <div style={{ background: "rgba(7,7,14,0.95)", padding: "18px 20px", textAlign: "center", cursor: "help" }} title="Avg truck fill rate on middle-mile linehaul after the scheduling overhaul vs before (also −11% inter-FC cost).">
                <div style={{ fontSize: "24px", fontWeight: "700", color: "#f0f0f4", letterSpacing: "-0.03em" }}>
                  +23%
                </div>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.1em", color: "#63636d", marginTop: "4px", textTransform: "uppercase" }}>
                  Load Efficiency
                </div>
                <div style={{ fontSize: "9px", lineHeight: "1.35", color: "#8f8f9b", marginTop: "6px", letterSpacing: "0" }}>
                  linehaul rescheduling consolidated loads
                </div>
              </div>
              <div style={{ background: "rgba(7,7,14,0.95)", padding: "18px 20px", textAlign: "center", cursor: "help" }} title="First-attempt successful deliveries / total attempts across the 4 redesigned stations, before vs after.">
                <div style={{ fontSize: "24px", fontWeight: "700", color: "#f0f0f4", letterSpacing: "-0.03em" }}>
                  +14%
                </div>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.1em", color: "#63636d", marginTop: "4px", textTransform: "uppercase" }}>
                  First-Attempt Delivery
                </div>
                <div style={{ fontSize: "9px", lineHeight: "1.35", color: "#8f8f9b", marginTop: "6px", letterSpacing: "0" }}>
                  redesigned last-mile station workflows
                </div>
              </div>
              <div style={{ background: "rgba(7,7,14,0.95)", padding: "18px 20px", textAlign: "center", cursor: "help" }} title="On-time deliveries / total across the 6 fulfilment nodes after the SQL reporting suite went live.">
                <div style={{ fontSize: "24px", fontWeight: "700", color: "#f0f0f4", letterSpacing: "-0.03em" }}>
                  +18%
                </div>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.1em", color: "#63636d", marginTop: "4px", textTransform: "uppercase" }}>
                  On-Time Delivery
                </div>
                <div style={{ fontSize: "9px", lineHeight: "1.35", color: "#8f8f9b", marginTop: "6px", letterSpacing: "0" }}>
                  live SQL issue reporting across 6 nodes
                </div>
              </div>
              <div style={{ background: "rgba(7,7,14,0.95)", padding: "18px 20px", textAlign: "center", cursor: "help" }} title="Manual report-assembly hours eliminated = associates × hours per report × monthly frequency.">
                <div style={{ fontSize: "24px", fontWeight: "700", color: "#f0f0f4", letterSpacing: "-0.03em" }}>
                  1.2K
                </div>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.1em", color: "#63636d", marginTop: "4px", textTransform: "uppercase" }}>
                  Hours Saved / Month
                </div>
                <div style={{ fontSize: "9px", lineHeight: "1.35", color: "#8f8f9b", marginTop: "6px", letterSpacing: "0" }}>
                  manual report assembly eliminated
                </div>
              </div>
            </div>
            <div style={{ padding: "20px 32px 28px" }}>
              <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#63636d", marginBottom: "10px" }}>
                Key Deliverables
              </div>
              <div style={{ display: "flex", gap: "6px", flexWrap: "wrap" }}>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  Linehaul Scheduling Overhaul
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  Last-Mile Station Redesign
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  Shift Allocation Model
                </span>
                <span style={{ fontSize: "11px", color: "#9a9aa5", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "4px 10px" }}>
                  SQL Ops Reporting Suite
                </span>
              </div>
            </div>
            <div style={{ padding: "4px 32px 28px" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "8px" }}>
                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--a,#34d399)" }}>
                  {"// Ask Me About"}
                </div>
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.06em", color: "#63636d" }}>
                  tap a question &middot; STAR-ready answers
                </span>
              </div>
              <div style={{ border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", overflow: "hidden" }}>
                {arr(v.careerAmazon).map((cq: any, cqIndex: number) => (
                  <Fragment key={cqIndex}>
                    <div style={css(`border-bottom: 1px solid rgba(255,255,255,0.04); ${cq.rowStyle}`)}>
                      <div onClick={cq.onClick} style={{ cursor: "pointer", display: "flex", alignItems: "center", gap: "12px", padding: "14px 18px", transition: "background 0.2s" }} className="hv-7">
                        <span style={css(`font-family: var(--font-ibm-plex-mono), monospace; font-size: 8px; letter-spacing: 0.08em; font-weight: 600; border-radius: 4px; padding: 3px 8px; white-space: nowrap; flex-shrink: 0; ${cq.tagStyle}`)}>
                          {cq.tag}
                        </span>
                        <span style={{ fontSize: "13.5px", fontWeight: "600", color: "#e0e0e6", flex: "1", lineHeight: "1.4" }}>
                          {cq.q}
                        </span>
                        <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "18px", color: "var(--a,#34d399)", flexShrink: "0", lineHeight: "1" }}>
                          {cq.chevron}
                        </span>
                      </div>
                      {cq.open ? (
                        <>
                          <div style={{ padding: "4px 18px 20px" }}>
                            {cq.isStar ? (
                              <>
                                <div style={{ display: "grid", gridTemplateColumns: "24px 1fr", gap: "10px 14px", fontSize: "13px", lineHeight: "1.6", color: "#9a9aa5" }}>
                                  <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontWeight: "600", color: "var(--a,#34d399)" }}>
                                    S
                                  </span>
                                  <span>
                                    {cq.star.s}
                                  </span>
                                  <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontWeight: "600", color: "var(--a,#34d399)" }}>
                                    T
                                  </span>
                                  <span>
                                    {cq.star.t}
                                  </span>
                                  <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontWeight: "600", color: "var(--a,#34d399)" }}>
                                    A
                                  </span>
                                  <span>
                                    {cq.star.a}
                                  </span>
                                  <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontWeight: "600", color: "var(--a,#34d399)" }}>
                                    R
                                  </span>
                                  <span style={{ color: "#d0d0d8", fontWeight: "500" }}>
                                    {cq.star.r}
                                  </span>
                                </div>
                              </>
                            ) : null}
                            {cq.isList ? (
                              <>
                                <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                                  {arr(cq.bullets).map((b: any, bIndex: number) => (
                                    <Fragment key={bIndex}>
                                      <div style={{ display: "flex", gap: "10px", fontSize: "13px", lineHeight: "1.55", color: "#9a9aa5" }}>
                                        <span style={{ color: "rgba(var(--aRGB,52,211,153),0.5)", flexShrink: "0" }}>
                                          ▸
                                        </span>
                                        <span>
                                          {b}
                                        </span>
                                      </div>
                                    </Fragment>
                                  ))}
                                </div>
                              </>
                            ) : null}
                            {cq.isText ? (
                              <>
                                <p style={{ fontSize: "13px", lineHeight: "1.65", color: "#9a9aa5", margin: "0" }}>
                                  {cq.body}
                                </p>
                              </>
                            ) : null}
                            {cq.isMetrics ? (
                              <>
                                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" }}>
                                  <div style={{ background: "rgba(var(--aRGB,52,211,153),0.03)", border: "1px solid rgba(var(--aRGB,52,211,153),0.12)", borderRadius: "10px", padding: "14px 16px" }}>
                                    <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "12px" }}>
                                      Dispatch Web App
                                    </div>
                                    <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                                      {arr(cq.webApp).map((m: any, mIndex: number) => (
                                        <Fragment key={mIndex}>
                                          <div style={{ display: "flex", flexDirection: "column", gap: "2px" }}>
                                            <span style={{ fontSize: "12px", color: "#e0e0e6", fontWeight: "500" }}>
                                              {m.k}
                                            </span>
                                            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", color: "var(--a,#34d399)" }}>
                                              {m.v}
                                            </span>
                                          </div>
                                        </Fragment>
                                      ))}
                                    </div>
                                  </div>
                                  <div style={{ background: "rgba(167,139,250,0.03)", border: "1px solid rgba(167,139,250,0.15)", borderRadius: "10px", padding: "14px 16px" }}>
                                    <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#a78bfa", marginBottom: "12px" }}>
                                      Driver App · Android
                                    </div>
                                    <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                                      {arr(cq.driverApp).map((m: any, mIndex: number) => (
                                        <Fragment key={mIndex}>
                                          <div style={{ display: "flex", flexDirection: "column", gap: "2px" }}>
                                            <span style={{ fontSize: "12px", color: "#e0e0e6", fontWeight: "500" }}>
                                              {m.k}
                                            </span>
                                            <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", color: "#a78bfa" }}>
                                              {m.v}
                                            </span>
                                          </div>
                                        </Fragment>
                                      ))}
                                    </div>
                                  </div>
                                </div>
                              </>
                            ) : null}
                            {cq.note ? (
                              <>
                                <div style={{ marginTop: "14px", background: "rgba(var(--aRGB,52,211,153),0.04)", border: "1px solid rgba(var(--aRGB,52,211,153),0.12)", borderRadius: "8px", padding: "10px 14px", fontSize: "12px", lineHeight: "1.55", color: "#9a9aa5" }}>
                                  {cq.note}
                                </div>
                              </>
                            ) : null}
                          </div>
                        </>
                      ) : null}
                    </div>
                  </Fragment>
                ))}
              </div>
            </div>
          </div>
        </div>
        <div data-reveal="1" style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "1px", background: "rgba(255,255,255,0.04)", borderRadius: "12px", overflow: "hidden", marginTop: "48px" }}>
          <div style={{ background: "rgba(7,7,14,0.95)", padding: "20px 22px" }}>
            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#63636d", marginBottom: "8px" }}>
              Education
            </div>
            <div style={{ fontSize: "13.5px", lineHeight: "1.6", color: "#9a9aa5" }}>
              B.Tech, NIT India · 2020 · University Gold Medalist · Best All-Rounder
            </div>
          </div>
          <div style={{ background: "rgba(7,7,14,0.95)", padding: "20px 22px" }}>
            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#63636d", marginBottom: "8px" }}>
              Certifications
            </div>
            <div style={{ fontSize: "13.5px", lineHeight: "1.6", color: "#9a9aa5" }}>
              CSPO · Azure AI Engineer · Google AI Professional · Dynamics 365 &amp; Power Platform · Azure Data Fundamentals
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
