// Generated by scripts/port-template.mjs from the design handoff package.
// Region: Proof / impact (prototype lines 692–707).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'

import { Fragment } from 'react'
import { arr } from '@/lib/style'
import type { ViewModel } from '@/lib/useViewModel'

export function HomeImpact({ v }: { v: ViewModel }) {
  return (
    <>
      <section id="impact" data-ps="1" style={{ position: "relative", maxWidth: "1200px", margin: "0 auto", padding: "100px 48px 0" }}>
        <div data-reveal="1">
          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#22d3ee", marginBottom: "14px" }}>
            {"// Proof"}
          </div>
          <h2 data-glitch="1" style={{ fontSize: "clamp(28px, 3.2vw, 42px)", fontWeight: "700", letterSpacing: "-0.03em", margin: "0", color: "#f0f0f4" }}>
            Outcomes, Not Adjectives
          </h2>
          <p style={{ fontSize: "15px", color: "#8f8f9b", margin: "8px 0 0", maxWidth: "60ch" }}>
            Every product I ship carries a number. This is what the work has moved.
          </p>
        </div>
        <div data-reveal="1" style={{ position: "relative", overflow: "hidden", borderTop: "1px solid rgba(255,255,255,0.06)", borderBottom: "1px solid rgba(255,255,255,0.06)", background: "rgba(11,11,18,0.5)", padding: "13px 0", marginTop: "34px" }}>
          <div style={{ position: "absolute", left: "0", top: "0", bottom: "0", width: "90px", background: "linear-gradient(90deg, #07070e, transparent)", zIndex: "2", pointerEvents: "none" }} />
          <div style={{ position: "absolute", right: "0", top: "0", bottom: "0", width: "90px", background: "linear-gradient(270deg, #07070e, transparent)", zIndex: "2", pointerEvents: "none" }} />
          <div style={{ display: "flex", width: "max-content", whiteSpace: "nowrap", fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#8a8a95", animation: "marqueeScroll 34s linear infinite" }}>
            {arr(v.impactTicker).map((t: any, tIndex: number) => (
              <Fragment key={tIndex}>
                <span style={{ display: "inline-flex", alignItems: "center", margin: "0 18px" }}>
                  {t}
                  <span style={{ color: "var(--a,#34d399)", marginLeft: "18px" }}>
                    /
                  </span>
                </span>
              </Fragment>
            ))}
          </div>
        </div>
      </section>
    </>
  )
}
