// Generated by scripts/port-template.mjs from the design handoff package.
// Region: Where I come from (prototype lines 1606–1626).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'



export function HomeRoots() {
  return (
    <>
      <section id="roots" data-ps="1" style={{ position: "relative", maxWidth: "1200px", margin: "0 auto", padding: "100px 48px 0" }}>
        <div data-reveal="1">
          <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "14px" }}>
            {"// Where I Come From"}
          </div>
          <h2 style={{ fontSize: "clamp(22px, 2.6vw, 32px)", fontWeight: "700", letterSpacing: "-0.02em", lineHeight: "1.25", margin: "0 0 20px", color: "#f0f0f4", maxWidth: "860px" }}>
            A computer scientist who loves building things &mdash; now based in Dubai.
          </h2>
          <p style={{ fontSize: "16px", lineHeight: "1.8", color: "#9a9aa5", margin: "0 0 40px", maxWidth: "820px" }}>
            I grew up in Bhubaneswar, Odisha, in eastern India, and studied at an NIT, where I graduated top of my university. I&rsquo;ve built my career across India and the Gulf, and I&rsquo;m based in Dubai today. I speak English and Hindi, and I&rsquo;m currently learning Arabic &mdash; which is part of why Arabic-first design matters to me in my healthcare work. What I enjoy most is taking a messy, manual process and turning it into something a system can run smoothly.
          </p>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "14px" }}>
            <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", padding: "22px" }}>
              <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "10px" }}>
                Education
              </div>
              <p style={{ fontSize: "14px", lineHeight: "1.6", color: "#9a9aa5", margin: "0" }}>
                B.Tech (Bachelor of Technology) — NIT. University Gold Medalist &amp; Best All-Rounder, 2020.
              </p>
            </div>
            <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", padding: "22px" }}>
              <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#22d3ee", marginBottom: "10px" }}>
                Languages
              </div>
              <p style={{ fontSize: "14px", lineHeight: "1.6", color: "#9a9aa5", margin: "0" }}>
                English &amp; Hindi — fluent. Arabic — currently learning.
              </p>
            </div>
            <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", padding: "22px" }}>
              <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#22d3ee", marginBottom: "10px" }}>
                Outside Work
              </div>
              <p style={{ fontSize: "14px", lineHeight: "1.6", color: "#9a9aa5", margin: "0" }}>
                Badminton on the court, active trading in the markets, and a lifelong thing for cars.
              </p>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
