// Generated by scripts/port-template.mjs from the design handoff package.
// Region: Mobile nav drawer (prototype lines 113–121).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'

import { Fragment } from 'react'
import { css, arr } from '@/lib/style'
import type { ViewModel } from '@/lib/useViewModel'

export function MobileNav({ v }: { v: ViewModel }) {
  return (
    <>
      {v.mobileNavOpen ? (
        <>
          <div onClick={v.closeMobileNav} style={{ position: "fixed", inset: "0", top: "61px", background: "rgba(4,4,8,0.6)", zIndex: "39", backdropFilter: "blur(4px)", animation: "fadeIn 0.2s ease" }} />
          <div style={{ position: "fixed", top: "61px", left: "0", right: "0", zIndex: "41", background: "rgba(9,9,16,0.98)", borderBottom: "1px solid rgba(var(--aRGB,52,211,153),0.14)", backdropFilter: "blur(20px)", padding: "12px 18px 20px", display: "flex", flexDirection: "column", gap: "2px", animation: "modalSlide 0.28s cubic-bezier(.2,.7,.2,1)", boxShadow: "0 24px 48px rgba(0,0,0,0.5)" }}>
            {arr(v.mNavItems).map((mn: any, mnIndex: number) => (
              <Fragment key={mnIndex}>
                <button type="button" onClick={mn.onClick} style={css(mn.style)}>
                  {mn.label}
                </button>
              </Fragment>
            ))}
            <a href="mailto:abdulmuwahib@gmail.com" onClick={v.closeMobileNav} style={{ marginTop: "10px", textAlign: "center", background: "var(--a,#34d399)", color: "#07070e", fontFamily: "var(--font-space-grotesk), system-ui, sans-serif", fontSize: "14px", fontWeight: "600", padding: "13px 20px", borderRadius: "10px" }}>
              Let's Build
            </a>
          </div>
        </>
      ) : null}
    </>
  )
}
