// Generated by scripts/port-template.mjs from the design handoff package.
// Region: Presentation mode bar (prototype lines 2782–2810).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'

import { Fragment } from 'react'
import { css, arr } from '@/lib/style'
import type { ViewModel } from '@/lib/useViewModel'

export function PresentationBar({ v }: { v: ViewModel }) {
  return (
    <>
      {v.presMode ? (
        <>
          <div style={{ position: "fixed", bottom: "0", left: "0", right: "0", zIndex: "700", background: "rgba(7,7,14,0.96)", borderTop: "1px solid rgba(var(--aRGB,52,211,153),0.25)", backdropFilter: "blur(16px)", padding: "0" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "0", padding: "8px 16px", overflowX: "auto" }}>
              <button type="button" onClick={v.presPrev} style={{ background: "none", border: "1px solid rgba(255,255,255,0.1)", color: "#9a9aa5", width: "32px", height: "32px", borderRadius: "6px", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: "0", marginRight: "8px", transition: "all 0.2s" }} className="hv-34">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                  <polyline points="15 18 9 12 15 6" />
                </svg>
              </button>
              {arr(v.presStepItems).map((ps: any, psIndex: number) => (
                <Fragment key={psIndex}>
                  <div onClick={ps.onClick} style={css(`cursor: pointer; padding: 6px 10px; border-radius: 6px; font-family: var(--font-ibm-plex-mono), monospace; font-size: 10px; letter-spacing: 0.04em; white-space: nowrap; transition: all 0.2s; display: flex; align-items: center; gap: 5px; flex-shrink: 0; ${ps.style}`)}>
                    <span style={{ fontWeight: "700" }}>
                      {ps.num}
                    </span>
                    <span>
                      {ps.label}
                    </span>
                  </div>
                </Fragment>
              ))}
              <button type="button" onClick={v.presNext} style={{ background: "none", border: "1px solid rgba(255,255,255,0.1)", color: "#9a9aa5", width: "32px", height: "32px", borderRadius: "6px", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: "0", marginLeft: "8px", transition: "all 0.2s" }} className="hv-34">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                  <polyline points="9 18 15 12 9 6" />
                </svg>
              </button>
              <div style={{ marginLeft: "auto", flexShrink: "0" }}>
                <button type="button" onClick={v.presExit} style={{ background: "none", border: "1px solid rgba(255,255,255,0.08)", color: "#8f8f9b", fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.08em", textTransform: "uppercase", padding: "5px 10px", borderRadius: "5px", cursor: "pointer", transition: "all 0.2s" }} className="hv-35">
                  ESC
                </button>
              </div>
            </div>
            <div style={{ padding: "6px 16px 10px", borderTop: "1px solid rgba(255,255,255,0.04)" }}>
              <div style={{ display: "flex", alignItems: "baseline", gap: "10px" }}>
                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--a,#34d399)", flexShrink: "0" }}>
                  Notes
                </span>
                <p style={{ fontSize: "12.5px", lineHeight: "1.55", color: "#9a9aa5", margin: "0" }}>
                  {v.presNote}
                </p>
              </div>
            </div>
          </div>
        </>
      ) : null}
    </>
  )
}
