// Generated by scripts/port-template.mjs from the design handoff package.
// Region: Project modal (prototype lines 1855–2389).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'

import { Fragment } from 'react'
import { css, arr } from '@/lib/style'
import { ImageSlot } from '@/components/ImageSlot'
import type { ViewModel } from '@/lib/useViewModel'

export function ProjectModal({ v }: { v: ViewModel }) {
  return (
    <>
      {v.modalOpen ? (
        <>
          <div onClick={v.closeModal} style={{ position: "fixed", inset: "0", background: "rgba(0,0,0,0.6)", zIndex: "50", backdropFilter: "blur(10px)", animation: "fadeIn 0.3s ease" }} />
          <div style={{ position: "fixed", inset: "0", zIndex: "51", overflowY: "auto", overscrollBehavior: "contain" }}>
            <div style={{ paddingTop: "50px", minHeight: "100vh" }}>
              <div style={{ background: "#0a0a12", borderRadius: "24px 24px 0 0", border: "1px solid rgba(var(--aRGB,52,211,153),0.1)", borderBottom: "none", animation: "modalSlide 0.5s cubic-bezier(.2,.7,.2,1)", padding: "48px 48px 80px", position: "relative", maxWidth: "1000px", margin: "0 auto" }} className="modal-card">
                <button type="button" onClick={v.closeModal} style={{ position: "absolute", top: "20px", right: "20px", background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: "50%", width: "40px", height: "40px", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: "#8f8f9b", fontSize: "18px", fontFamily: "system-ui", transition: "all 0.2s" }} className="hv-29">
                  ✕
                </button>
                <div style={{ marginBottom: "48px" }}>
                  <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", color: "var(--a,#34d399)", background: "rgba(var(--aRGB,52,211,153),0.08)", border: "1px solid rgba(var(--aRGB,52,211,153),0.2)", borderRadius: "999px", padding: "5px 14px", letterSpacing: "0.06em" }}>
                    {v.mp.badge}
                  </span>
                  <h2 data-glitch="1" style={{ fontSize: "clamp(28px, 3.5vw, 42px)", fontWeight: "700", letterSpacing: "-0.03em", lineHeight: "1.1", margin: "20px 0 0", color: "#f0f0f4" }}>
                    {v.mp.name}
                  </h2>
                  <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", marginTop: "16px" }}>
                    {arr(v.mp.tags).map((tag: any, tagIndex: number) => (
                      <Fragment key={tagIndex}>
                        <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.06em", color: "#8f8f9b", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "4px", padding: "5px 10px" }}>
                          {tag}
                        </span>
                      </Fragment>
                    ))}
                  </div>
                </div>
                {v.mpStudyLive ? (
                  <>
                    <div style={{ marginBottom: "40px", border: "1px solid rgba(var(--aRGB,52,211,153),0.25)", borderRadius: "12px", background: "linear-gradient(135deg, rgba(var(--aRGB,52,211,153),0.07), rgba(var(--aRGB,52,211,153),0.01))", padding: "20px 24px", display: "flex", gap: "16px", alignItems: "flex-start" }}>
                      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="var(--a,#34d399)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ flexShrink: "0", marginTop: "2px" }}>
                        <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
                        <polyline points="22 4 12 14.01 9 11.01" />
                      </svg>
                      <div>
                        <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "8px" }}>
                          <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--a,#34d399)" }}>
                            Live Product Teardown
                          </span>
                          <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#07070e", background: "var(--a,#34d399)", borderRadius: "4px", padding: "2px 7px", fontWeight: "600" }}>
                            {v.mpStudyLiveBadge}
                          </span>
                        </div>
                        <p style={{ fontSize: "13.5px", lineHeight: "1.65", color: "#b0b0ba", margin: "0" }}>
                          {v.mpStudyBasis}{' '}
                          <strong style={{ color: "#e0e0e6" }}>
                            I did not build this product
                          </strong>
                           &mdash; my contribution is the feature teardown of how it works and the 
                          <strong style={{ color: "var(--a,#34d399)" }}>
                            Enhancement Roadmap
                          </strong>
                           below: the improvements I&rsquo;d drive as its product manager.
                        </p>
                      </div>
                    </div>
                  </>
                ) : null}
                {v.mpStudyConcept ? (
                  <>
                    <div style={{ marginBottom: "40px", border: "1px solid rgba(167,139,250,0.28)", borderRadius: "12px", background: "linear-gradient(135deg, rgba(167,139,250,0.07), rgba(167,139,250,0.01))", padding: "20px 24px", display: "flex", gap: "16px", alignItems: "flex-start" }}>
                      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#a78bfa" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ flexShrink: "0", marginTop: "2px" }}>
                        <path d="M9 18h6" />
                        <path d="M10 22h4" />
                        <path d="M15.09 14c.18-.98.65-1.74 1.41-2.5A4.65 4.65 0 0 0 18 8 6 6 0 0 0 6 8c0 1 .23 2.23 1.5 3.5A4.61 4.61 0 0 1 8.91 14" />
                      </svg>
                      <div>
                        <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "8px" }}>
                          <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#a78bfa" }}>
                            Concept on Live Infrastructure
                          </span>
                          <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#07070e", background: "#a78bfa", borderRadius: "4px", padding: "2px 7px", fontWeight: "600" }}>
                            My proposal
                          </span>
                        </div>
                        <p style={{ fontSize: "13.5px", lineHeight: "1.65", color: "#b0b0ba", margin: "0" }}>
                          {v.mpStudyBasis}{' '}
                          <strong style={{ color: "#e0e0e6" }}>
                            The infrastructure is real and live; this specific product is my proposed concept
                          </strong>
                           on top of it &mdash; the concept design plus the 
                          <strong style={{ color: "#a78bfa" }}>
                            Enhancement Roadmap
                          </strong>
                           below are my contribution.
                        </p>
                      </div>
                    </div>
                  </>
                ) : null}
                {v.mpHasTabs ? (
                  <>
                    <div style={{ display: "flex", gap: "4px", marginBottom: "8px", borderBottom: "1px solid rgba(255,255,255,0.08)" }}>
                      {arr(v.mpTabs).map((tb: any, tbIndex: number) => (
                        <Fragment key={tbIndex}>
                          <button type="button" onClick={tb.onClick} style={css(tb.style)}>
                            {tb.label}
                          </button>
                        </Fragment>
                      ))}
                    </div>
                  </>
                ) : null}
                {v.mpShowOverview ? (
                  <>
                    <div>
                      <section style={{ marginBottom: "48px" }}>
                        <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "14px" }}>
                          {"// The Problem It Solves"}
                        </div>
                        <p style={{ fontSize: "16px", lineHeight: "1.75", color: "#9a9aa5", margin: "0 0 20px" }}>
                          {v.mp.problemDesc}
                        </p>
                        <div style={{ display: "grid", gap: "10px" }}>
                          {arr(v.mp.pains).map((pain: any, painIndex: number) => (
                            <Fragment key={painIndex}>
                              <div style={{ display: "flex", gap: "12px", fontSize: "14px", color: "#9a9aa5", alignItems: "baseline" }}>
                                <span style={{ color: "#63636d", flexShrink: "0" }}>
                                  ×
                                </span>
                                <span>
                                  {pain}
                                </span>
                              </div>
                            </Fragment>
                          ))}
                        </div>
                      </section>
                      <section style={{ marginBottom: "48px" }}>
                        <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "14px" }}>
                          {"// Role &amp; Approach"}
                        </div>
                        <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "14px" }}>
                          <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "12px", fontWeight: "600", color: "#f0f0f4", background: "rgba(var(--aRGB,52,211,153),0.08)", border: "1px solid rgba(var(--aRGB,52,211,153),0.15)", borderRadius: "6px", padding: "6px 14px" }}>
                            {v.mp.roleTitle}
                          </span>
                        </div>
                        <p style={{ fontSize: "15px", lineHeight: "1.75", color: "#9a9aa5", margin: "0" }}>
                          {v.mp.roleDesc}
                        </p>
                      </section>
                      <section style={{ marginBottom: "48px" }}>
                        <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "14px" }}>
                          {"// Solution Architecture"}
                        </div>
                        <p style={{ fontSize: "15px", lineHeight: "1.75", color: "#9a9aa5", margin: "0 0 20px" }}>
                          {v.mp.solutionDesc}
                        </p>
                        <div style={{ display: "grid", gap: "12px" }}>
                          {arr(v.mp.steps).map((step: any, stepIndex: number) => (
                            <Fragment key={stepIndex}>
                              <div style={{ display: "flex", gap: "12px", fontSize: "14px", color: "#9a9aa5", alignItems: "baseline" }}>
                                <span style={{ color: "var(--a,#34d399)", flexShrink: "0" }}>
                                  ✓
                                </span>
                                <span>
                                  {step}
                                </span>
                              </div>
                            </Fragment>
                          ))}
                        </div>
                      </section>
                      {v.mpHasDeliverables ? (
                        <>
                          <section style={{ marginBottom: "48px" }}>
                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#22d3ee", marginBottom: "20px" }}>
                              {"// Product Deliverables — what I&rsquo;d ship"}
                            </div>
                            <div style={{ display: "grid", gap: "12px" }}>
                              {arr(v.mp.deliverables).map((d: any, dIndex: number) => (
                                <Fragment key={dIndex}>
                                  <div style={{ display: "grid", gridTemplateColumns: "30px 1fr", gap: "16px", background: "rgba(34,211,238,0.03)", border: "1px solid rgba(34,211,238,0.15)", borderRadius: "12px", padding: "18px 22px", alignItems: "baseline" }}>
                                    <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "13px", fontWeight: "700", color: "#22d3ee" }}>
                                      {d.num}
                                    </div>
                                    <div>
                                      <h4 style={{ fontSize: "15px", fontWeight: "600", margin: "0 0 6px", color: "#f0f0f4" }}>
                                        {d.name}
                                      </h4>
                                      <p style={{ fontSize: "13px", lineHeight: "1.65", color: "#9a9aa5", margin: "0" }}>
                                        {d.desc}
                                      </p>
                                    </div>
                                  </div>
                                </Fragment>
                              ))}
                            </div>
                          </section>
                        </>
                      ) : null}
                      {v.mpHasPhases ? (
                        <>
                          <section style={{ marginBottom: "48px" }}>
                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "20px" }}>
                              {"// "}{v.mpBuildLabel}
                            </div>
                            <div style={{ display: "grid", gap: "0" }}>
                              {arr(v.mp.phases).map((ph: any, phIndex: number) => (
                                <Fragment key={phIndex}>
                                  <div style={{ display: "grid", gridTemplateColumns: "190px 1fr", gap: "24px", padding: "18px 0", borderBottom: "1px solid rgba(255,255,255,0.05)", alignItems: "start" }}>
                                    <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                                      <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "12px", fontWeight: "500", color: "#f0f0f4", letterSpacing: "0.02em" }}>
                                        {ph.name}
                                      </div>
                                      <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.16em", color: "rgba(var(--aRGB,52,211,153),0.6)" }}>
                                        {ph.status}
                                      </div>
                                    </div>
                                    <p style={{ fontSize: "14px", lineHeight: "1.7", color: "#9a9aa5", margin: "0" }}>
                                      {ph.detail}
                                    </p>
                                  </div>
                                </Fragment>
                              ))}
                            </div>
                          </section>
                        </>
                      ) : null}
                      <section style={{ marginBottom: "48px" }}>
                        <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "20px" }}>
                          {"// Key Features"}
                        </div>
                        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "14px" }}>
                          {arr(v.mp.features).map((feat: any, featIndex: number) => (
                            <Fragment key={featIndex}>
                              <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", padding: "24px", transition: "border-color 0.2s" }} className="hv-30">
                                <h4 style={{ fontSize: "15px", fontWeight: "600", margin: "0 0 8px", color: "#f0f0f4" }}>
                                  {feat.name}
                                </h4>
                                <p style={{ fontSize: "13px", lineHeight: "1.65", color: "#9a9aa5", margin: "0" }}>
                                  {feat.desc}
                                </p>
                              </div>
                            </Fragment>
                          ))}
                        </div>
                      </section>
                      {v.mpHasShipAI ? (
                        <>
                          <section style={{ marginBottom: "48px" }}>
                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#60a5fa", marginBottom: "20px" }}>
                              {"// How I Ship AI &mdash; embedded-model discipline"}
                            </div>
                            <div style={{ border: "1px solid rgba(96,165,250,0.2)", background: "linear-gradient(135deg, rgba(96,165,250,0.05), rgba(96,165,250,0.01))", borderRadius: "14px", overflow: "hidden" }}>
                              {arr(v.mpShipAI).map((row: any, rowIndex: number) => (
                                <Fragment key={rowIndex}>
                                  <div style={{ display: "grid", gridTemplateColumns: "168px 1fr", gap: "20px", padding: "16px 24px", borderBottom: "1px solid rgba(255,255,255,0.05)", alignItems: "baseline" }}>
                                    <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", letterSpacing: "0.06em", textTransform: "uppercase", color: "#93c5fd" }}>
                                      {row.k}
                                    </div>
                                    <p style={{ fontSize: "13.5px", lineHeight: "1.65", color: "#9a9aa5", margin: "0" }}>
                                      {row.v}
                                    </p>
                                  </div>
                                </Fragment>
                              ))}
                            </div>
                          </section>
                        </>
                      ) : null}
                    </div>
                  </>
                ) : null}
                {v.mpShowDeep ? (
                  <>
                    <section style={{ marginBottom: "48px" }}>
                      <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#60a5fa", marginBottom: "8px" }}>
                        {"// Deep Dive — How It Runs"}
                      </div>
                      <p style={{ fontSize: "13px", color: "#8f8f9b", margin: "0 0 24px", maxWidth: "76ch" }}>
                        The same lens applied to the shipped agent case studies — a traced request, the control loop, tool contracts, context &amp; memory, operating budget, and where autonomy stops.
                      </p>
                      <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#93c5fd", marginBottom: "14px" }}>
                        Worked Example — One Request, End to End
                      </div>
                      <div style={{ display: "flex", flexDirection: "column", gap: "8px", marginBottom: "34px" }}>
                        {arr(v.mpTechExample).map((ex: any, exIndex: number) => (
                          <Fragment key={exIndex}>
                            <div style={{ display: "flex", alignItems: "flex-start", gap: "12px", background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "10px", padding: "12px 14px" }}>
                              <span style={css(ex.chipStyle)}>
                                {ex.who}
                              </span>
                              <span style={{ fontSize: "13px", lineHeight: "1.6", color: "#d0d0d8" }}>
                                {ex.t}
                              </span>
                            </div>
                          </Fragment>
                        ))}
                      </div>
                      <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#93c5fd", marginBottom: "14px" }}>
                        Architecture — the Agent Loop
                      </div>
                      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "14px", marginBottom: "34px" }}>
                        {arr(v.mpTechArch).map((ar: any, arIndex: number) => (
                          <Fragment key={arIndex}>
                            <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", padding: "16px" }}>
                              <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "10px" }}>
                                <span style={css(ar.numStyle)}>
                                  {ar.num}
                                </span>
                                <span style={{ fontSize: "13px", fontWeight: "700", color: "#f0f0f4" }}>
                                  {ar.s}
                                </span>
                              </div>
                              <p style={{ fontSize: "12.5px", lineHeight: "1.6", color: "#a8a8b2", margin: "0" }}>
                                {ar.d}
                              </p>
                            </div>
                          </Fragment>
                        ))}
                      </div>
                      <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#93c5fd", marginBottom: "14px" }}>
                        Tool Contracts — I/O per Callable
                      </div>
                      <div style={{ display: "flex", flexDirection: "column", gap: "8px", marginBottom: "34px" }}>
                        {arr(v.mpTechContracts).map((tc: any, tcIndex: number) => (
                          <Fragment key={tcIndex}>
                            <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "10px", padding: "13px 15px" }}>
                              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "10px", flexWrap: "wrap" }}>
                                <span style={css(tc.nStyle)}>
                                  {tc.n}
                                </span>
                                <span style={css(tc.effStyle)}>
                                  {tc.e}
                                </span>
                              </div>
                              <div style={{ display: "grid", gridTemplateColumns: "auto 1fr", gap: "5px 12px", marginTop: "10px" }}>
                                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8.5px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#5a5a64", paddingTop: "2px" }}>
                                  args
                                </span>
                                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", lineHeight: "1.4", color: "#9a9aa5" }}>
                                  {tc.a}
                                </span>
                                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8.5px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#5a5a64", paddingTop: "2px" }}>
                                  returns
                                </span>
                                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", lineHeight: "1.4", color: "#9a9aa5" }}>
                                  {tc.r}
                                </span>
                              </div>
                            </div>
                          </Fragment>
                        ))}
                      </div>
                      <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#93c5fd", marginBottom: "14px" }}>
                        Context &amp; Memory Design
                      </div>
                      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(232px, 1fr))", gap: "14px", marginBottom: "34px" }}>
                        {arr(v.mpTechContext).map((cx: any, cxIndex: number) => (
                          <Fragment key={cxIndex}>
                            <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", padding: "16px" }}>
                              <div style={{ fontSize: "12px", fontWeight: "700", color: "#e0e0e6", marginBottom: "8px" }}>
                                {cx.k}
                              </div>
                              <p style={{ fontSize: "12.5px", lineHeight: "1.6", color: "#a8a8b2", margin: "0" }}>
                                {cx.d}
                              </p>
                            </div>
                          </Fragment>
                        ))}
                      </div>
                      <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#93c5fd", marginBottom: "14px" }}>
                        Cost · Latency · Scale
                      </div>
                      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: "1px", background: "rgba(255,255,255,0.05)", borderRadius: "12px", overflow: "hidden", marginBottom: "34px" }}>
                        {arr(v.mpTechBudget).map((bd: any, bdIndex: number) => (
                          <Fragment key={bdIndex}>
                            <div style={{ background: "#0a0a12", padding: "18px 16px" }}>
                              <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#8f8f9b" }}>
                                {bd.k}
                              </div>
                              <div style={{ fontSize: "17px", fontWeight: "700", color: "#f0f0f4", marginTop: "8px", letterSpacing: "-0.01em" }}>
                                {bd.v}
                              </div>
                            </div>
                          </Fragment>
                        ))}
                      </div>
                      <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#93c5fd", marginBottom: "14px" }}>
                        Autonomy &amp; Escalation Logic
                      </div>
                      <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                        {arr(v.mpTechAutonomy).map((au: any, auIndex: number) => (
                          <Fragment key={auIndex}>
                            <div style={{ display: "grid", gridTemplateColumns: "auto 1fr auto", gap: "14px", alignItems: "start", background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "10px", padding: "13px 15px" }}>
                              <span style={css(au.dotStyle)} />
                              <div>
                                <div style={{ fontSize: "12px", lineHeight: "1.45", color: "#e0e0e6" }}>
                                  {au.w}
                                </div>
                                <div style={{ fontSize: "11.5px", lineHeight: "1.45", color: "#8a8a95", marginTop: "3px" }}>
                                  → {au.a}
                                </div>
                              </div>
                              <span style={css(au.badgeStyle)}>
                                {au.badge}
                              </span>
                            </div>
                          </Fragment>
                        ))}
                      </div>
                      <p style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9.5px", letterSpacing: "0.06em", color: "#63636d", margin: "26px 0 0" }}>
                        Deep-dive figures are illustrative of the design — schemas, budgets, and thresholds are tuned per deployment.
                      </p>
                    </section>
                  </>
                ) : null}
                {v.zoomOpen ? (
                  <>
                    <div onClick={v.closeZoom} style={{ position: "fixed", inset: "0", zIndex: "500", background: "rgba(4,4,8,0.94)", overflow: "auto", padding: "28px", cursor: "zoom-out" }}>
                      <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#8f8f9b", marginBottom: "12px" }}>
                        Full resolution &middot; click anywhere to close
                      </div>
                      <div style={css(`width: ${v.zoomW}px; height: ${v.zoomH}px; background-image: url('${v.zoomSrc}'); background-size: 100% 100%; background-repeat: no-repeat; border-radius: 8px; box-shadow: 0 20px 60px rgba(0,0,0,0.6);`)} />
                    </div>
                  </>
                ) : null}
                {v.mpShowOverview ? (
                  <>
                    <div>
                      {v.mpHasNvidia ? (
                        <>
                          <section style={{ marginBottom: "48px" }}>
                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#76b900", marginBottom: "20px", display: "flex", alignItems: "center", gap: "10px" }}>
                              <svg width="20" height="20" viewBox="0 0 24 24" fill="#76b900">
                                <path d="M8.948 8.798v-1.43a6.7 6.7 0 0 1 .424-.018c3.922-.124 6.772 3.156 6.772 3.156s-3.098 3.59-6.252 3.59c-.332 0-.64-.035-.944-.1V10.2a3.56 3.56 0 0 1 2.836 1.226l2.1-1.856S11.934 8.106 9.372 8.106c-.142 0-.284.01-.424.022v-.33zm0-3.584v1.334c.14-.012.282-.022.424-.022 5.15-.168 8.545 4.354 8.545 4.354s-3.892 4.496-7.53 4.496c-.5 0-.976-.064-1.44-.186v1.192c.4.076.812.12 1.236.12 3.442 0 5.936-1.77 8.342-3.89.398.318 2.028 1.096 2.36 1.434-2.326 1.82-7.726 3.67-10.66 3.67-.434 0-.846-.038-1.278-.104v1.6H22V5.214H8.948zM2 5.214v14.572h5.2V18.33A8.1 8.1 0 0 1 4.7 14.39s1.6-1.914 2.5-2.368v-1.57c-1.574.634-3.324 2.89-3.324 2.89s1.092-3.584 3.324-5.166V6.256C4.854 7.5 2 11.08 2 11.08V5.214z" />
                              </svg>
                              {" // NVIDIA AI Infrastructure "}
                            </div>
                            <div style={{ display: "grid", gap: "14px" }}>
                              {arr(v.mp.nvidiaAI).map((nv: any, nvIndex: number) => (
                                <Fragment key={nvIndex}>
                                  <div style={{ background: "rgba(118,185,0,0.04)", border: "1px solid rgba(118,185,0,0.15)", borderRadius: "12px", padding: "20px 24px", display: "flex", flexDirection: "column", gap: "8px" }}>
                                    <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                                      <span style={{ fontFamily: "var(--font-space-grotesk), system-ui, sans-serif", fontSize: "15px", fontWeight: "600", color: "#76b900" }}>
                                        {nv.platform}
                                      </span>
                                      <a href={nv.url} target="_blank" rel="noopener" style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", color: "rgba(118,185,0,0.6)", textDecoration: "none", border: "1px solid rgba(118,185,0,0.2)", borderRadius: "4px", padding: "2px 8px" }} className="hv-31">
                                        NVIDIA Developer ↗
                                      </a>
                                    </div>
                                    <p style={{ fontSize: "13.5px", lineHeight: "1.65", color: "#9a9aa5", margin: "0" }}>
                                      {nv.role}
                                    </p>
                                  </div>
                                </Fragment>
                              ))}
                            </div>
                          </section>
                        </>
                      ) : null}
                      {v.mpHasModules ? (
                        <>
                          <section style={{ marginBottom: "48px" }}>
                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "20px" }}>
                              {"// Platform Deep Dive — What We Built"}
                            </div>
                            {arr(v.mp.modules).map((mod: any, modIndex: number) => (
                              <Fragment key={modIndex}>
                                <div style={{ border: "1px solid rgba(255,255,255,0.08)", borderRadius: "14px", overflow: "hidden", marginBottom: "18px" }}>
                                  <div style={{ padding: "20px 28px", background: "rgba(255,255,255,0.02)", borderBottom: "1px solid rgba(255,255,255,0.05)", display: "flex", alignItems: "baseline", gap: "14px", flexWrap: "wrap" }}>
                                    <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "13px", fontWeight: "600", color: "var(--a,#34d399)" }}>
                                      {mod.num}
                                    </span>
                                    <h4 style={{ fontSize: "18px", fontWeight: "700", letterSpacing: "-0.01em", color: "#f0f0f4", margin: "0" }}>
                                      {mod.name}
                                    </h4>
                                    <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", color: "var(--a,#34d399)", background: "rgba(var(--aRGB,52,211,153),0.08)", border: "1px solid rgba(var(--aRGB,52,211,153),0.2)", borderRadius: "4px", padding: "3px 8px", marginLeft: "auto" }}>
                                      {mod.status}
                                    </span>
                                  </div>
                                  <div style={{ padding: "20px 28px 24px" }}>
                                    <p style={{ fontSize: "14px", lineHeight: "1.65", color: "#9a9aa5", margin: "0 0 18px" }}>
                                      {mod.tagline}
                                    </p>
                                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px 20px", marginBottom: "22px" }}>
                                      {arr(mod.features).map((mf: any, mfIndex: number) => (
                                        <Fragment key={mfIndex}>
                                          <div style={{ display: "flex", gap: "10px", fontSize: "13px", lineHeight: "1.6", color: "#9a9aa5" }}>
                                            <span style={{ color: "rgba(var(--aRGB,52,211,153),0.45)", flexShrink: "0" }}>
                                              &#9656;
                                            </span>
                                            <span>
                                              {mf}
                                            </span>
                                          </div>
                                        </Fragment>
                                      ))}
                                    </div>
                                    <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
                                      {arr(mod.shots).map((ms: any, msIndex: number) => (
                                        <Fragment key={msIndex}>
                                          <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                                            <div role="img" aria-label={ms.caption} data-src={ms.src} data-w={ms.w} data-h={ms.h} onClick={v.zoomShot} title="Click to view full size" style={css(`width: 100%; aspect-ratio: ${ms.w} / ${ms.h}; background-image: url('${ms.src}'); background-size: 100% 100%; background-repeat: no-repeat; border: 1px solid rgba(255,255,255,0.08); border-radius: 10px; cursor: zoom-in;`)} />
                                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.06em", color: "#63636d" }}>
                                              {ms.caption}
                                            </div>
                                          </div>
                                        </Fragment>
                                      ))}
                                    </div>
                                  </div>
                                </div>
                              </Fragment>
                            ))}
                          </section>
                        </>
                      ) : null}
                      {v.mpHasScreens ? (
                        <>
                          <section style={{ marginBottom: "48px" }}>
                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "20px" }}>
                              {"// App Screens"}
                            </div>
                            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "14px" }}>
                              {arr(v.mp.screens).map((scr: any, scrIndex: number) => (
                                <Fragment key={scrIndex}>
                                  <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                                    <div style={{ height: "240px", background: "#08080f", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", overflow: "hidden" }}>
                                      <ImageSlot label={scr.hint} />
                                    </div>
                                    <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.06em", color: "#63636d" }}>
                                      {scr.caption}
                                    </div>
                                  </div>
                                </Fragment>
                              ))}
                            </div>
                          </section>
                        </>
                      ) : null}
                      <section style={{ marginBottom: "48px" }}>
                        <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "20px" }}>
                          {"// Impact Dashboard"}
                        </div>
                        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: "1px", background: "rgba(255,255,255,0.04)", borderRadius: "14px", overflow: "hidden" }}>
                          {arr(v.mp.impact).map((m: any, mIndex: number) => (
                            <Fragment key={mIndex}>
                              <div style={{ background: "rgba(7,7,14,0.95)", padding: "24px 16px", display: "flex", flexDirection: "column", alignItems: "center" }}>
                                <div style={{ position: "relative", width: "94px", height: "94px" }}>
                                  <svg viewBox="0 0 120 120" style={{ width: "100%", height: "100%" }}>
                                    <circle cx="60" cy="60" r="46" fill="none" stroke="rgba(255,255,255,0.06)" strokeWidth="3.5" strokeDasharray="216.77 72.26" strokeLinecap="round" transform="rotate(135 60 60)" />
                                    <circle data-gauge-arc={m.gauge} cx="60" cy="60" r="46" fill="none" stroke="var(--a,#34d399)" strokeWidth="3.5" strokeDasharray="216.77 72.26" strokeLinecap="round" transform="rotate(135 60 60)" style={{ filter: "drop-shadow(0 0 6px rgba(var(--aRGB,52,211,153),0.4))" }} />
                                  </svg>
                                  <div style={{ position: "absolute", inset: "0", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
                                    <div style={{ fontSize: "24px", fontWeight: "700", letterSpacing: "-0.03em", color: "#f0f0f4", lineHeight: "1" }} data-count={m.value} data-suffix={m.suffix}>
                                      {m.display}
                                    </div>
                                  </div>
                                </div>
                                <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#63636d", marginTop: "10px", textAlign: "center" }}>
                                  {m.label}
                                </div>
                                <div data-gauge-status style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "7px", color: "rgba(var(--aRGB,52,211,153),0.35)", letterSpacing: "0.1em", marginTop: "4px" }}>
                                  STANDBY
                                </div>
                              </div>
                            </Fragment>
                          ))}
                        </div>
                      </section>
                      {v.mpHasRealImpact ? (
                        <>
                          <section style={{ marginBottom: "48px" }}>
                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#22d3ee", marginBottom: "14px" }}>
                              {"// Real-World Impact"}
                            </div>
                            <div style={{ border: "1px solid rgba(34,211,238,0.2)", background: "linear-gradient(135deg, rgba(34,211,238,0.06), rgba(34,211,238,0.01))", borderRadius: "12px", padding: "22px 26px" }}>
                              <p style={{ fontSize: "15px", lineHeight: "1.75", color: "#d0d0d8", margin: "0" }}>
                                {v.mp.realImpact}
                              </p>
                            </div>
                          </section>
                        </>
                      ) : null}
                      {v.mpHasEcosystemNote ? (
                        <>
                          <section style={{ marginBottom: "48px" }}>
                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#f472b6", marginBottom: "14px" }}>
                              {"// How This Fits the Ecosystem"}
                            </div>
                            <div style={{ border: "1px solid rgba(244,114,182,0.2)", background: "linear-gradient(135deg, rgba(244,114,182,0.06), rgba(244,114,182,0.01))", borderRadius: "12px", padding: "22px 26px" }}>
                              <p style={{ fontSize: "14px", lineHeight: "1.75", color: "#d0d0d8", margin: "0" }}>
                                {v.mp.ecosystemNote}
                              </p>
                            </div>
                          </section>
                        </>
                      ) : null}
                    </div>
                  </>
                ) : null}
                {v.mpShowRoadmap ? (
                  <>
                    <div>
                      {v.mpHasPM ? (
                        <>
                          <section style={{ marginBottom: "48px" }}>
                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "20px" }}>
                              {"// Product Management Deep Dive"}
                            </div>
                            <div style={{ border: "1px solid rgba(255,255,255,0.08)", borderRadius: "12px", padding: "24px 28px", marginBottom: "14px" }}>
                              <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(var(--aRGB,52,211,153),0.7)", marginBottom: "16px" }}>
                                Case Narrative — STAR
                              </div>
                              <div style={{ display: "grid", gridTemplateColumns: "26px 1fr", gap: "12px 16px", fontSize: "13.5px", lineHeight: "1.65", color: "#9a9aa5" }}>
                                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontWeight: "600", color: "var(--a,#34d399)" }}>
                                  S
                                </span>
                                <span>
                                  {v.mpPm.star.s}
                                </span>
                                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontWeight: "600", color: "var(--a,#34d399)" }}>
                                  T
                                </span>
                                <span>
                                  {v.mpPm.star.t}
                                </span>
                                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontWeight: "600", color: "var(--a,#34d399)" }}>
                                  A
                                </span>
                                <span>
                                  {v.mpPm.star.a}
                                </span>
                                <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontWeight: "600", color: "var(--a,#34d399)" }}>
                                  R
                                </span>
                                <span>
                                  {v.mpPm.star.r}
                                </span>
                              </div>
                              <div style={{ background: "rgba(var(--aRGB,52,211,153),0.04)", border: "1px solid rgba(var(--aRGB,52,211,153),0.12)", borderRadius: "8px", padding: "12px 16px", marginTop: "16px", fontSize: "12.5px", lineHeight: "1.6", color: "#9a9aa5" }}>
                                <span style={{ color: "var(--a,#34d399)", fontWeight: "600" }}>
                                  Likely follow-up: 
                                </span>
                                {v.mpPm.star.followUp}
                              </div>
                            </div>
                            <div style={{ background: "linear-gradient(135deg, rgba(var(--aRGB,52,211,153),0.07), rgba(var(--aRGB,52,211,153),0.01))", border: "1px solid rgba(var(--aRGB,52,211,153),0.22)", borderRadius: "12px", padding: "24px 28px", marginBottom: "14px" }}>
                              <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(var(--aRGB,52,211,153),0.7)", marginBottom: "10px" }}>
                                North Star Metric
                              </div>
                              <div style={{ fontSize: "17px", fontWeight: "650", letterSpacing: "-0.01em", color: "#f0f0f4", lineHeight: "1.4", marginBottom: "8px" }}>
                                {v.mpPm.northStar}
                              </div>
                              <p style={{ fontSize: "13px", lineHeight: "1.65", color: "#9a9aa5", margin: "0" }}>
                                {v.mpPm.northStarWhy}
                              </p>
                            </div>
                            <div style={{ border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", overflow: "hidden", marginBottom: "14px" }}>
                              <div style={{ display: "grid", gridTemplateColumns: "1.1fr 0.6fr 1.7fr", gap: "16px", padding: "12px 24px", background: "rgba(255,255,255,0.02)", fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#63636d" }}>
                                <span>
                                  Success Metric
                                </span>
                                <span>
                                  Target
                                </span>
                                <span>
                                  Why this metric
                                </span>
                              </div>
                              {arr(v.mpPm.metrics).map((pmm: any, pmmIndex: number) => (
                                <Fragment key={pmmIndex}>
                                  <div style={{ display: "grid", gridTemplateColumns: "1.1fr 0.6fr 1.7fr", gap: "16px", padding: "14px 24px", borderTop: "1px solid rgba(255,255,255,0.04)", alignItems: "start" }}>
                                    <div style={{ fontSize: "13px", fontWeight: "600", color: "#f0f0f4", lineHeight: "1.5" }}>
                                      {pmm.name}
                                    </div>
                                    <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "12px", color: "var(--a,#34d399)" }}>
                                      {pmm.target}
                                    </div>
                                    <div style={{ fontSize: "12px", lineHeight: "1.6", color: "#9a9aa5" }}>
                                      {pmm.why}
                                    </div>
                                  </div>
                                </Fragment>
                              ))}
                            </div>
                            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "14px" }}>
                              {arr(v.mpPm.sections).map((pms: any, pmsIndex: number) => (
                                <Fragment key={pmsIndex}>
                                  <div style={{ background: "rgba(255,255,255,0.015)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "12px", padding: "20px 24px" }}>
                                    <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "14px" }}>
                                      {pms.title}
                                    </div>
                                    <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                                      {arr(pms.items).map((pmi: any, pmiIndex: number) => (
                                        <Fragment key={pmiIndex}>
                                          <div style={{ display: "flex", gap: "10px", fontSize: "13px", lineHeight: "1.6", color: "#9a9aa5" }}>
                                            <span style={{ color: "rgba(var(--aRGB,52,211,153),0.45)", flexShrink: "0" }}>
                                              &#9656;
                                            </span>
                                            <span>
                                              {pmi}
                                            </span>
                                          </div>
                                        </Fragment>
                                      ))}
                                    </div>
                                  </div>
                                </Fragment>
                              ))}
                            </div>
                          </section>
                        </>
                      ) : null}
                      {v.mpHasEnh ? (
                        <>
                          <section style={{ marginBottom: "48px" }}>
                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "8px" }}>
                              {"// Enhancement Roadmap"}
                            </div>
                            <p style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10.5px", lineHeight: "1.5", color: "#8f8f9b", margin: "0 0 20px" }}>
                              Grounded in the live product: 
                              <span style={{ color: "#22d3ee" }}>
                                {v.mpEnh.enhanceSource}
                              </span>
                            </p>
                            {v.mpHasQuick ? (
                              <>
                                <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "14px" }}>
                                  <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--a,#34d399)", background: "rgba(var(--aRGB,52,211,153),0.12)", border: "1px solid rgba(var(--aRGB,52,211,153),0.35)", borderRadius: "5px", padding: "4px 10px", fontWeight: "600" }}>
                                    Quick Wins
                                  </span>
                                  <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", color: "#8f8f9b" }}>
                                    low-hanging fruit &middot; realistic, shippable now
                                  </span>
                                </div>
                                <div style={{ display: "flex", flexDirection: "column", gap: "14px", marginBottom: "28px" }}>
                                  {arr(v.mpEnhQuick).map((en: any, enIndex: number) => (
                                    <Fragment key={enIndex}>
                                      <div style={{ border: "1px solid rgba(255,255,255,0.07)", borderRadius: "12px", padding: "20px 22px", background: "rgba(255,255,255,0.012)" }}>
                                        <div style={{ display: "flex", alignItems: "flex-start", gap: "12px", marginBottom: "14px" }}>
                                          <h4 style={{ fontSize: "15px", fontWeight: "650", color: "#f0f0f4", margin: "0", lineHeight: "1.4", flex: "1" }}>
                                            {en.enhance}
                                          </h4>
                                          <span style={css(`font-family: var(--font-ibm-plex-mono), monospace; font-size: 9px; letter-spacing: 0.08em; text-transform: uppercase; padding: 4px 10px; border-radius: 5px; border: 1px solid; white-space: nowrap; flex-shrink: 0; ${en.effortStyle}`)}>
                                            {en.effort} effort
                                          </span>
                                        </div>
                                        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px 20px" }}>
                                          <div>
                                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8.5px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#8f8f9b", marginBottom: "5px" }}>
                                              Today
                                            </div>
                                            <p style={{ fontSize: "12.5px", lineHeight: "1.55", color: "#8a8a95", margin: "0" }}>
                                              {en.current}
                                            </p>
                                          </div>
                                          <div>
                                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8.5px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(var(--aRGB,52,211,153),0.7)", marginBottom: "5px" }}>
                                              Justifying Metric
                                            </div>
                                            <p style={{ fontSize: "12.5px", lineHeight: "1.55", color: "#9a9aa5", margin: "0" }}>
                                              {en.metric}
                                            </p>
                                          </div>
                                        </div>
                                        <div style={{ marginTop: "14px", paddingTop: "14px", borderTop: "1px solid rgba(var(--aRGB,52,211,153),0.1)", display: "flex", alignItems: "baseline", gap: "10px" }}>
                                          <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8.5px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#22d3ee", flexShrink: "0" }}>
                                            Expected Impact
                                          </span>
                                          <p style={{ fontSize: "13px", lineHeight: "1.55", color: "#d0d0d8", margin: "0", fontWeight: "500" }}>
                                            {en.impact}
                                          </p>
                                        </div>
                                      </div>
                                    </Fragment>
                                  ))}
                                </div>
                              </>
                            ) : null}
                            {v.mpHasBets ? (
                              <>
                                <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "14px" }}>
                                  <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "9px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#a78bfa", background: "rgba(167,139,250,0.12)", border: "1px solid rgba(167,139,250,0.4)", borderRadius: "5px", padding: "4px 10px", fontWeight: "600" }}>
                                    Big Bets
                                  </span>
                                  <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", color: "#8f8f9b" }}>
                                    visionary &middot; where this product could go
                                  </span>
                                </div>
                                <div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
                                  {arr(v.mpEnhBets).map((en: any, enIndex: number) => (
                                    <Fragment key={enIndex}>
                                      <div style={{ border: "1px solid rgba(167,139,250,0.18)", borderRadius: "12px", padding: "20px 22px", background: "rgba(167,139,250,0.03)" }}>
                                        <div style={{ display: "flex", alignItems: "flex-start", gap: "12px", marginBottom: "14px" }}>
                                          <h4 style={{ fontSize: "15px", fontWeight: "650", color: "#f0f0f4", margin: "0", lineHeight: "1.4", flex: "1" }}>
                                            {en.enhance}
                                          </h4>
                                          <span style={css(`font-family: var(--font-ibm-plex-mono), monospace; font-size: 9px; letter-spacing: 0.08em; text-transform: uppercase; padding: 4px 10px; border-radius: 5px; border: 1px solid; white-space: nowrap; flex-shrink: 0; ${en.effortStyle}`)}>
                                            {en.effort} effort
                                          </span>
                                        </div>
                                        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px 20px" }}>
                                          <div>
                                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8.5px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#8f8f9b", marginBottom: "5px" }}>
                                              Today
                                            </div>
                                            <p style={{ fontSize: "12.5px", lineHeight: "1.55", color: "#8a8a95", margin: "0" }}>
                                              {en.current}
                                            </p>
                                          </div>
                                          <div>
                                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8.5px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(167,139,250,0.8)", marginBottom: "5px" }}>
                                              Justifying Metric
                                            </div>
                                            <p style={{ fontSize: "12.5px", lineHeight: "1.55", color: "#9a9aa5", margin: "0" }}>
                                              {en.metric}
                                            </p>
                                          </div>
                                        </div>
                                        <div style={{ marginTop: "14px", paddingTop: "14px", borderTop: "1px solid rgba(167,139,250,0.15)", display: "flex", alignItems: "baseline", gap: "10px" }}>
                                          <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "8.5px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#a78bfa", flexShrink: "0" }}>
                                            Expected Impact
                                          </span>
                                          <p style={{ fontSize: "13px", lineHeight: "1.55", color: "#d0d0d8", margin: "0", fontWeight: "500" }}>
                                            {en.impact}
                                          </p>
                                        </div>
                                      </div>
                                    </Fragment>
                                  ))}
                                </div>
                              </>
                            ) : null}
                          </section>
                        </>
                      ) : null}
                    </div>
                  </>
                ) : null}
                {v.mpShowOverview ? (
                  <>
                    <div>
                      {v.mpHasFeedback ? (
                        <>
                          <section style={{ marginBottom: "48px" }}>
                            <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "20px" }}>
                              {"// User Feedback"}
                            </div>
                            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "14px" }}>
                              {arr(v.mp.feedback).map((fb: any, fbIndex: number) => (
                                <Fragment key={fbIndex}>
                                  <div style={{ background: "rgba(var(--aRGB,52,211,153),0.02)", border: "1px solid rgba(var(--aRGB,52,211,153),0.12)", borderRadius: "12px", padding: "24px", display: "flex", flexDirection: "column", gap: "14px" }}>
                                    <p style={{ fontSize: "14px", lineHeight: "1.7", color: "#9a9aa5", margin: "0", fontStyle: "italic" }}>
                                      &ldquo;{fb.quote}&rdquo;
                                    </p>
                                    <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.08em", color: "var(--a,#34d399)" }}>
                                      &mdash; {fb.author}
                                    </div>
                                  </div>
                                </Fragment>
                              ))}
                            </div>
                          </section>
                        </>
                      ) : null}
                      <section style={{ marginBottom: "48px" }}>
                        <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "16px" }}>
                          {"// Tech Stack"}
                        </div>
                        <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
                          {arr(v.mp.tech).map((t: any, tIndex: number) => (
                            <Fragment key={tIndex}>
                              <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", color: "var(--a,#34d399)", background: "rgba(var(--aRGB,52,211,153),0.06)", border: "1px solid rgba(var(--aRGB,52,211,153),0.15)", borderRadius: "6px", padding: "8px 14px", letterSpacing: "0.04em" }}>
                                {t}
                              </span>
                            </Fragment>
                          ))}
                        </div>
                      </section>
                      <section>
                        <div style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "10px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--a,#34d399)", marginBottom: "14px" }}>
                          {"// Key Takeaway"}
                        </div>
                        <div style={{ borderLeft: "2px solid rgba(var(--aRGB,52,211,153),0.4)", paddingLeft: "24px" }}>
                          <p style={{ fontSize: "15px", lineHeight: "1.75", color: "#9a9aa5", margin: "0", fontStyle: "italic" }}>
                            {v.mp.lesson}
                          </p>
                        </div>
                      </section>
                    </div>
                  </>
                ) : null}
              </div>
            </div>
          </div>
        </>
      ) : null}
    </>
  )
}
