// Generated by scripts/port-template.mjs from the design handoff package.
// Region: Sticky header + primary nav (prototype lines 91–110).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'

import { Fragment } from 'react'
import { css, arr } from '@/lib/style'
import type { ViewModel } from '@/lib/useViewModel'

export function SiteHeader({ v }: { v: ViewModel }) {
  return (
    <>
      <header style={{ position: "sticky", top: "0", zIndex: "40", display: "flex", alignItems: "center", gap: "40px", padding: "14px 48px", background: "rgba(7,7,14,0.82)", backdropFilter: "blur(20px)", borderBottom: "1px solid rgba(255,255,255,0.04)" }}>
        <button type="button" onClick={v.goHome} data-magnetic="1" style={{ background: "none", border: "none", padding: "0", cursor: "pointer", color: "#f0f0f4", fontFamily: "var(--font-space-grotesk), system-ui, sans-serif", fontSize: "17px", fontWeight: "700", letterSpacing: "-0.02em", display: "flex", alignItems: "center", gap: "10px" }}>
          <span style={{ width: "26px", height: "26px", borderRadius: "7px", background: "var(--a,#34d399)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-space-grotesk), sans-serif", fontSize: "12px", fontWeight: "700", letterSpacing: "-0.03em", color: "#07070e", boxShadow: "0 0 18px rgba(var(--aRGB,52,211,153),0.5)" }}>
            AM
          </span>
           Abdul Muwahib 
        </button>
        <nav style={{ display: "flex", alignItems: "center", gap: "26px", margin: "0 auto", fontSize: "13.5px", fontWeight: "500" }} className="main-nav">
          {arr(v.navItems).map((nv: any, nvIndex: number) => (
            <Fragment key={nvIndex}>
              <button type="button" onClick={nv.onClick} data-magnetic="1" style={css(nv.style)} className="hv-1">
                {nv.label}
              </button>
            </Fragment>
          ))}
        </nav>
        <a href="mailto:abdulmuwahib@gmail.com" data-magnetic="1" style={{ background: "var(--a,#34d399)", color: "#07070e", fontSize: "13px", fontWeight: "600", padding: "9px 20px", borderRadius: "8px", transition: "all 0.2s", boxShadow: "0 4px 16px rgba(var(--aRGB,52,211,153),0.3)" }} className="nav-cta hv-2">
          Let's Build
        </a>
        <button type="button" onClick={v.toggleMobileNav} aria-label="Menu" style={{ alignItems: "center", justifyContent: "center", width: "42px", height: "42px", background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: "10px", cursor: "pointer", padding: "0", flexShrink: "0" }} className="nav-hamburger">
          {v.mobileNavOpen ? (
            <>
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#f0f0f4" strokeWidth="2" strokeLinecap="round">
                <line x1="18" y1="6" x2="6" y2="18" />
                <line x1="6" y1="6" x2="18" y2="18" />
              </svg>
            </>
          ) : null}
          {v.mobileNavClosed ? (
            <>
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#f0f0f4" strokeWidth="2" strokeLinecap="round">
                <line x1="3" y1="6" x2="21" y2="6" />
                <line x1="3" y1="12" x2="21" y2="12" />
                <line x1="3" y1="18" x2="21" y2="18" />
              </svg>
            </>
          ) : null}
        </button>
      </header>
    </>
  )
}
