// Generated by scripts/port-template.mjs from the design handoff package.
// Region: Footer (prototype lines 1790–1799).
// Markup is a faithful port of the signed-off design; behaviour lives in
// src/lib/useViewModel.ts. Regenerate rather than hand-editing structure.
'use client'



export function SiteFooter() {
  return (
    <>
      <footer style={{ borderTop: "1px solid rgba(255,255,255,0.04)", background: "rgba(4,4,8,0.95)" }}>
        <div style={{ maxWidth: "1200px", margin: "0 auto", padding: "44px 48px", display: "flex", alignItems: "center", justifyContent: "space-between", gap: "24px", flexWrap: "wrap" }}>
          <span style={{ fontSize: "16px", fontWeight: "700", letterSpacing: "-0.01em", color: "#f0f0f4" }}>
            Abdul Muwahib
          </span>
          <span style={{ fontFamily: "var(--font-ibm-plex-mono), monospace", fontSize: "11px", color: "#3a3a42" }}>
            © 2026 · Built with precision and strategic clarity.
          </span>
          <div style={{ display: "flex", gap: "20px", fontSize: "13px" }}>
            <a href="https://www.linkedin.com/in/abdul-muwahib" target="_blank" rel="noopener" style={{ color: "#8f8f9b", transition: "color 0.2s" }} className="hv-25">
              LinkedIn
            </a>
            <a href="https://github.com/abdul037" target="_blank" rel="noopener" style={{ color: "#8f8f9b", transition: "color 0.2s" }} className="hv-25">
              GitHub
            </a>
          </div>
        </div>
      </footer>
    </>
  )
}
