// Generated by scripts/port-data.mjs from the design handoff package.
// Source: design_handoff_portfolio_site/design/portfolio-deepdive.js
// Content is the source of truth for copy — edit here, not in the handoff.
// Deep-dive augmentation: phases (how it was built), screens (image slots), feedback (user quotes), impact fills.
export const PORTFOLIO_DEEPDIVE: Record<string, any> = {
  planner: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Shadowed 12 executives and managers through a week of inbox work — quantified 2-3h/day lost to triage and isolated the five recurring workflows worth automating.' },
      { name: '02 · Design', status: 'DONE', detail: 'Skills.md architecture with one skill per workflow (triage, meeting prep, missed messages, calendar) so each behavior could ship and iterate independently.' },
      { name: '03 · Build', status: 'DONE', detail: 'Graph API integration with delegated permissions, priority-scoring prompts tuned on four weeks of labeled emails, and hard guardrails against auto-sending anything.' },
      { name: '04 · Rollout', status: 'DONE', detail: '90-user pilot in three waves with weekly feedback loops — triage precision tuned from 71% to 94% before wave two went live.' }
    ],
    feedback: [
      { quote: 'It reads my morning like a chief of staff — I stopped opening my inbox first thing.', author: 'Country GM, pilot wave 1' },
      { quote: 'Meeting prep that used to take 30 minutes shows up on its own before every call.', author: 'Operations Director' }
    ]
  },
  ticket: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Mined 18 months of ServiceNow history — 62% of ticket volume came from nine repeat categories (passwords, VPN, access, installs).' },
      { name: '02 · Design', status: 'DONE', detail: 'Resolution decision trees per category with confidence thresholds; anything below threshold escalates to a human with full diagnostic context attached.' },
      { name: '03 · Build', status: 'DONE', detail: 'Claude + LangChain orchestration over ServiceNow APIs; automated fix actions executed via Azure Functions with complete audit logging.' },
      { name: '04 · Rollout', status: 'DONE', detail: 'Three weeks in shadow mode — agent proposes, humans approve — before switching to autonomous resolution at 800+ tickets/month.' }
    ],
    feedback: [
      { quote: 'Password resets went from four hours to four minutes — people noticed in the first week.', author: 'IT Helpdesk Lead' },
      { quote: 'Escalations now arrive with diagnostics attached. We fix instead of investigate.', author: 'Infrastructure Engineer' }
    ]
  },
  finstrat: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Sat with FP&A through a full quarterly cycle — mapped every workbook and the fourteen hand-offs behind a single forecast.' },
      { name: '02 · Design', status: 'DONE', detail: 'Scenario-first UX: assumptions as adjustable levers rather than buried cells, with Snowflake as the single data source.' },
      { name: '03 · Build', status: 'DONE', detail: 'PyTorch time-series models benchmarked against three years of actuals until they consistently beat manual forecasts — 92% vs 84% accuracy.' },
      { name: '04 · Rollout', status: 'DONE', detail: 'Ran one full quarter in parallel with the Excel process to build trust, then retired the workbooks.' }
    ],
    feedback: [
      { quote: 'We tested twelve scenarios last quarter. We used to manage two.', author: 'FP&A Manager' },
      { quote: 'The first planning cycle where the numbers and the narrative came from the same place.', author: 'Finance Director' }
    ]
  },
  ceo: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Interviewed the executive team on what "company health" actually means — distilled 40 candidate metrics down to the twelve that drive decisions.' },
      { name: '02 · Design', status: 'DONE', detail: 'GraphQL aggregation layer so every source system stayed untouched; health-score rubric co-designed with the CEO.' },
      { name: '03 · Build', status: 'DONE', detail: 'LLM narrative engine explaining each day\u2019s score movement; anomaly thresholds tuned per business unit to avoid alert fatigue.' },
      { name: '04 · Rollout', status: 'DONE', detail: 'Daily 7am brief to the exec team; natural-language query added after execs kept asking follow-up questions.' }
    ],
    feedback: [
      { quote: 'I check one number before my first meeting. That number replaced three reports.', author: 'CEO' },
      { quote: 'Board prep dropped from two days to an afternoon.', author: 'Executive Office' }
    ]
  },
  safecount: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Visited five plants across three countries — every site counted heads differently: paper logs, guards\u2019 memory, or nothing at all.' },
      { name: '02 · Design', status: 'DONE', detail: 'Two-surface design: dead-simple check-in for workers, live aggregation for admins — offline-first to survive plant connectivity gaps.' },
      { name: '03 · Build', status: 'DONE', detail: 'React Native + Supabase realtime; emergency-ping architecture returns a verified site headcount in under ten seconds.' },
      { name: '04 · Rollout', status: 'DONE', detail: 'Local champions recruited at each site — 27 plants live in four months with near-total adoption.' }
    ],
    feedback: [
      { quote: 'During the last drill we had a verified headcount in eight seconds. That used to take forty minutes.', author: 'HSE Manager' },
      { quote: 'The first tool where head office and gate security see the same number.', author: 'Plant Manager' }
    ]
  },
  fero: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Rode along with dispatch teams in three countries — documented 40+ local variants of what should have been one delivery workflow.' },
      { name: '02 · Design', status: 'DONE', detail: 'One standard order-to-delivery flow with per-country compliance layers, Dynamics 365 F&O as the system of record.' },
      { name: '03 · Build', status: 'DONE', detail: 'Vue.js platform with a REST integration layer; Auto-Plan ML route optimization trained on historical trip data.' },
      { name: '04 · Rollout', status: 'DONE', detail: 'Country-by-country rollout over 18 months — invoicing lag cut from ten days to same-day across all markets.' }
    ],
    feedback: [
      { quote: 'Dispatch planning is an hour now, not a morning.', author: 'Dispatch Supervisor, KSA' },
      { quote: 'For the first time I can compare delivery cost across all ten countries on one screen.', author: 'Group Logistics Director' }
    ],
    modules: [
      {
        num: '01', name: 'Dashboard', status: 'LIVE',
        tagline: 'The single pane of glass the platform grew from — every vertical, KPI, SLA, and trend in one screen.',
        features: [
          'Five operational verticals in one dashboard — Bulk, Package, Milkrun, Customer, and Fleet — each with its own KPI model',
          'Global filters: date range, 42 branches, and 36+ projects, at daily / weekly / monthly / yearly granularity',
          'Executive summary grid — 16+ KPIs per vertical with live health states: Healthy, Warning, At Risk, Critical',
          'SLA performance cards with explicit thresholds and breach counts — delivery-date compliance, attempt count, POD capture, weight-loss threshold, ops confirmation',
          'Composite Operational Health score rolling delivery success, failure-free, cancellation-free, fulfillment, and trip completion into one number',
          'Bulk-specific physics as first-class KPIs — weight fulfillment, average weight loss, and tank utilization',
          'Package equipment economics — inventory fulfillment, order fill rate, empty collection rate, and customer equipment balance across cylinders, racks, and dewars',
          'Trend analysis with period-over-period deltas — order volume, delivery rate, delivered volume, cycle time, drop count, and on-time completion, sliceable by product group'
        ],
        shots: [
          { src: '/assets/fero/Dashboard_Bulk_1.jpg', w: 1907, h: 945, caption: 'Dashboard · Bulk — executive summary KPIs with health states, and SLA performance with thresholds and breach counts' },
          { src: '/assets/fero/Dashboard_Bulk_2.jpg', w: 1898, h: 928, caption: 'Dashboard · Bulk — trend analysis: volume, delivery rate, cycle time, and weight loss by operational product group' },
          { src: '/assets/fero/Dashboard_PG_1.jpg', w: 1896, h: 947, caption: 'Dashboard · Package — fill rates, equipment balance, delivery-window SLAs, and quantity by unit of measure' },
          { src: '/assets/fero/Dashboard_PG_2.jpg', w: 1889, h: 933, caption: 'Dashboard · Package — order status distribution, quantity by rack / cylinder / dewar, and empty-collection, POD, and on-time trends' },
          { src: '/assets/fero/Dashboard_Milkrun.jpg', w: 1891, h: 946, caption: 'Dashboard · Milkrun — van-stock utilization, returned stock, POD capture, orders per trip, and cash collected per trip' },
          { src: '/assets/fero/Dashboard_Customers.jpg', w: 1901, h: 934, caption: 'Dashboard · Customer — customer-base KPIs, address-verification and contact-validity SLAs, and status distribution' },
          { src: '/assets/fero/Dashboard_Customers_2.jpg', w: 1889, h: 947, caption: 'Dashboard · Customer — top customers per segment and at-risk customers with declining-order detection (6mo vs prior 6mo)' },
          { src: '/assets/fero/Dashboard_Drivers.jpg', w: 1894, h: 921, caption: 'Dashboard · Fleet / Driver — utilization overview, on-time delivery, attendance, document validity, and driver SLAs' },
          { src: '/assets/fero/Dashboard_Vehicles.jpg', w: 1894, h: 889, caption: 'Dashboard · Fleet / Vehicle — utilization, downtime, and registration / insurance / MVPI / OPG compliance SLAs' }
        ]
      },
      {
        num: '02', name: 'Control Tower', status: 'LIVE',
        tagline: 'The live operations view — every trip and order on the map, per branch, as it happens. It replaces phone-call dispatching with one screen of ground truth.',
        features: [
          'Real-time map of the day\'s trips and orders per branch, across Bulk, Package, and Milkrun tabs — dispatchers stop calling drivers to ask "where are you?"',
          'Order locations and driver locations as switchable map layers, clustered by area — coverage gaps and idle capacity are visible at a glance',
          'Selected-trip route view overlaying planned vs actual path with numbered stop sequence — route deviations and skipped stops surface the moment they happen, not at end-of-day reconciliation',
          'Per-order side rail with ordered vs delivered weight/quantity, ETA, and status — short deliveries (e.g. partial drops) are caught while the truck is still in the field and recoverable',
          'Drill from any trip card straight into the trip or order record, so an exception spotted on the map becomes an action in two clicks',
          'Net effect: exception handling moves from reactive (customer calls to complain) to proactive (dispatcher intervenes mid-route), and end-of-day delivery disputes drop because planned vs actual is recorded per stop'
        ],
        shots: [
          { src: '/assets/fero/Control_Tower_Bulk.jpg', w: 1901, h: 931, caption: 'Control Tower · Bulk — live trips, order and driver locations on the map, delivered vs ordered weight per order' },
          { src: '/assets/fero/Control_Tower_PG.jpg', w: 1887, h: 933, caption: 'Control Tower · Package — selected trip route with planned vs actual path and numbered stop sequence' }
        ]
      },
      {
        num: '03', name: 'Order Management', status: 'LIVE',
        tagline: '103,000+ bulk orders under management — one structured lifecycle from D365 sales order to delivery.',
        features: [
          'Full order lifecycle statuses — Unassigned, Enroute, On Hold, Partially Delivered, Delivered — color-coded in the grid',
          'Every order tied to its D365 sales order number, customer code, and verified address ID',
          'Delivery / export movement types and sales / transfer order segments',
          'Faceted filters (project, status, order type, on-site, confirmation) plus saved-view and bulk-action tooling'
        ],
        shots: [
          { src: '/assets/fero/BulkOrders.jpg', w: 1889, h: 923, caption: 'Order Management · Bulk Orders — 103,260 orders with lifecycle status, D365 linkage, and customer address IDs' }
        ]
      },
      {
        num: '04', name: 'Trip Management', status: 'LIVE',
        tagline: 'Where orders become routes — 29,000+ bulk trips and 4,600+ milkrun trips planned, dispatched, and confirmed.',
        features: [
          'Trip lifecycle — Scheduled, Active, Completed, Cancelled — with exception flags surfaced in the first column',
          'Driver, vehicle, tank, and trailer assignment per trip, each linked to its master record',
          'Operational product group on every bulk trip — the right tank for the right gas',
          'Milkrun trip confirmation workflow with creation timestamps for morning dispatch discipline'
        ],
        shots: [
          { src: '/assets/fero/BulkTrips.jpg', w: 1889, h: 916, caption: 'Trip Management · Bulk Trips — 29,767 trips with driver / vehicle / tank assignment and exception flags' },
          { src: '/assets/fero/MilkrunTrips.jpg', w: 1890, h: 911, caption: 'Trip Management · Milkrun Trips — recurring van routes with confirmation status and driver-vehicle pairing' }
        ]
      },
      {
        num: '05', name: 'Customer Management', status: 'LIVE',
        tagline: '22,000+ customers and 44,000 delivery addresses — with a verification loop that fixes location data at the source.',
        features: [
          'Customer master across legal entities — customer types, milkrun and catalyst flags, cash-customer handling',
          'Customer addresses with GPS coordinates as first-class, order-blocking data',
          'Address verification workflow: driver-submitted corrections showing previous vs new address, coordinates, and distance moved',
          'Event subscriptions for customer-facing delivery notifications'
        ],
        shots: [
          { src: '/assets/fero/CustomerMaster.jpg', w: 1888, h: 908, caption: 'Customer Management · Customers — 22,185 customers across legal entities with type and segment flags' },
          { src: '/assets/fero/DeliveryAddressCorrection.jpg', w: 1890, h: 911, caption: 'Customer Management · Address Verification — driver-submitted corrections with previous vs new coordinates and distance-moved audit' }
        ]
      },
      {
        num: '06', name: 'Inventory & Item Master', status: 'LIVE',
        tagline: 'Every cylinder accounted for — 483,000+ serialized assets barcode-tracked from depot to customer and back.',
        features: [
          'Serialized inventory master — 483,253 barcoded units with depot, legal entity, and customer-address custody',
          'Custody trail answers the industry\'s oldest question: which customer holds which cylinders',
          'Item master: 433 items with weights, conversion factors, and operational product groups per legal entity',
          'UOM masters (cylinder, dewar, rack, container) powering equipment-balance analytics upstream'
        ],
        shots: [
          { src: '/assets/fero/InventoryManagement.jpg', w: 1893, h: 913, caption: 'Inventory Management — serialized, barcode-tracked units with customer custody fields' },
          { src: '/assets/fero/ItemMaster.jpg', w: 1891, h: 923, caption: 'Item Master — items with weights, conversion factors, operational product groups, and UoM per legal entity' }
        ]
      },
      {
        num: '07', name: 'Fleet Management', status: 'LIVE',
        tagline: 'The physical network — 977 vehicles plus trailers, tanks, and drivers, with attendance captured at the depot gate.',
        features: [
          'Vehicle master with asset type (truck, pickup, prime mover), ownership, capacity (VKW), depot, and project assignment',
          'Trailers, tanks, asset types, and drivers as linked master registries',
          'Driver check-in / check-out logs per depot with shift duration — attendance data feeding the Fleet dashboard SLAs',
          'Document tracking behind registration, insurance, and MVPI compliance KPIs'
        ],
        shots: [
          { src: '/assets/fero/FleetMaster.jpg', w: 1895, h: 916, caption: 'Fleet Management · Vehicles — 977 vehicles with asset type, ownership, capacity, and depot assignment' },
          { src: '/assets/fero/DriverWorkingHours.jpg', w: 1888, h: 904, caption: 'Fleet Management · Driver Check-In/Out Logs — 36,828 depot-gate attendance records with shift duration' }
        ]
      },
      {
        num: '08', name: 'Integration Logs', status: 'LIVE',
        tagline: 'The glass box around the D365 integration — 437,000+ order messages, every payload inspectable and replayable.',
        features: [
          'Order, trip, asset-status, driver-status, item, inventory, and customer-address log streams',
          'Per-message payload viewer with origin and execution project IDs for cross-entity flows',
          'Resend / replay actions turning integration failures into a self-service fix, not a support ticket',
          'Success and request-type filters for rapid triage of interface incidents'
        ],
        shots: [
          { src: '/assets/fero/IntegrationLogs.jpg', w: 1885, h: 912, caption: 'Integration Logs · Order Logs — 437,441 D365 integration messages with payload inspection and resend actions' }
        ]
      },
      {
        num: '09', name: 'Configurations', status: 'LIVE',
        tagline: 'The rulebook that lets one platform run ten countries — every operational parameter is data, not code.',
        features: [
          'Depot registry across countries and legal entities — 42 depots with geo-coded addresses',
          'Legal entities, projects, countries, cities, areas, and currencies as configurable masters',
          'Benchmark times, variable processing times, and status reasons tuning SLA logic per market',
          'Pre / post trip checklists, tags, and transporter registries driving driver-app behavior'
        ],
        shots: [
          { src: '/assets/fero/SystemAdminConfiguration.jpg', w: 1887, h: 936, caption: 'Configurations · Depots — 42 depots across legal entities and countries, geo-coded and audit-stamped' }
        ]
      },
      {
        num: '10', name: 'User Management', status: 'LIVE',
        tagline: 'Access control scoped to the operational map — users see the depots they run, nothing more.',
        features: [
          'Role plus permission-role model with per-user depot scoping across all countries',
          'Activation control and full audit-log download for compliance reviews',
          'Onboarding trail — every user records who added them'
        ],
        shots: [
          { src: '/assets/fero/UserAccess.jpg', w: 1890, h: 925, caption: 'User Management · Users — depot-scoped roles, activation state, and audit-log export' }
        ]
      }
    ]
  },
  routeplanning: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Gap analysis with dispatchers in every region — the real ask was visibility (working hours, constraints, tags), not just better optimization.' },
      { name: '02 · Design', status: 'DONE', detail: 'Colour-coding and tag systems designed side-by-side with the dispatchers who would read them daily.' },
      { name: '03 · Build', status: 'DONE', detail: 'ML model 2.0 for automated trip generation, plus a comparison view showing system plans against dispatcher plans honestly.' },
      { name: '04 · Rollout', status: 'DONE', detail: 'Deployed to all ten countries — system-generated plans flagged so adoption could be measured, not assumed.' }
    ],
    modules: [
      {
        num: '01', name: 'AI Auto-Plan — Trip Generation', status: 'LIVE',
        tagline: 'One click turns a day\u2019s open orders into a dispatch-ready trip plan \u2014 and every system-planned trip is flagged so adoption is measured, not assumed.',
        features: [
          'Auto Plan Trips: ML generates the full day\u2019s trip plan per project, branch, and movement type from open orders',
          'Reusable planning templates capturing a branch\u2019s dispatch strategy',
          'Per-trip vitals in one row \u2014 vehicle utilization %, stops, orders, and planned distance (km)',
          'System-planned trips carry the auto-plan flag; manual dispatches stay distinguishable \u2014 downloadable system-vs-manual comparison reports',
          'Zone-tagged trips honoring geographic zoning rules; unassigned orders clustered on the live map',
          'Manual overrides welcome \u2014 add trips, reassign drivers and vehicles, then export the trip manifest'
        ],
        shots: [
          { src: '/assets/fero/RoutePlanning.jpg', w: 1619, h: 924, caption: 'Route Planning \u2014 AI Auto-Plan: system-generated trips with utilization, stops, distance, and zone tags against the live order map' }
        ]
      }
    ],
    feedback: [
      { quote: 'The working-hours summary stopped compliance violations before they happened.', author: 'Fleet Compliance Officer' },
      { quote: 'I trust the system plans now because I can see exactly where they beat mine.', author: 'Senior Dispatcher' }
    ]
  },
  learninghub: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Audited paper-based training at six plants — completion untracked and content three revisions out of date.' },
      { name: '02 · Design', status: 'DONE', detail: 'Mobile-first with 5-minute modules; multilingual from day one to match the workforce mix.' },
      { name: '03 · Build', status: 'DONE', detail: 'React + Supabase with a certification engine producing audit-ready completion records.' },
      { name: '04 · Rollout', status: 'DONE', detail: 'Plant-by-plant rollout with safety officers owning their course content.' }
    ],
    impact: [
      { label: 'Plants live', value: 27, suffix: '', gauge: 90, display: '27' },
      { label: 'Module completion', value: 3, suffix: '\u00d7', gauge: 75, display: '3\u00d7' },
      { label: 'Languages', value: 4, suffix: '', gauge: 60, display: '4' }
    ],
    feedback: [
      { quote: 'Workers finish modules in the break-room queue. Completion tripled.', author: 'Plant Safety Officer' },
      { quote: 'Audit season went from panic to a filter click.', author: 'Group QHSE' }
    ]
  },
  doc_template: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Collected 200+ letterhead documents in circulation — found fourteen logo variants and legally outdated entity names still in use.' },
      { name: '02 · Design', status: 'DONE', detail: 'Template engine with per-entity branding rules maintained centrally by corporate communications.' },
      { name: '03 · Build', status: 'DONE', detail: 'Vue.js + PDF generation with a searchable, metadata-tagged document archive.' },
      { name: '04 · Rollout', status: 'DONE', detail: 'All legal entities onboarded; legacy templates deprecated with a hard cutoff date.' }
    ],
    impact: [
      { label: 'Entity coverage', value: 100, suffix: '%', gauge: 100, display: '100%' },
      { label: 'Formatting time cut', value: 90, suffix: '%', gauge: 90, display: '-90%' },
      { label: 'Logo variants retired', value: 14, suffix: '', gauge: 70, display: '14' }
    ],
    feedback: [
      { quote: 'Legal stopped finding wrong entity names on outbound letters.', author: 'Corporate Communications' },
      { quote: 'New joiners produce on-brand documents on day one.', author: 'HR Operations' }
    ]
  },
  consequence_mgmt: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Mapped the consequence policy with group HR — application varied widely between entities and managers.' },
      { name: '02 · Design', status: 'DONE', detail: 'Policy decision trees co-authored with HR and legal so every case follows the same path regardless of who runs it.' },
      { name: '03 · Build', status: 'DONE', detail: 'Vue.js case workflow with role-based access and an immutable audit trail.' },
      { name: '04 · Rollout', status: 'DONE', detail: 'Deployed to all entities; open cases migrated out of spreadsheets.' }
    ],
    impact: [
      { label: 'Case cycle time', value: 50, suffix: '%', gauge: 70, display: '-50%' },
      { label: 'Policy consistency', value: 100, suffix: '%', gauge: 100, display: '100%' },
      { label: 'Audit-ready cases', value: 100, suffix: '%', gauge: 95, display: '100%' }
    ],
    feedback: [
      { quote: 'Every case now has a defensible trail. That changed our audit posture completely.', author: 'Group HR Director' },
      { quote: 'Managers know the process is the same for everyone — that builds trust.', author: 'HR Business Partner' }
    ]
  },
  gpt_erp: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Logged a month of analyst report requests — 70% were variants of the same twenty questions.' },
      { name: '02 · Design', status: 'DONE', detail: 'Entity map of Dynamics 365 with hard guardrails: read-only, whitelisted entities, citation mandatory on every answer.' },
      { name: '03 · Build', status: 'DONE', detail: 'GPT-4 query translation with retry-and-verify; every answer cites the exact record and timestamp for audit.' },
      { name: '04 · Rollout', status: 'DONE', detail: 'Live with operations and finance — the analyst queue is now reserved for genuinely new questions.' }
    ],
    impact: [
      { label: 'Answer time', value: 10, suffix: 's', gauge: 90, display: 'Seconds' },
      { label: 'Report backlog cut', value: 70, suffix: '%', gauge: 75, display: '-70%' },
      { label: 'Teams live', value: 2, suffix: '', gauge: 50, display: '2' }
    ],
    feedback: [
      { quote: 'I ask in plain English and get the number with its source. No more ticket queue.', author: 'Operations Manager' },
      { quote: 'The citations are what sold it to audit.', author: 'Finance Controller' }
    ]
  },
  trading: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Journaled six months of discretionary trades first — the data showed the problem was discipline, not signal quality.' },
      { name: '02 · Design', status: 'DONE', detail: 'Journal-first design: every trade requires a written thesis before entry; ML signals stay advisory, never automatic.' },
      { name: '03 · Build', status: 'DONE', detail: 'TensorFlow models trained on three years of price data; WebSocket pipeline for live multi-asset feeds.' },
      { name: '04 · Live', status: 'DONE', detail: 'In personal daily use for 2+ years — 500+ journaled trades feeding the pattern analysis.' }
    ],
  },
  shipped_control_tower: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Fleet status was managed by phone; third-party fleets were entirely invisible to operations.' },
      { name: '02 · Design', status: 'DONE', detail: 'Map-first single view with per-country drill-down; IVMS connector spec agreed with third-party fleet providers.' },
      { name: '03 · Build', status: 'DONE', detail: 'Vue.js front-end over WebSocket streams; owned and contractor vehicles rendered on one live map.' },
      { name: '04 · Rollout', status: 'DONE', detail: 'Live in all countries including contractor fleets — the morning fleet call became a glance at a screen.' }
    ],
    impact: [
      { label: 'Countries live', value: 10, suffix: '', gauge: 83, display: '10' },
      { label: 'Fleet visibility', value: 100, suffix: '%', gauge: 100, display: '100%' },
      { label: '3rd-party fleets', value: 100, suffix: '%', gauge: 90, display: 'Integrated' }
    ],
    feedback: [
      { quote: 'The morning fleet call is now a glance at a screen.', author: 'Country Operations Manager' },
      { quote: 'Contractor trucks were a blind spot for years. Not anymore.', author: 'Group Logistics' }
    ]
  },
  shipped_edn_notif: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Mapped the delivery-note lifecycle and every point where customers called to ask about status.' },
      { name: '02 · Design', status: 'DONE', detail: 'Notification matrix per event and customer type across SMS and email, opt-in per customer.' },
      { name: '03 · Build', status: 'DONE', detail: 'Power Automate flows with an Azure SMS gateway, triggered by delivery-note lifecycle events.' },
      { name: '04 · Rollout', status: 'DONE', detail: 'Live across markets — proactive alerts replaced the reactive status-call queue.' }
    ],
    impact: [
      { label: 'Status calls cut', value: 40, suffix: '%', gauge: 65, display: '-40%' },
      { label: 'Lifecycle coverage', value: 100, suffix: '%', gauge: 100, display: '100%' },
      { label: 'Channels', value: 2, suffix: '', gauge: 60, display: 'SMS + Email' }
    ],
    feedback: [
      { quote: 'Customers stopped calling to ask where their gas is.', author: 'Customer Service Lead' },
      { quote: 'We know about delivery exceptions before the customer does.', author: 'Operations Coordinator' }
    ]
  },
  shipped_synapse: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Inventoried data across Dynamics 365, SAP, and operational systems — mapped entity overlaps and settled data ownership.' },
      { name: '02 · Design', status: 'DONE', detail: 'Star schema designed for analytical workloads with conformed dimensions across source systems.' },
      { name: '03 · Build', status: 'DONE', detail: 'Azure Data Factory pipelines with near-real-time refresh and cost governance from day one.' },
      { name: '04 · Rollout', status: 'DONE', detail: 'All downstream Power BI reporting migrated to the unified layer — ~30K in annual cost savings.' }
    ],
    feedback: [
      { quote: 'Report requests that took a week of data stitching now start from one model.', author: 'BI Analyst' },
      { quote: 'Finance and ops finally argue about decisions, not about whose numbers are right.', author: 'Group FP&A' }
    ]
  },
  shipped_qhse: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'KPI framework workshops with QHSE leadership — definitions agreed before a single visual was built.' },
      { name: '02 · Design', status: 'DONE', detail: 'Drill-down hierarchy from group to country to plant to individual incident.' },
      { name: '03 · Build', status: 'DONE', detail: 'Power BI over the Synapse layer with automated refresh from source systems.' },
      { name: '04 · Rollout', status: 'DONE', detail: '50+ scattered reports consolidated; monthly safety reviews now run off the live dashboard.' }
    ],
    feedback: [
      { quote: 'Safety reviews start from live data now, not last month\u2019s slide deck.', author: 'Group QHSE Manager' },
      { quote: 'I can trace a group-level trend to the exact plant and incident in three clicks.', author: 'Regional HSE Lead' }
    ]
  },
  shipped_assets_report: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Catalogued the manual checks operations ran daily on asset and driver status.' },
      { name: '02 · Design', status: 'DONE', detail: 'Threshold and escalation rules defined with each operations team per asset type.' },
      { name: '03 · Build', status: 'DONE', detail: 'Dynamics 365 event pipeline into Power BI with real-time alert surfacing.' },
      { name: '04 · Rollout', status: 'DONE', detail: 'Manual checking retired; every alert routes to a named owner.' }
    ],
    impact: [
      { label: 'Manual checks retired', value: 100, suffix: '%', gauge: 90, display: '100%' },
      { label: 'Alert latency', value: 100, suffix: '%', gauge: 95, display: 'Real-time' }
    ],
    feedback: [
      { quote: 'Issues find us now — we used to go looking for them.', author: 'Fleet Supervisor' }
    ]
  },
  shipped_open_orders: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Traced missed orders back through the funnel — the unassigned backlog was simply invisible to everyone.' },
      { name: '02 · Design', status: 'DONE', detail: 'Aging bands and priority scoring built from customer SLA, order value, and age.' },
      { name: '03 · Build', status: 'DONE', detail: 'Power BI over Dynamics 365 order states with drill-down by region, customer, and order type.' },
      { name: '04 · Rollout', status: 'DONE', detail: 'Once the backlog was visible, dispatch teams self-organized to clear it.' }
    ],
    impact: [
      { label: 'Backlog visibility', value: 100, suffix: '%', gauge: 100, display: '100%' },
      { label: 'Missed-order complaints', value: 60, suffix: '%', gauge: 70, display: '-60%' }
    ],
    feedback: [
      { quote: 'The aging colours made the backlog impossible to ignore — so it got cleared.', author: 'Dispatch Team Lead' }
    ]
  },
  asset_tracking: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Mapped asset lifecycles across production, gate security, delivery, and rentals — scoped into six workstreams.' },
      { name: '02 · Design', status: 'IN PROGRESS', detail: 'RFID/barcode standards and process redesign per workstream, production tracking first.' },
      { name: '03 · Build', status: 'PLANNED', detail: 'Phased delivery through 2026 — fill-to-dispatch tracking, then gates, delivery custody, and rentals.' },
      { name: '04 · Rollout', status: 'PLANNED', detail: 'Plant-by-plant with gate security as the enforcement point for data quality.' }
    ],
    impact: [
      { label: 'Workstreams', value: 6, suffix: '', gauge: 60, display: '6' },
      { label: 'Plants in scope', value: 27, suffix: '', gauge: 90, display: '27' },
      { label: 'Target: audit time', value: 80, suffix: '%', gauge: 75, display: '-80%' }
    ],
  },
  foundry: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Agent demand inventory across ops, sales, and supply chain — 20+ candidate use cases prioritized by value and feasibility.' },
      { name: '02 · Design', status: 'IN PROGRESS', detail: 'Builder UX and managed knowledge-base infrastructure on Azure AI Foundry.' },
      { name: '03 · Build', status: 'IN PROGRESS', detail: 'Standardized deployment pipeline with evaluation gates — no agent ships without passing its eval suite.' },
      { name: '04 · Rollout', status: 'PLANNED', detail: 'Pilot with three domains, then open to business teams as self-service.' }
    ],
    impact: [
      { label: 'Pilot domains', value: 3, suffix: '', gauge: 50, display: '3' },
      { label: 'Candidate use cases', value: 20, suffix: '+', gauge: 65, display: '20+' },
      { label: 'Target: agent build time', value: 90, suffix: '%', gauge: 80, display: 'Days' }
    ],
  },
  ms_fabric: {
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Workload audit of the Synapse estate against Microsoft Fabric capabilities.' },
      { name: '02 · Design', status: 'IN PROGRESS', detail: 'Semantic ontology for cross-domain data relationships — the layer every future AI project builds on.' },
      { name: '03 · Build', status: 'PLANNED', detail: 'Phased migration with zero-downtime cutover, workload by workload.' },
      { name: '04 · Rollout', status: 'PLANNED', detail: 'Self-service analytics and AI-ready data products across the enterprise.' }
    ],
    impact: [
      { label: 'Systems in scope', value: 5, suffix: '', gauge: 80, display: '5' },
      { label: 'Target: cutover downtime', value: 100, suffix: '%', gauge: 100, display: 'Zero' },
      { label: 'AI-ready coverage', value: 100, suffix: '%', gauge: 85, display: '100%' }
    ],
  },
  talent_mgmt: {
    tags: ['Azure OpenAI', 'Vue.js', 'HR Tech'],
    problemDesc: 'Hiring ran on email threads and spreadsheets — CVs screened inconsistently, interview loops uncoordinated, and no pipeline visibility for hiring managers.',
    pains: ['CV screening manual and inconsistent across roles', 'Interview scheduling by email ping-pong', 'No pipeline visibility for hiring managers', 'Candidate records scattered across inboxes'],
    roleDesc: 'Building the talent acquisition platform — AI-assisted CV screening, structured interview workflows, and pipeline analytics for hiring managers.',
    solutionDesc: 'Recruitment platform with AI-assisted CV screening against role profiles, structured interview loops with scorecards, and live pipeline dashboards.',
    steps: ['Role-profile builder defining evaluation criteria per position', 'AI CV screening ranking candidates against the profile with visible reasoning', 'Structured interview workflow with scorecards and panel coordination', 'Pipeline analytics — time-to-hire, funnel conversion, source quality'],
    features: [
      { name: 'AI CV Screening', desc: 'Candidates ranked against the role profile with explainable reasoning — not keyword matching.' },
      { name: 'Interview Loops', desc: 'Panels, scheduling, and scorecards coordinated in one workflow.' },
      { name: 'Pipeline Dashboard', desc: 'Live funnel per role — where candidates are and where they stall.' },
      { name: 'Candidate Record', desc: 'One record per candidate across roles and time — no more inbox archaeology.' }
    ],
    tech: ['Vue.js', 'Azure OpenAI', 'Supabase', 'Azure'],
    lesson: 'In development — early lesson: hiring managers trust AI screening only when it shows its reasoning for every candidate.',
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Mapped the hiring funnel with HR — screening effort and scheduling delays were the two biggest time sinks.' },
      { name: '02 · Design', status: 'IN PROGRESS', detail: 'Role-profile and scorecard model designed with recruiters and hiring managers.' },
      { name: '03 · Build', status: 'IN PROGRESS', detail: 'Screening engine and pipeline views in development on the Vue.js + Supabase stack.' },
      { name: '04 · Rollout', status: 'PLANNED', detail: 'Pilot with two departments before company-wide rollout.' }
    ],
    impact: [
      { label: 'Target: screening time', value: 70, suffix: '%', gauge: 70, display: '-70%' },
      { label: 'Target: time-to-hire', value: 30, suffix: '%', gauge: 60, display: '-30%' }
    ],
  },
  contract_mgmt: {
    tags: ['Azure OpenAI', 'Vue.js', 'Legal Tech'],
    problemDesc: 'Contracts lived in shared drives and inboxes — no central repository, no visibility into obligations, and renewals discovered after they lapsed.',
    pains: ['Contracts scattered across drives and email', 'Renewal dates discovered after expiry', 'Key clauses and obligations untracked', 'Legal review requests with no workflow or SLA'],
    roleDesc: 'Building the contract management solution — central repository, AI clause extraction, and renewal tracking with approval workflows.',
    solutionDesc: 'Central contract repository with AI clause extraction, obligation and renewal tracking, and approval workflows from draft through legal review to signature.',
    steps: ['Central repository with metadata and full-text search', 'AI extraction of parties, dates, values, and key clauses on upload', 'Renewal and obligation alerts routed to contract owners', 'Approval workflow from request through legal review to signature'],
    features: [
      { name: 'AI Clause Extraction', desc: 'Parties, terms, values, and renewal dates extracted automatically on upload.' },
      { name: 'Renewal Radar', desc: 'Alerts ahead of every renewal and expiry, routed to the contract owner.' },
      { name: 'Approval Workflow', desc: 'Structured path from request to signature with SLAs and an audit trail.' },
      { name: 'Obligation Tracker', desc: 'Contract commitments surfaced as trackable tasks with owners.' }
    ],
    tech: ['Vue.js', 'Azure OpenAI', 'Supabase', 'Azure'],
    lesson: 'In development — a contract repository is only trusted once the AI extraction proves itself on the contracts people already know by heart.',
    phases: [
      { name: '01 · Discovery', status: 'DONE', detail: 'Contract inventory across entities — surfaced lapsed renewals and untracked obligations.' },
      { name: '02 · Design', status: 'IN PROGRESS', detail: 'Extraction schema and approval workflow designed with legal.' },
      { name: '03 · Build', status: 'PLANNED', detail: 'Repository and extraction engine on the Vue.js + Azure OpenAI stack.' },
      { name: '04 · Rollout', status: 'PLANNED', detail: 'Backfill of existing contracts, then mandatory for all new agreements.' }
    ],
    impact: [
      { label: 'Target: lapsed renewals', value: 100, suffix: '%', gauge: 100, display: 'Zero' },
      { label: 'Target: retrieval time', value: 90, suffix: '%', gauge: 85, display: 'Seconds' }
    ],
  },
  demand_forecast: {
    shots: [
      { src: '/assets/deepdive/supply-chain/feat-demand.jpg', w: 1600, h: 1000, caption: 'Demand Forecasting — predictive consumption dashboard with forecast accuracy and stockout risk overview' },
      { src: '/assets/deepdive/supply-chain/dd-demand-1.jpg', w: 5120, h: 3200, caption: 'Demand Forecasting — per-customer consumption trends, forecast accuracy, and stockout risk board with days-to-stockout ranking' },
      { src: '/assets/deepdive/supply-chain/dd-demand-2.jpg', w: 5120, h: 3200, caption: 'Auto-Replenishment & Route Planning — proposed orders with depot routing, estimated distances, and one-click send-to-planning' }
    ],
    phases: [
      { name: 'Phase 1 · Data foundation', status: 'PROPOSED', detail: 'Assemble per-customer consumption histories from Dynamics 365 orders and Last Mile Platform delivery data (months 0-3).' },
      { name: 'Phase 2 · Model pilot', status: 'PROPOSED', detail: 'Two pilot countries — forecast accuracy validated against actuals before anything touches the order flow (months 3-6).' },
      { name: 'Phase 3 · Replenishment loop', status: 'PROPOSED', detail: 'Auto-generated proposals into the D365 order flow behind approval gates (months 6-9).' },
      { name: 'Phase 4 · Scale', status: 'PROPOSED', detail: 'All ten countries, enriched with cylinder telemetry where available (months 9-12).' }
    ],
    modules: [{
      num: '01', name: 'Demand Forecasting', status: 'PROPOSED',
      tagline: 'ML-driven consumption forecasting with auto-replenishment — replacing reactive ordering with proactive supply.',
      features: [
        'Demand Forecasting Dashboard — per-customer consumption trends, forecast accuracy, delivery efficiency, and SKU-level matching',
        'Stockout Risk Board — ranked customers by criticality with days-to-stockout and replenishment urgency color-coding',
        'Auto-Replenishment & Route Planning — proposed orders with route optimization across depots, estimated distances, and one-click send-to-planning'
      ]
    }],
  },
  network_twin: {
    shots: [
      { src: '/assets/deepdive/supply-chain/v6-cat-nettwin.jpg', w: 1600, h: 1000, caption: 'Logistics Network Digital Twin — end-to-end network model for scenario planning and optimisation' },
      { src: '/assets/deepdive/supply-chain/dd-nettwin-1.jpg', w: 5120, h: 3200, caption: 'Logistics Network Digital Twin — scenario controls with fleet size, depot capacity, and service-level parameters over a live network map' },
      { src: '/assets/deepdive/supply-chain/dd-nettwin-2.jpg', w: 5120, h: 3200, caption: 'Scenario Comparison — baseline vs alternative with delta analysis on total cost, transport, service level, on-time delivery, and CO2' }
    ],
    phases: [
      { name: 'Phase 1 · Mirror', status: 'PROPOSED', detail: 'Model the live network — depots, fleet, demand — from Last Mile Platform and IVMS feeds (months 0-3).' },
      { name: 'Phase 2 · Validate', status: 'PROPOSED', detail: 'Replay last quarter and match actual costs and service levels — the twin must predict the present first (months 3-5).' },
      { name: 'Phase 3 · Scenarios', status: 'PROPOSED', detail: 'Scenario builder for depots, fleet sizing, and routing policies with delta reports (months 5-8).' },
      { name: 'Phase 4 · Adopt', status: 'PROPOSED', detail: 'Twin review becomes a standing step in every network capex decision (months 8-12).' }
    ],
    modules: [{
      num: '01', name: 'Network Digital Twin', status: 'PROPOSED',
      tagline: 'A simulation of the logistics network that lets you test depot, fleet, and routing changes before committing capital.',
      features: [
        'Logistics Network Digital Twin — live map of depots, routes, and fleet with KPIs for coverage, utilization, and service level',
        'What-if Scenario Builder — adjust fleet size, depot capacity, and service-level targets with side-by-side impact preview',
        'Scenario Comparison Report — baseline vs alternative with delta analysis on cost, transport, service level, and delivery metrics'
      ]
    }],
  },
  fleet_maintenance: {
    shots: [
      { src: '/assets/deepdive/supply-chain/v6-cat-fleetmaint.jpg', w: 1600, h: 1000, caption: 'Fleet Health Monitoring — predictive maintenance dashboard across the vehicle fleet' },
      { src: '/assets/deepdive/supply-chain/dd-fleetmaint-1.jpg', w: 5120, h: 3200, caption: 'Vehicle Health Score — composite 82/100 score with engine, brakes, cooling, and tires subsystem gauges plus predicted-issue timeline' },
      { src: '/assets/deepdive/supply-chain/dd-fleetmaint-2.jpg', w: 5120, h: 3200, caption: 'Maintenance Scheduling Queue — priority-ranked work orders with severity color-coding, calendar view, and one-click scheduling' }
    ],
    phases: [
      { name: 'Phase 1 · Data', status: 'PROPOSED', detail: 'Aggregate IVMS telematics, fault codes, and service history per vehicle (months 0-3).' },
      { name: 'Phase 2 · Models', status: 'PROPOSED', detail: 'Failure-prediction models trained on historical breakdowns, validated against known incidents (months 3-6).' },
      { name: 'Phase 3 · Workflow', status: 'PROPOSED', detail: 'Health scores wired into the maintenance queue and route planning dispatch guard (months 6-9).' },
      { name: 'Phase 4 · Scale', status: 'PROPOSED', detail: 'Full fleet coverage with model retraining on every logged repair (months 9-12).' }
    ],
    modules: [{
      num: '01', name: 'Predictive Fleet Maintenance', status: 'PROPOSED',
      tagline: 'Telematics-driven health scoring that catches failures before they strand a truck on the road.',
      features: [
        'Fleet Health Monitoring Dashboard — overall fleet status with running, critical, warning, and good counts plus subsystem trend charts',
        'Vehicle Health Score — composite 82/100 score with engine, brakes, cooling, and tires gauges plus predicted issues timeline',
        'Maintenance Scheduling Queue — priority-ranked work orders with severity color-coding and calendar scheduling'
      ]
    }],
  },
  crm_copilot: {
    shots: [
      { src: '/assets/deepdive/crm/feat-salescopilot.jpg', w: 1600, h: 1000, caption: 'Sales Copilot for D365 — AI account assistant embedded in the CRM' },
      { src: '/assets/deepdive/crm/dd-crmcopilot-1.jpg', w: 5120, h: 3200, caption: 'Sales Copilot — conversational account brief with events timeline, next-best-action feed, and pre-visit account snapshot' },
      { src: '/assets/deepdive/crm/dd-crmcopilot-2.jpg', w: 5120, h: 3200, caption: 'Pre-Visit Account Brief & Next-Best-Action — health score, YTD revenue, open issues, and prioritized actions with confidence scores' }
    ],
    phases: [
      { name: 'Phase 1 · Grounding', status: 'PROPOSED', detail: 'RAG index over account records — orders, cases, contracts, activity history (months 0-2).' },
      { name: 'Phase 2 · Briefs', status: 'PROPOSED', detail: 'One-click pre-visit brief inside the D365 account view, piloted with one sales team (months 2-4).' },
      { name: 'Phase 3 · Actions', status: 'PROPOSED', detail: 'Quote drafting against price lists and next-best-action feed with citations (months 4-7).' },
      { name: 'Phase 4 · Scale', status: 'PROPOSED', detail: 'All account teams, with adoption and win-rate tracking (months 7-10).' }
    ],
    modules: [{
      num: '01', name: 'Sales Copilot for D365', status: 'PROPOSED',
      tagline: 'AI copilot embedded in Dynamics 365 — pre-visit briefs, account context, and next-best-action in the sales workflow.',
      features: [
        'Sales Copilot — conversational account brief with events timeline, order history, and real-time next-best-action recommendations',
        'Pre-Visit Account Brief — one-page account snapshot with health score, YTD revenue, open issues, and delivery map',
        'Next-Best-Action Feed — prioritized actions with confidence scores: renew, upsell, cross-sell ranked by propensity'
      ]
    }],
  },
  crm_churn: {
    shots: [
      { src: '/assets/deepdive/crm/v6-cat-churn.jpg', w: 1600, h: 1000, caption: 'Churn & Retention AI — at-risk account detection and retention overview' },
      { src: '/assets/deepdive/crm/dd-crmchurn-1.jpg', w: 5120, h: 3200, caption: 'Churn & Retention AI — at-risk account count, fund-at-risk value, risk distribution donut, and ranked at-risk worklist' },
      { src: '/assets/deepdive/crm/dd-crmchurn-2.jpg', w: 5120, h: 3200, caption: 'Retention Playbook — per-account action plan with offer strategy, progress tracking, and outcome measurement' }
    ],
    phases: [
      { name: 'Phase 1 · Signals', status: 'PROPOSED', detail: 'Join CRM activity, ERP order history, and case data per account (months 0-2).' },
      { name: 'Phase 2 · Model', status: 'PROPOSED', detail: 'Churn-risk models trained on historical account losses with reason codes (months 2-5).' },
      { name: 'Phase 3 · Worklist', status: 'PROPOSED', detail: 'Ranked at-risk worklist with retention playbooks in account managers\u2019 hands (months 5-8).' },
      { name: 'Phase 4 · Loop', status: 'PROPOSED', detail: 'Save-rate tracking feeding model retraining and playbook refinement (months 8-12).' }
    ],
    modules: [{
      num: '01', name: 'Churn & Retention AI', status: 'PROPOSED',
      tagline: 'Predictive churn scoring with retention playbooks — turning at-risk signals into save actions.',
      features: [
        'Churn & Retention AI Dashboard — at-risk account count, fund-at-risk value, risk distribution donut, and trend over time',
        'At-Risk Account Worklist — ranked accounts with health scores, revenue at risk, and churn drivers',
        'Retention Playbook — per-account action plan with offer strategy, progress tracking, and outcome measurement'
      ]
    }],
  },
  crm_portal: {
    shots: [
      { src: '/assets/deepdive/crm/v6-cat-custportal.jpg', w: 1600, h: 1000, caption: 'Customer Self-Service Portal — orders, deliveries, and invoices in one place' },
      { src: '/assets/deepdive/crm/dd-crmportal-1.jpg', w: 5120, h: 3200, caption: 'Customer Self-Service Portal — welcome view with orders, deliveries, invoices summary cards and My Orders with status tracking' },
      { src: '/assets/deepdive/crm/dd-crmportal-2.jpg', w: 5120, h: 3200, caption: 'Live Delivery Tracking — real-time map with driver location, ETA, distance, and delivery milestone timeline' }
    ],
    phases: [
      { name: 'Phase 1 · Identity', status: 'PROPOSED', detail: 'Customer identity and account linking against D365 with Azure AD B2C (months 0-2).' },
      { name: 'Phase 2 · Visibility', status: 'PROPOSED', detail: 'Live delivery tracking, invoices, and cylinder balances — the highest-call-volume pages first (months 2-5).' },
      { name: 'Phase 3 · Transactions', status: 'PROPOSED', detail: 'Order placement, repeats, and case-raising into the existing pipelines (months 5-8).' },
      { name: 'Phase 4 · Scale', status: 'PROPOSED', detail: 'All markets with call-deflection measurement per page (months 8-12).' }
    ],
    modules: [{
      num: '01', name: 'Customer Self-Service Portal', status: 'PROPOSED',
      tagline: 'A branded portal where customers track deliveries, view invoices, and manage cylinder balances without calling.',
      features: [
        'Customer Portal Home — welcome view with orders, deliveries, invoices summary cards and cylinder balance overview',
        'My Orders & Deliveries — order list with status, tabs for active/completed, and order details with ETA',
        'Live Delivery Tracking — real-time map with driver location, ETA, distance, and delivery milestone timeline'
      ]
    }],
  },
  pop_health: {
    nvidiaAI: [
      { platform: 'MONAI', role: 'Medical imaging AI framework for building risk-stratification models on clinical imaging and structured health data across Abu Dhabi\'s 2.3M population.', url: 'https://monai.io/' },
      { platform: 'BioMedical AI-Q Research Agent', role: 'Privacy-preserving reasoning over real-world patient data — connecting claims, encounters, and screening records to surface population-level chronic disease patterns.', url: 'https://build.nvidia.com/nvidia/biomedical-aiq-research-agent' }
    ],
    shots: [
      { src: '/assets/deepdive/healthcare/feat-pophealth.jpg', w: 1600, h: 1000, caption: 'Predictive Population Health — emirate-scale risk-stratification dashboard' },
      { src: '/assets/deepdive/healthcare/dd-pophealth-1.jpg', w: 5120, h: 3200, caption: 'Population Health Dashboard — Abu Dhabi regional risk heat-map with risk stratification pyramid and intervention campaign funnel' },
      { src: '/assets/deepdive/healthcare/dd-pophealth-2.jpg', w: 5120, h: 3200, caption: 'Intervention Campaign Tracker — targeted-to-completed funnel with screening rate, compliance rate, and completion metrics' }
    ],
    phases: [
      { name: 'Phase 1 · Data model', status: 'PROPOSED', detail: 'Unify claims, encounters, and screening data on a FHIR-based population model.' },
      { name: 'Phase 2 · Risk models', status: 'PROPOSED', detail: 'Diabetes and cardiovascular risk stratification, clinically validated before exposure.' },
      { name: 'Phase 3 · Cohorts', status: 'PROPOSED', detail: 'Cohort explorer with drill-downs by region, demographics, and comorbidity.' },
      { name: 'Phase 4 · Interventions', status: 'PROPOSED', detail: 'Outreach routing to providers with yield measurement per campaign.' }
    ],
    modules: [{
      num: '01', name: 'Population Health Platform', status: 'PROPOSED',
      tagline: 'Population-level risk stratification with intervention campaign management for Abu Dhabi\'s 2.3M residents.',
      features: [
        'Population Health Dashboard — Abu Dhabi map with regional risk heat-mapping, high-risk percentage, and chronic condition prevalence',
        'Risk Stratification Explorer — pyramid visualization of high/medium/low risk populations with age, gender, and nationality filters',
        'Intervention Campaign Tracker — funnel from targeted to completed with screening rate, compliance rate, and completion metrics'
      ]
    }],
  },
  newborn_screening: {
    nvidiaAI: [
      { platform: 'NVIDIA Parabricks', role: 'GPU-accelerated genomics pipeline for whole-genome sequencing of 815+ treatable conditions — reducing WGS secondary analysis from hours to minutes.', url: 'https://docs.nvidia.com/clara/parabricks/latest/index.html' },
      { platform: 'BioNeMo', role: 'AI development platform for variant interpretation models — ranking genomic findings by severity and treatability for genetic counsellor triage.', url: 'https://github.com/NVIDIA-BioNeMo' }
    ],
    shots: [
      { src: '/assets/deepdive/healthcare/v6-cat-newborn.jpg', w: 1600, h: 1000, caption: 'Newborn Genomic Screening — whole-genome screening platform for treatable conditions' },
      { src: '/assets/deepdive/healthcare/dd-newborn-1.jpg', w: 5120, h: 3200, caption: 'Newborn Genomic Screening — DNA helix triage worklist with severity badges and genetic counsellor triage ranking' },
      { src: '/assets/deepdive/healthcare/dd-newborn-2.jpg', w: 5120, h: 3200, caption: 'Pediatric Care Pathway Timeline — patient journey from triage through diagnostics, counselling, specialist review, to follow-up' }
    ],
    phases: [
      { name: 'Phase 1 · Intake', status: 'PROPOSED', detail: 'Consent capture and cord-blood sample registration inside the maternity ward workflow.' },
      { name: 'Phase 2 · Pipeline', status: 'PROPOSED', detail: 'WGS pipeline screening 815+ treatable conditions with chain-of-custody tracking.' },
      { name: 'Phase 3 · Triage', status: 'PROPOSED', detail: 'AI ranking of findings by severity and treatability for genetic counsellor review.' },
      { name: 'Phase 4 · Pathways', status: 'PROPOSED', detail: 'Confirmed cases routed to specialist care pathways with follow-up tracking.' }
    ],
    modules: [{
      num: '01', name: 'Newborn Genomic Screening', status: 'PROPOSED',
      tagline: 'AI-assisted triage for 815+ conditions — from cord blood to genetic counsellor worklist to care pathway.',
      features: [
        'Newborn Genomic Screening — triage worklist with DNA helix visualization, condition list with severity badges, and action buttons',
        'Genetic Counsellor Triage Worklist — patients ranked by condition severity and treatability with High/Medium/Low badges',
        'Pediatric Care Pathway Timeline — patient journey from triage through diagnostics, counselling, specialist review, to treatment and follow-up'
      ]
    }],
  },
  shifa_ai: {
    nvidiaAI: [
      { platform: 'Ambient Healthcare Agents', role: 'Generative AI reasoning models powering the bilingual patient voice agent — context-aware symptom triage, red-flag detection, and automated clinical documentation.', url: 'https://build.nvidia.com/nvidia/ambient-healthcare-agents' },
      { platform: 'BioMedical AI-Q Research Agent', role: 'Secure reasoning over cross-provider HIE records — generating clinician copilot summaries with care-gap flags grounded in the patient\'s full history.', url: 'https://build.nvidia.com/nvidia/biomedical-aiq-research-agent' }
    ],
    shots: [
      { src: '/assets/deepdive/healthcare/v6-cat-shifa.jpg', w: 1600, h: 1000, caption: 'ShifaAI — bilingual clinical AI assistant for triage and clinician support' },
      { src: '/assets/deepdive/healthcare/dd-shifa-1.jpg', w: 5120, h: 3200, caption: 'ShifaAI — bilingual chat with AR/EN toggle, symptom triage with red-flag detection and nearest-facility routing' },
      { src: '/assets/deepdive/healthcare/dd-shifa-2.jpg', w: 5120, h: 3200, caption: 'Clinician Copilot Summary — cross-provider patient view with care gaps, recommendations, and medication adherence flags' }
    ],
    phases: [
      { name: 'Phase 1 · Grounding', status: 'PROPOSED', detail: 'RAG architecture over HIE records with per-answer source citations.' },
      { name: 'Phase 2 · Triage', status: 'PROPOSED', detail: 'Bilingual symptom triage with red-flag escalation, safety-evaluated with clinicians.' },
      { name: 'Phase 3 · Copilot', status: 'PROPOSED', detail: 'Clinician summary of cross-provider history with care-gap flags.' },
      { name: 'Phase 4 · Scale', status: 'PROPOSED', detail: 'Emirate-wide rollout with continuous clinical safety review.' }
    ],
    modules: [{
      num: '01', name: 'ShifaAI Clinical Assistant', status: 'PROPOSED',
      tagline: 'Bilingual AI assistant for patients and clinicians — symptom triage with red-flag detection, and cross-provider clinical summaries.',
      features: [
        'ShifaAI Chat — bilingual conversational interface with AR/EN toggle for patient symptom intake',
        'Patient Symptom Triage — red-flag detection with urgency escalation, possible conditions, and nearest-facility routing',
        'Clinician Copilot Summary — cross-provider patient view with care gaps, recommendations, and medication adherence flags'
      ]
    }],
  },
  health_twin: {
    nvidiaAI: [
      { platform: 'BioNeMo', role: 'Biological modeling platform for building the digital twin\'s organ-system scoring models — projecting biomarker trajectories from wearable, lab, and clinical data.', url: 'https://github.com/NVIDIA-BioNeMo' },
      { platform: 'MONAI', role: 'Deep learning framework for medical data — powering the organ-system health scores that drive the twin\'s risk timeline and metabolic alerts.', url: 'https://monai.io/' }
    ],
    shots: [
      { src: '/assets/deepdive/healthcare/v6-cat-healthtwin.jpg', w: 1600, h: 1000, caption: 'Virtual Human Twin — personal digital-twin health model and risk timeline' },
      { src: '/assets/deepdive/healthcare/dd-healthtwin-1.jpg', w: 5120, h: 3200, caption: 'Health Twin — full-body visualization with organ-system scores and health risk timeline with biomarker trajectories' },
      { src: '/assets/deepdive/healthcare/dd-healthtwin-2.jpg', w: 5120, h: 3200, caption: 'AI Health Coach — daily action dashboard with sleep, movement, nutrition tracking and progress rings' }
    ],
    phases: [
      { name: 'Phase 1 · Ingest', status: 'PROPOSED', detail: 'Wearable streams, lab panels, and health records unified into the twin model.' },
      { name: 'Phase 2 · Timeline', status: 'PROPOSED', detail: 'Predictive risk timeline projecting biomarker trajectories forward.' },
      { name: 'Phase 3 · Coach', status: 'PROPOSED', detail: 'AI coach translating twin insights into daily prevention actions.' },
      { name: 'Phase 4 · Clinical', status: 'PROPOSED', detail: 'Clinician share-out so the twin informs real consults.' }
    ],
    modules: [{
      num: '01', name: 'Virtual Human Twin', status: 'PROPOSED',
      tagline: 'A personal health digital twin — biomarker trajectories, risk timelines, and an AI coach that turns data into daily actions.',
      features: [
        'Health Twin — full-body visualization with organ-system scores (heart, chest, kidney, gut, glucose) and trend indicators',
        'Health Risk Timeline — biomarker trajectories (glucose, blood pressure, cholesterol, weight) with risk zone mapping and metabolic alerts',
        'AI Health Coach — daily action dashboard with sleep, movement, nutrition, and goals tracking with progress rings'
      ]
    }],
  },
  tableegh: {
    nvidiaAI: [
      { platform: 'BioMedical AI-Q Research Agent', role: 'AI-powered epidemiological reasoning — connecting case demographics, lab results, travel history, and exposure data to accelerate outbreak pattern detection.', url: 'https://build.nvidia.com/nvidia/biomedical-aiq-research-agent' }
    ],
    shots: [
      { src: '/assets/deepdive/healthcare/v6-cat-tableegh.jpg', w: 1600, h: 1000, caption: 'Tableegh — disease surveillance and outbreak-investigation platform' },
      { src: '/assets/deepdive/healthcare/dd-tableegh-1.jpg', w: 5120, h: 3200, caption: 'Tableegh Disease Notification — dashboard with case counts and Emirates ID patient lookup with demographics auto-fill' },
      { src: '/assets/deepdive/healthcare/dd-tableegh-2.jpg', w: 5120, h: 3200, caption: 'Epidemiological Investigation — structured symptom, laboratory, travel history, and exposure data capture per case' }
    ],
    modules: [{
      num: '01', name: 'Tableegh Disease Surveillance', status: 'PROPOSED',
      tagline: 'Digital disease notification and epidemiological investigation — from case alert to contact tracing.',
      features: [
        'Disease Notification Dashboard — real-time case counts with new reports, under review, and closed status plus recent disease alerts',
        'Emirates ID Patient Lookup — instant patient identification with demographics, verified against the national registry',
        'Epidemiological Investigation Form — structured symptom, laboratory, travel history, and exposure data capture per case'
      ]
    }],
  },
  malaffi_caregaps: {
    nvidiaAI: [
      { platform: 'BioMedical AI-Q Research Agent', role: 'Privacy-preserving AI workflows over Malaffi\'s HIE data — identifying care gaps from cross-provider records and generating prioritised clinic worklists.', url: 'https://build.nvidia.com/nvidia/biomedical-aiq-research-agent' }
    ],
    shots: [
      { src: '/assets/deepdive/malaffi/v6-cat-malaffi-gaps.jpg', w: 1600, h: 1000, caption: 'Care-Gap Worklists — panel-management dashboard over Malaffi HIE data' },
      { src: '/assets/deepdive/malaffi/dd-caregaps-1.jpg', w: 5120, h: 3200, caption: 'Care-Gap Worklists — clinic worklist with per-patient risk scores, open gaps, overdue count, and outreach actions' },
      { src: '/assets/deepdive/malaffi/dd-caregaps-2.jpg', w: 5120, h: 3200, caption: 'Care-Gap Closure Tracking — pipeline view (outreach to appointment to completed) with per-patient status' }
    ],
    phases: [
      { name: 'Phase 1 · Rules', status: 'PROPOSED', detail: 'Join existing risk scores with registry care-gap rules into per-clinic panels.' },
      { name: 'Phase 2 · Worklists', status: 'PROPOSED', detail: 'Prioritised worklists — risk × gap severity × time since last contact.' },
      { name: 'Phase 3 · Outreach', status: 'PROPOSED', detail: 'One-tap actions: book, task a nurse, or send a Sahatna nudge.' },
      { name: 'Phase 4 · Loop', status: 'PROPOSED', detail: 'Closed-loop gap status rolled into DoH quality reporting.' }
    ],
    modules: [{
      num: '01', name: 'Care-Gap Worklists', status: 'PROPOSED',
      tagline: 'Turning Malaffi\'s risk scores into actionable clinic worklists with outreach tracking and gap closure measurement.',
      features: [
        'Care-Gap Worklists — summary cards (flagged, overdue, due soon) with per-patient worklist showing risk scores and gap types',
        'Clinic Worklist — patient-level view with risk scores, open gaps, overdue count, and one-click outreach actions',
        'Care-Gap Closure Tracking — pipeline view (outreach → appointment → completed) with per-patient status and closure counts'
      ]
    }],
  },
  malaffi_pgx: {
    nvidiaAI: [
      { platform: 'NVIDIA Parabricks', role: 'GPU-accelerated genomics suite for processing pharmacogenomic profiles — CYP2C19 and other gene-drug interaction data at clinical speed.', url: 'https://docs.nvidia.com/clara/parabricks/latest/index.html' },
      { platform: 'BioNeMo', role: 'AI platform for drug-gene interaction modeling — powering the sealed-data design where prescribing alerts fire without exposing the raw genomic report.', url: 'https://github.com/NVIDIA-BioNeMo' }
    ],
    shots: [
      { src: '/assets/deepdive/malaffi/v6-cat-malaffi-pgx.jpg', w: 1600, h: 1000, caption: 'PGx Rx Guard — pharmacogenomic prescribing-alert dashboard' },
      { src: '/assets/deepdive/malaffi/dd-pgx-1.jpg', w: 5120, h: 3200, caption: 'PGx Rx Guard — e-prescribing CYP2C19 interaction alert with metaboliser status, recommended dose, and accept/override actions' },
      { src: '/assets/deepdive/malaffi/dd-pgx-2.jpg', w: 5120, h: 3200, caption: 'PGx Alert Analytics — drug-class acceptance rates with per-class breakdown bars' }
    ],
    phases: [
      { name: 'Phase 1 · Rules base', status: 'PROPOSED', detail: 'Structure PGx reports into a drug-gene interaction rules base.' },
      { name: 'Phase 2 · Alerts', status: 'PROPOSED', detail: 'Inline prescribing alerts with metaboliser status and dose guidance at order entry.' },
      { name: 'Phase 3 · Privacy', status: 'PROPOSED', detail: 'Sealed-data design — alerts fire without exposing the genomic report.' },
      { name: 'Phase 4 · Tuning', status: 'PROPOSED', detail: 'Accept/override analytics tuning alert precision and proving value to DoH.' }
    ],
    modules: [{
      num: '01', name: 'PGx Rx Guard', status: 'PROPOSED',
      tagline: 'Pharmacogenomic prescribing guard — inline alerts at order entry with metaboliser status and dose guidance.',
      features: [
        'PGx Rx Guard — e-prescribing interception with drug-gene interaction alerts, metaboliser status, and recommended dose adjustment',
        'E-Prescribing Alert — CYP2C19 interaction warning with accept/override/view-details actions and risk visualization',
        'Alert Precision Analytics — drug-class-level acceptance rates, override tracking, and precision metrics for tuning'
      ]
    }],
  },
  malaffi_patient: {
    nvidiaAI: [
      { platform: 'Ambient Healthcare Agents', role: 'Patient-facing AI agent powering the companion app\'s bilingual assistant — personalized health navigation, plain-language record explanations, and appointment guidance.', url: 'https://build.nvidia.com/nvidia/ambient-healthcare-agents' }
    ],
    shots: [
      { src: '/assets/deepdive/malaffi/v6-cat-malaffi-patient.jpg', w: 1600, h: 1000, caption: 'Patient Companion — unified personal health record and access-transparency app' },
      { src: '/assets/deepdive/malaffi/dd-mpatient-1.jpg', w: 5120, h: 3200, caption: 'Malaffi Patient Companion — personalized home with AI assistant and My Health Record cards' },
      { src: '/assets/deepdive/malaffi/dd-mpatient-2.jpg', w: 5120, h: 3200, caption: 'Record Access Transparency — timestamped log of every facility and provider who viewed the patient record' }
    ],
    phases: [
      { name: 'Phase 1 · Identity', status: 'PROPOSED', detail: 'UAE Pass binding to the Malaffi master patient index.' },
      { name: 'Phase 2 · Record', status: 'PROPOSED', detail: 'Plain-language unified record view in Arabic and English.' },
      { name: 'Phase 3 · Transparency', status: 'PROPOSED', detail: 'Access log surfacing every record view with facility and role.' },
      { name: 'Phase 4 · Control', status: 'PROPOSED', detail: 'Correction requests and granular consent preferences.' }
    ],
    modules: [{
      num: '01', name: 'Patient Companion', status: 'PROPOSED',
      tagline: 'Patient-facing companion app — unified health record, AI-powered navigation, and full transparency on who accessed your data.',
      features: [
        'Malaffi Patient Companion — personalized home with AI assistant, sidebar navigation for visits, medications, results, and appointments',
        'My Unified Health Record — card-based view of conditions, medications, health encounters, and allergy/immunization records',
        'Record Access Transparency Log — timestamped log of every facility and provider who viewed the patient\'s record with purpose'
      ]
    }],
  }
};
