// Generated by scripts/port-data.mjs from the design handoff package.
// Source: design_handoff_portfolio_site/design/portfolio-pm.js
// Content is the source of truth for copy — edit here, not in the handoff.
// PM deep-dive augmentation for healthcare case studies: north star, success metrics, and PM craft sections.
export const PORTFOLIO_PM: Record<string, any> = {
  pop_health: {
    northStar: '% of AI-flagged high-risk residents receiving a documented intervention within 30 days',
    northStarWhy: 'A risk score that never changes care is analytics theatre. This number only moves when the model, the cohort UX, and the provider workflow all work — so it keeps the whole team honest.',
    star: { s: 'Chronic disease is the region\'s largest cost driver, care is reactive, and risk signals sit fragmented across providers — even though Malaffi has unified the data.', t: 'Design a population-health product that turns unified data into earlier intervention at 2M+ resident scale.', a: 'Interviewed public-health analysts and shadowed providers — insight dies without an action loop, so the intervention workflow was designed first and the model second. Two explainable models (diabetes, CVD) over twelve black boxes; clinic worklists capped to real outreach capacity.', r: 'A spec where every risk score has an owner and a deadline. Targets: PPV ≥40% in the top decile, 25% outreach conversion, +30% earlier intervention — proven with matched control regions.', followUp: '"How do you know the model won\'t be biased?" — Stratified performance audits across nationality and income segments before launch; a clinical panel owns features and thresholds, not the data science team.' },
    metrics: [
      { name: 'Model PPV, top risk decile', target: '≥ 40%', why: 'Providers act on the list; precision protects their trust. AUC is invisible to users.' },
      { name: 'Outreach conversion', target: '≥ 25%', why: 'Flagged → contacted → screened. Measures whether the workflow works, not just the model.' },
      { name: 'Earlier-intervention rate', target: '+30%', why: 'Conditions caught pre-complication vs baseline — the clinical outcome DoH funds.' },
      { name: 'Time-to-outreach, top decile', target: '< 14 days', why: 'Risk decays. A stale flag is a missed window.' }
    ],
    sections: [
      { title: 'Why Now', items: ['Chronic disease is the region\'s largest cost driver, and Malaffi unified the data — population-level risk is computable for the first time', 'DoH\'s Smart Population Health agenda supplies sponsorship and budget; riding a mandate beats creating one', 'Sizing: 2M+ residents with among the world\'s highest diabetes prevalence — each avoided complication repays screening cost many times over'] },
      { title: 'Discovery', items: ['Public-health analysts: reports existed, action loops didn\'t — insight died in PowerPoint', 'Provider shadowing: clinics can\'t absorb unprioritized lists; they need small, ranked, justified worklists', 'Decision that shaped everything: design the intervention loop first, then build the model that feeds it'] },
      { title: 'Key Trade-offs', items: ['Two conditions (diabetes, CVD) before twelve — depth of loop over breadth of models', 'Explainable gradient-boosted models over deep learning — clinicians must see why a patient is flagged', 'One model, two products: cohort dashboards for public health, patient-level worklists for providers'] },
      { title: 'Stakeholders', items: ['DoH public health — sponsor, owns target conditions', 'Providers — act on cohorts; earned with small precise lists, not mandates', 'Malaffi and data governance — FHIR access and consent scope', 'Privacy office — risk-scoring residents needs an explicit legal basis'] },
      { title: 'Risks & Mitigations', items: ['Model bias across nationality and income segments → stratified performance audits before launch', 'Alert fatigue → list size capped per clinic, threshold tuned to outreach capacity', 'Attribution (did we cause the screening?) → phased rollout with matched control regions'] },
      { title: 'Rollout / GTM', items: ['Pilot: one region, one condition, three provider networks — prove outreach yield before scaling', 'Expand by condition once the loop is proven; models are the cheap part', 'Quarterly outcome reviews with DoH tied to programme funding'] },
      { title: 'AI Eval & Trust', items: ['Clinical validation panel signs off on model features and thresholds', 'Monthly drift monitoring against incoming encounter data', 'Every flag carries its top-3 contributing factors — no black-box scores in clinical hands'] }
    ]
  },
  newborn_screening: {
    northStar: 'Median time from birth to treatment start for confirmed conditions',
    northStarWhy: 'The programme exists to open treatment windows. Sequencing volume is a vanity metric; days-to-treatment is the number that changes a child\'s life.',
    star: { s: 'Abu Dhabi launched a world-first newborn genomic screening programme covering 815+ treatable conditions — but sequencing was never the hard part.', t: 'Make an 815-condition genomic result operable inside real maternity and paediatric workflows.', a: 'Mapped the ward workflow: consent has to fit five bedside minutes. Genetic counsellors, not sequencers, are the bottleneck — so AI triage ranks findings by severity and treatability. Adult-onset incidental findings excluded; confirmatory testing completes before any parent is notified.', r: 'End-to-end workflow from consent to care pathway. Targets: ≥80% consent, <21-day turnaround, counsellor review time halved, 100% of confirmed cases in a pathway within 14 days.', followUp: '"Opt-in or opt-out?" — Opt-in with a counsellor callback. Volume matters less than trust in a programme touching infant genomes; consent rate is itself a trust metric.' },
    metrics: [
      { name: 'Parental consent rate', target: '≥ 80%', why: 'Screening only helps babies whose parents opt in — this measures trust in the programme design itself.' },
      { name: 'Sample-to-result turnaround', target: '< 21 days', why: 'From cord blood to counsellor-reviewed result; the treatment window is measured in weeks.' },
      { name: 'Counsellor review time per case', target: '−50%', why: 'AI triage exists to make 815 conditions reviewable by a scarce workforce. This tests whether it does.' },
      { name: 'Confirmed cases in care pathway', target: '100% ≤ 14 days', why: 'A diagnosis without a pathway is just bad news delivered early.' }
    ],
    sections: [
      { title: 'Why Now', items: ['WGS cost collapsed while the list of treatable childhood conditions grew — gene therapies changed the payoff of early detection', 'Abu Dhabi committed to a world-first programme; the product question is making it clinically operable', 'Conventional heel-prick panels cover a few dozen conditions; the gap is hundreds of treatable diagnoses'] },
      { title: 'Discovery', items: ['Maternity ward observation: consent must fit bedside reality — under five minutes, delivered by trained staff', 'The bottleneck is genetic counsellors, not sequencers — triage is the product', 'Paediatricians want a yes/no with a next step, not a genomic report'] },
      { title: 'Key Trade-offs', items: ['Report only treatable, childhood-onset conditions — incidental adult-onset findings deliberately excluded', 'Opt-in consent with counsellor callback over opt-out — trust over volume', 'AI ranks, humans sign: every released result carries a counsellor\'s name'] },
      { title: 'Stakeholders', items: ['DoH programme office — mandate and funding', 'Maternity hospitals — consent and sample intake live in their workflow', 'Genetics labs and counsellors — the capacity constraint', 'Ethics board — consent scope, data use, incidental-findings policy'] },
      { title: 'Risks & Mitigations', items: ['False positives → confirmatory testing completes before any parent notification', 'Parental anxiety → results delivered by counsellors in person, never through a portal', 'Infant genomic data governance → strict use limits; no secondary use without re-consent'] },
      { title: 'Rollout / GTM', items: ['Single maternity hospital pilot to harden consent scripts and chain-of-custody SOPs', 'Consent language A/B tested against comprehension, not just uptake', 'Emirate-wide expansion only after turnaround and pathway SLAs hold at pilot volume'] },
      { title: 'AI Eval & Trust', items: ['Triage ranking validated retrospectively against cohorts of diagnosed children', 'Severity and treatability rubric owned by the clinical board, not the model', 'Every AI rank is reviewable with its evidence trail'] }
    ]
  },
  shifa_ai: {
    northStar: '% of sessions resolved at the clinically appropriate care level',
    northStarWhy: 'Triage that over-refers floods ERs; triage that under-refers is unsafe. Clinician-audited appropriateness is the one number that captures both safety and system value.',
    star: { s: '100% of the emirate\'s providers are connected by an HIE, yet patients triage themselves at the ER and clinicians re-assemble history by hand every consult.', t: 'Design a bilingual LLM assistant safe enough for regulated healthcare — patient triage plus a clinician copilot on one core.', a: 'RAG over fine-tuning for auditability. Citations mandatory — no source, no answer. Red-flag escalation recall ≥99% as the safety gate; copilot sequenced first to earn clinical trust before public exposure. Eval plan: 500 clinician-graded golden cases, red-teaming, weekly regression.', r: 'A clinically defensible AI architecture: 100% citation coverage, Arabic/English parity as a launch gate, ~5 minutes saved per consult as the copilot\'s measured value proposition.', followUp: '"How do you stop hallucination?" — Grounded-only generation: the model can\'t state what it can\'t cite, and under uncertainty it refuses and escalates to a human rather than best-guessing.' },
    metrics: [
      { name: 'Citation coverage', target: '100%', why: 'Every clinical claim traceable to an HIE record — the trust contract that makes the product usable in a regulated setting.' },
      { name: 'Red-flag escalation recall', target: '≥ 99%', why: 'Missing an emergency is the one failure mode we cannot have. We over-escalate before we ever under-escalate.' },
      { name: 'Clinician minutes saved per consult', target: '~5 min', why: 'The copilot\'s entire value proposition — measured in pilot, never assumed.' },
      { name: 'Arabic / English quality parity', target: 'within 2%', why: 'Arabic-first users are the underserved majority. Parity is a launch gate, not a roadmap item.' }
    ],
    sections: [
      { title: 'Why Now', items: ['The HIE connects 100% of the emirate\'s providers — the grounding data finally exists', 'LLM capability crossed the clinical-summarisation threshold; the constraint moved from model to trust design', 'ERs absorb the cost of failed self-triage every day — the baseline is measurably bad'] },
      { title: 'Discovery', items: ['ER triage nurses: a large share of walk-ins belong elsewhere — misdirection is the norm, not the exception', 'Clinicians spend the first minutes of each consult re-assembling history the HIE already holds', 'Patients trust an Arabic-native voice — translation-flavoured Arabic reads as foreign and erodes trust'] },
      { title: 'Key Trade-offs', items: ['Clinician copilot ships first, patient surface second — earn clinical trust internally before public exposure', 'RAG over fine-tuning — auditability and update speed beat marginal fluency', 'Under uncertainty the assistant refuses and escalates; it never best-guesses a clinical answer'] },
      { title: 'Stakeholders', items: ['DoH digital health — sponsor and regulator', 'HIE operator — data access, consent scopes', 'Clinical safety board — owns thresholds and sign-off', 'Provider CMOs and ER leadership — the adoption gatekeepers'] },
      { title: 'Risks & Mitigations', items: ['Hallucination → grounded-only generation: no citation, no answer', 'Under-triage → conservative thresholds plus an always-available human escalation path', 'Privacy → consented HIE scopes; no training on patient data'] },
      { title: 'Rollout / GTM', items: ['Copilot pilot in three specialties; clinician NPS and time-saved gate expansion', 'Patient triage launches in one service line with clinician oversight of transcripts', 'Bilingual launch from day one — parity verified, not promised'] },
      { title: 'AI Eval & Trust', items: ['Golden set of 500 clinician-graded cases before any launch', 'Red-teaming for jailbreaks and medical-harm prompts', 'Weekly eval regression on every model or prompt update; specialist review loop on low-confidence answers'] }
    ]
  },
  health_twin: {
    northStar: 'Weekly prevention actions completed per active user',
    northStarWhy: 'A twin that is admired but not acted on changes nothing. Completed actions are the causal link between the model and a health outcome.',
    star: { s: 'The DoH–M42 Virtual Human Twin partnership created the rails, but consumers still see health as annual-checkup snapshots and wearable data goes uninterpreted.', t: 'Design a consumer product that makes prevention a daily behaviour instead of an annual event.', a: 'The predictive risk timeline is the hero screen — the story about tomorrow, not a dashboard about today. Three data streams done well at launch; wellness positioning to stay outside device classification; every projected risk paired with an action, framing tested against anxiety instruments.', r: 'A clear product bet with falsifiable numbers: weekly prevention actions as north star, D90 retention ≥40% against the day-30 death curve of health apps, screenings booked from the app as the digital-to-clinical bridge.', followUp: '"Isn\'t showing people risk projections dangerous?" — Ranges instead of point estimates, every risk paired with an action, and framing validated with behavioural scientists before launch.' },
    metrics: [
      { name: 'D90 retention', target: '≥ 40%', why: 'Health apps die at day 30. The forward-looking risk story has to beat the engagement decay curve.' },
      { name: 'Screenings booked from the app', target: 'track & grow', why: 'The moment digital risk becomes clinical care — the twin\'s actual job.' },
      { name: 'Risk-timeline views per week', target: '≥ 2', why: 'Tests the core design bet: the forward view, not the dashboard, is the hook.' },
      { name: 'Clinician share-outs per quarter', target: 'track & grow', why: 'The twin entering real consults is the credibility signal money can\'t buy.' }
    ],
    sections: [
      { title: 'Why Now', items: ['The DoH–M42 Virtual Human Twin partnership creates the data and distribution rails', 'Wearable penetration crossed the threshold where continuous signals are the norm, not the exception', 'The longevity agenda gives prevention political sponsorship it never had'] },
      { title: 'Discovery', items: ['Users don\'t want data — they want "am I okay, and what should I do?"', 'The annual-checkup mental model is the enemy; the product must make health feel continuous', 'Clinicians dismiss consumer data unless it arrives summarised and relevant to the consult'] },
      { title: 'Key Trade-offs', items: ['Risk timeline as the hero screen over a metrics dashboard — story beats stats', 'Three data streams done well over open integration sprawl', 'Wellness positioning at launch to stay outside medical-device classification — reclassify deliberately, later, if predictions become diagnostic'] },
      { title: 'Stakeholders', items: ['M42 — twin models and clinical infrastructure', 'DoH — programme sponsorship and population reach', 'Wearable platforms — data partnerships', 'Regulator — device-classification boundary must be managed, not discovered'] },
      { title: 'Risks & Mitigations', items: ['Health anxiety from forward projections → framing tested with behavioural scientists; every risk shown is paired with an action', 'Prediction credibility → confidence ranges always, point estimates never', 'Engagement decay → coach cadence tuned per user; no gamification slop'] },
      { title: 'Rollout / GTM', items: ['Invite-only cohort recruited through the national screening programme — data-rich users first', 'Employer wellness channel as the second wave', 'Clinician share-out feature marketed to doctors as better inputs, not more work'] },
      { title: 'AI Eval & Trust', items: ['Projection models backtested on longitudinal cohorts before any user sees a forecast', 'Coach recommendations reviewed by a preventive-medicine board', 'Framing A/Bs measured against anxiety instruments, not just engagement'] }
    ]
  },
  tableegh: {
    northStar: 'Median time from clinical suspicion to CDD notification',
    northStarWhy: 'Outbreak response is a race. Every design choice in the portal is justified by how much reporting latency and data incompleteness it removes.',
    star: { s: 'Communicable-disease reporting ran on faxes, phone calls, and free text — impossible at outbreak speed. DoH\'s live Tableegh portal replaced it.', t: 'Tear down the live product: explain why each design choice exists, and identify what to build next.', a: 'Walked the portal end-to-end as a facility reporter and mapped every mandatory field to its epidemiological purpose. Surfaced the deliberate trade-offs: friction accepted for data quality, per-disease notifications for clean case records, a CDD-controlled update loop where only lab fields unlock.', r: 'Three improvement proposals: LIS integration so lab-confirmed results auto-draft notifications, outbreak dashboards on the now-structured data, and a reporter feedback loop to sustain compliance.', followUp: '"What would you measure?" — North star: median time from clinical suspicion to CDD notification. Supporting: ≥90% complete at first submission — incomplete reports trigger the phone-call loops the portal exists to kill.' },
    metrics: [
      { name: 'Complete at first submission', target: '≥ 90%', why: 'Incomplete reports trigger the phone-call loops the portal exists to kill.' },
      { name: 'EID auto-fill rate', target: 'maximise', why: 'Every auto-filled record removes typo risk on the field that matters most — identity.' },
      { name: 'Facility reporting compliance', target: 'emirate-wide', why: 'Coverage is the epidemiological value. A portal 60% of facilities ignore is a fax machine with extra steps.' },
      { name: 'Lab-update turnaround', target: '< 48 h', why: 'Cases stay current as results land — surveillance stays live, not archival.' }
    ],
    sections: [
      { title: 'Why Now', items: ['Fax and phone reporting cannot support outbreak-speed response — COVID made that undeniable', 'UAE Pass and the EID registry made identity infrastructure free to reuse', 'Structured digital capture is the precondition for any downstream outbreak analytics'] },
      { title: 'Discovery (Product Reading)', items: ['Walked the live portal end-to-end as a facility reporter; mapped every mandatory field to its epidemiological purpose', 'Draft-and-resume exists because investigations span shifts — a workflow insight embedded in the design', 'The CDD lab-update loop shows the case lifecycle was designed, not bolted on'] },
      { title: 'Key Trade-offs', items: ['Mandatory symptom and lab sections raise reporter friction but make data analyzable — quality chosen over convenience', 'Multi-select spawning one notification per disease keeps case records clean at the cost of more forms', 'On updates, only lab fields unlock — protecting the integrity of submitted epidemiological data'] },
      { title: 'Stakeholders', items: ['Healthcare facilities and infection-control nurses — the reporters', 'CDD epidemiologists — the consumers; their questions define the form', 'ICA — Emirates ID registry integration', 'DoH licensing — facility-scoped access control'] },
      { title: 'Risks & Mitigations', items: ['Compliance without enforcement → reporting tied to facility licensing obligations', 'Garbage-in on manual-entry fallback → EID-first flow with lookup as default', 'Duplicate cases across facilities → Emirates ID as the natural patient key'] },
      { title: 'Improvements I\'d Propose', items: ['LIS integration: lab-confirmed notifiable results auto-draft a notification — remove the human trigger', 'Outbreak dashboards on top of the structured data the portal now captures', 'Reporter feedback loop — facilities never learn what their reports triggered; closing that loop sustains compliance'] },
      { title: 'Data Quality & Governance', items: ['Structure enforced at entry beats cleaning at analysis — the portal\'s core thesis', 'EID lookup as the single source of identity truth', 'Controlled update cycles preserve an auditable case history'] }
    ]
  },
  malaffi_caregaps: {
    northStar: 'Care gaps closed per clinic per month',
    northStarWhy: 'Malaffi already knows who is at risk. This proposal exists to convert known risk into closed gaps — everything else is instrumentation.',
    star: { s: 'Malaffi computes AI risk scores and runs 12 disease registries, but a score only surfaces when a clinician opens that record — the highest-risk patients who never book are the ones the system never shows anyone.', t: 'Flip Malaffi from record viewer to action engine — without any new data science.', a: 'A panel-management layer on the already-paid-for scores: three gap types with clear owners, worklists capped to each clinic\'s outreach capacity, one-tap actions, closed-loop status codes agreed with DoH up front, and a matched-control pilot design.', r: 'Pilot spec: five clinics, one gap type (overdue diabetic screening). Gates: ≥70% weekly clinic adoption, ≥30% outreach-to-kept-appointment, +25% closure lift vs control.', followUp: '"Why would clinics adopt it?" — The quality-reporting tie-in makes adoption self-interested, and capped lists guarantee it never becomes workload dumping on nurses.' },
    metrics: [
      { name: 'Weekly active clinics', target: '≥ 70%', why: 'A worklist nobody opens closes nothing. Adoption is the leading indicator for everything downstream.' },
      { name: 'Outreach → kept appointment', target: '≥ 30%', why: 'Tests whether prioritisation and one-tap actions actually move patients.' },
      { name: 'Gap-closure lift vs control', target: '+25%', why: 'The causal claim DoH will fund — which is why the pilot needs matched controls from day one.' },
      { name: 'Time-to-contact, top decile', target: '< 7 days', why: 'Speed is the worklist\'s whole advantage over monthly registry reports.' }
    ],
    sections: [
      { title: 'Why Now', items: ['The risk models and 12 disease registries are already built and paid for — the marginal cost is workflow, not data science', 'Value-based care needs quality numbers that today are assembled by hand', 'High-risk patients who never book are exactly the ones the current consult-time model never surfaces'] },
      { title: 'Discovery', items: ['Panel managers already export registry lists to Excel — the worklist exists, just outside the product', 'Clinicians reject anything that adds clicks mid-consult — so the worklist lives outside the consult, owned by panel managers', 'Nobody today knows whether an identified gap was ever acted on — the closed loop is the missing half'] },
      { title: 'Key Trade-offs', items: ['Build on existing risk scores rather than new models — ship the loop, not another model', 'Three gap types with clear owners before all registry rules — overdue screening, uncontrolled HbA1c, missed follow-up', 'Malaffi-side worklist now, EMR embed as phase two — speed to pilot over perfect placement'] },
      { title: 'Stakeholders', items: ['Malaffi product and engineering — the platform', 'DoH quality — reporting alignment and incentives', 'Clinic panel managers and nurses — the real users', 'Payers — quality incentives make closure financially legible'] },
      { title: 'Risks & Mitigations', items: ['Workload dumping on nurses → list capped to each clinic\'s stated outreach capacity', 'Attribution disputes → closed-loop status codes agreed with DoH before pilot', 'Duplicate outreach across providers → patient-level outreach lock in the HIE'] },
      { title: 'Rollout / GTM', items: ['Five-clinic pilot on one gap type: overdue diabetic screening', 'Success gate: closure lift vs matched controls — then expand gap types, then clinics', 'Quality-reporting tie-in makes adoption self-interested, not altruistic'] },
      { title: 'AI Eval & Trust', items: ['Risk scores are already clinically validated — evaluation shifts to workflow outcomes', 'Quarterly audit of worklist ranking for demographic skew in who receives outreach', 'Every closure status is auditable — the quality number must survive scrutiny'] }
    ]
  },
  malaffi_pgx: {
    northStar: 'Preventable adverse drug events from known drug-gene interactions',
    northStarWhy: 'The data to prevent these ADEs already sits in Malaffi. The product\'s only job is moving it thirty seconds earlier — to order entry.',
    star: { s: 'Malaffi holds pharmacogenomics reports — four metaboliser classes — as static documents behind a privacy seal. Nobody opens a PDF at prescribing speed, so preventable ADEs keep happening with the data to stop them already in the system.', t: 'Move genomic insight from document to decision — at order entry — without weakening the privacy model.', a: 'A sealed-data alert: it fires the dosing recommendation without ever exposing genotype. Launch scoped to ~10 high-evidence drug-gene pairs, interruptive only for severe interactions, with a retrospective replay of 12 months of real prescriptions to measure precision before go-live.', r: 'Targets: alert precision ≥80%, preventable ADEs −30%, override-with-reason analytics feeding a monthly P&T committee review, and a per-pair kill-switch if precision degrades.', followUp: '"Doesn\'t the privacy seal block this?" — The seal is the constraint that made the design better: the alert derives from sealed data and reveals a recommendation, never the genotype. Privacy preserved by architecture, not by policy.' },
    metrics: [
      { name: 'Alert precision (actionable)', target: '≥ 80%', why: 'Alert fatigue kills CDS. We\'d rather miss borderline cases than train clinicians to click through.' },
      { name: 'Accepted-alert rate', target: 'trend up', why: 'Acceptance is the trust curve; overrides with reasons are the tuning signal.' },
      { name: 'Dose adjustments at order entry', target: 'track', why: 'The behaviour change itself — prescription modified before dispensing, not after harm.' },
      { name: 'ADE reduction', target: '−30%', why: 'The clinical endpoint, measured against a retrospective baseline.' }
    ],
    sections: [
      { title: 'Why Now', items: ['The Emirati Genome Program is populating PGx reports at scale — coverage is crossing the usefulness threshold', 'e-Prescribing rails and CDS Hooks exist; the integration path is standard, not exotic', 'ADEs are a measurable, costed harm — the business case writes itself if the alert works'] },
      { title: 'Discovery', items: ['Clinicians never open sealed PGx PDFs mid-prescription — seconds matter at order entry', 'Pharmacists catch drug-gene interactions manually and inconsistently today', 'The privacy seal is a feature to preserve, not a blocker to remove — that reframe unlocked the design'] },
      { title: 'Key Trade-offs', items: ['Launch with ~10 high-evidence drug-gene pairs, not comprehensive coverage — precision before breadth', 'The alert derives from sealed data without exposing it — recommendation surfaces, genotype never does', 'Interruptive alerts only for severe interactions; passive banners otherwise'] },
      { title: 'Stakeholders', items: ['M42 genomics — PGx report pipeline', 'Malaffi — platform and EMR integrations', 'DoH privacy office — sealed-data design sign-off', 'Pharmacy & therapeutics committees — own the rules base clinically'] },
      { title: 'Risks & Mitigations', items: ['Liability for missed interactions → scope stated plainly: decision support, not decision', 'Alert fatigue → precision gate before any new pair ships; per-pair kill-switch', 'Genomic privacy → the alert reveals a dosing recommendation, never raw genotype'] },
      { title: 'Rollout / GTM', items: ['Two-hospital pilot on the top-10 pairs with pharmacist champions', 'Expand the pair list by evidence level, each pair passing the precision gate', 'Override analytics reported to DoH as the clinical-value proof'] },
      { title: 'AI Eval & Trust', items: ['Rules base replayed against 12 months of historical prescriptions before go-live — precision measured on real data', 'Override reasons reviewed monthly by the P&T committee', 'Every alert carries its evidence citation — clinicians can interrogate the recommendation'] }
    ]
  },
  sahatna: {
    northStar: 'Weekly active residents engaging with their health age and acting on a prevention recommendation',
    northStarWhy: 'Downloads and record views are vanity metrics. The health age feature only works if residents return weekly and take action — that is the behaviour change the longevity agenda needs.',
    star: { s: 'Abu Dhabi has world-class clinical infrastructure and a unified HIE, but residents still experience health as annual checkups and reactive ER visits — no consumer product connects them to their own data or motivates prevention.', t: 'Analyze Sahatna as the consumer platform that bridges the gap between DoH\'s preventive health vision and individual resident behaviour — with health age as the engagement hook.', a: 'Mapped the product\'s feature set against the longevity agenda: health age as the hero metric, AI assistant for guidance, Malaffi records for trust, wearables for daily engagement. Identified the critical design bet — making a single biological age number feel actionable, not anxiety-inducing.', r: 'A product analysis positioning health age as the north star engagement feature, with success tied to weekly return visits, prevention actions taken, and screenings booked — not app downloads.', followUp: '"How do you keep people coming back after they see their health age?" — The health age must change in response to their actions. A static number is a novelty; a number that moves when they walk more, sleep better, or complete a screening is a habit loop.' },
    metrics: [
      { name: 'Weekly active users', target: 'track & grow', why: 'Health apps die at day 30. Weekly return visits prove the health age story beats the engagement decay curve.' },
      { name: 'Prevention actions per user per week', target: '\u22651', why: 'The causal link between seeing a health age and changing a behaviour — the product\'s entire thesis.' },
      { name: 'Screenings booked from the app', target: 'track & grow', why: 'The moment digital engagement becomes clinical care — Sahatna\'s bridge to the health system.' },
      { name: 'AI assistant sessions per user', target: '\u22652/month', why: 'Tests whether the AI adds ongoing value or is a one-time novelty.' }
    ],
    sections: [
      { title: 'Why Now', items: ['Malaffi connects every provider in the emirate — the data to power a consumer health view finally exists', 'Abu Dhabi\'s longevity agenda gives prevention political sponsorship and budget', 'Wearable penetration crossed the threshold where continuous health signals are the norm'] },
      { title: 'Discovery (Product Reading)', items: ['Sahatna launched at Gitex 2024 with records, booking, and AI assistant — the health age feature extends this into prevention', 'The app uses UAE Pass for identity — the same trust infrastructure as government services', 'Wearable integration signals the shift from clinical-only to daily wellness data'] },
      { title: 'Key Trade-offs', items: ['Health age as a single number vs a dashboard of metrics — simplicity chosen over completeness', 'Wellness positioning to avoid medical-device classification — the same trade-off as Health Twin', 'AI assistant guidance vs clinical advice — clear boundaries required for regulatory safety'] },
      { title: 'Stakeholders', items: ['DoH Abu Dhabi — app owner and longevity agenda sponsor', 'Malaffi — the data backbone powering the unified record', 'M42 — clinical and genomic infrastructure partner', 'Wearable platforms — data partnerships for daily signals'] },
      { title: 'Risks & Mitigations', items: ['Health anxiety from biological age score — framing tested with behavioural scientists; every risk paired with an action', 'Engagement decay after initial curiosity — health age must visibly respond to behaviour changes', 'AI assistant hallucination — grounded-only generation with clinical review of guidance content'] },
      { title: 'Connection to Health Twin', items: ['Sahatna is the live consumer surface; Health Twin is the deeper predictive model underneath', 'The health age in Sahatna could be powered by the twin\'s biomarker trajectory models', 'Sahatna earns consumer trust first; the twin deepens the science later'] }
    ]
  },

  malaffi_patient: {
    northStar: 'Monthly active patients engaging with their own record',
    northStarWhy: 'Malaffi\'s value is invisible to the residents it describes. Engagement — views, consent actions, corrections — is how an HIE becomes something people trust rather than something done to them.',
    star: { s: 'Every resident\'s record flows through Malaffi, but patients can\'t see, correct, or control any of it — the HIE is something done to them, not for them.', t: 'Design the patient-facing surface that turns the HIE into something residents trust.', a: 'Discovery said patients\' first question is "who can see this?" — so the launch scope is transparency-first: record view, a who-viewed-my-record access log, and consent controls, nothing else. Plain-language Arabic-first summaries; corrections as structured requests routed to the source facility.', r: 'A trust funnel with numbers: ≥60% UAE Pass activation, corrections resolved in <14 days, ≥2 return visits per quarter — launched at a high-value moment, lab results landing in the app.', followUp: '"Won\'t the access log cause panic?" — Every entry carries a plain-language purpose. Transparency with context builds trust; opacity is what breeds the panic.' },
    metrics: [
      { name: 'UAE Pass activation rate', target: '≥ 60%', why: 'Identity binding is the top of the funnel; if activation fails, nothing downstream matters.' },
      { name: 'Return visits per quarter', target: '≥ 2', why: 'Separates one-time curiosity from a durable relationship with one\'s own health record.' },
      { name: 'Corrections resolved', target: '< 14 days', why: 'Trust is built at the failure points. A correction loop that works is worth ten features.' },
      { name: 'Access-log views', target: 'track', why: 'Transparency is the differentiating bet — usage validates it.' }
    ],
    sections: [
      { title: 'Why Now', items: ['Patients are increasingly entitled to their own data — the policy direction is one-way', 'A who-viewed-my-record access log is a differentiator no regional HIE offers patients', 'The rails exist: UAE Pass for identity, the master patient index for the record'] },
      { title: 'Discovery', items: ['Patients\' first question is "who can see this?" — transparency ranks above features', 'Medical jargon is the top comprehension barrier → a plain-language layer, Arabic-first', 'Correction anxiety is real: errors live in records patients could never see, let alone fix'] },
      { title: 'Key Trade-offs', items: ['Transparency-first launch: record view, access log, consent controls — nothing else', 'Plain-language summaries over raw record rendering — comprehension over completeness', 'Corrections as structured requests routed to the source facility, not free-text complaints'] },
      { title: 'Stakeholders', items: ['Malaffi — platform and master patient index', 'DoH policy — patient-rights framework', 'Source facilities — handle correction requests, need a workflow not a burden', 'ICA / UAE Pass — identity assurance'] },
      { title: 'Risks & Mitigations', items: ['Access-log panic ("why did that clinic view my record?") → every entry paired with a plain-language purpose', 'Identity mis-binding → conservative matching with a manual review queue', 'Low health literacy → Arabic-first plain language, tested with real patients before launch'] },
      { title: 'Rollout / GTM', items: ['Launch tied to a high-value moment: lab results landing in the app', 'National awareness through DoH channels — this is a public-trust product, not an app-store play', 'Facility onboarding for the correction workflow precedes patient launch'] },
      { title: 'Privacy & Trust', items: ['Consent controls granular by data category, not all-or-nothing', 'No secondary use of patients\' viewing behaviour', 'Every feature judged by one question: does this earn trust or spend it?'] }
    ]
  },
  planner: {
    northStar: 'Hours of focused time returned per active user per week',
    northStarWhy: 'The product exists to give knowledge workers their attention back. Task counts are activity; reclaimed hours are the outcome that justifies the whole build.',
    star: { s: 'Enterprise teams lose up to 30% of the day to inbox and Teams triage and status hygiene, spread across fragmented M365 apps.', t: 'Ship a Claude agent that triages, prepares, and drafts across M365 \u2014 trusted enough to run a 90-user pilot.', a: 'Built a Skills.md behaviour spec + Graph API connector; every action emits structured JSON; draft-never-send with a human on every approve; auto-flagging widened only where planners stopped overriding.', r: '~3h/day saved per user across the 90-user pilot, with triage precision high enough that planners stopped correcting most flags.', followUp: 'How would you decide which action types graduate from draft-only to autonomous?' },
    metrics: [
      { name: 'Triage precision (acted-on)', target: '\u2265 80%', why: 'A noisy flagged list gets abandoned \u2014 precision is the trust gate for the whole product.' },
      { name: 'Draft acceptance rate', target: '\u2265 70%', why: 'Measures whether drafts are good enough to send at a glance rather than rewrite.' },
      { name: 'Weekly active pilot users', target: '\u2265 75%', why: 'An assistant nobody opens saves nobody time; adoption leads every other metric.' },
      { name: 'Override-rate trend', target: 'declining', why: 'Falling overrides is the signal a workflow is ready for more autonomy.' }
    ],
    sections: [
      { title: 'Guardrails', items: ['Structured JSON for every action', 'The agent drafts, never sends', 'Low-confidence items surfaced for review, not auto-actioned'] },
      { title: 'Rollout / GTM', items: ['90-user pilot before any wider rollout', 'Auto-flag paths expanded only as override rate falls', 'Skills.md architecture ships new behaviours in days'] },
      { title: 'Risks', items: ['Over-triage causing alert fatigue', 'Graph API permission-scope creep', 'One bad autonomous send would cost trust \u2014 hence draft-only'] },
      { title: 'Prioritisation', items: ['Safest, highest-frequency actions first', 'Autonomy earned per action type via error budget', 'Team rollup deferred until per-user value is proven'] }
    ]
  },
  ticket: {
    northStar: '% of Tier-1 tickets resolved without a human touch \u2014 at zero unsafe actions',
    northStarWhy: 'Auto-resolution rate is the value; the zero-unsafe-actions clause is what keeps it shippable in a real IT org. Optimising either one alone is a trap.',
    star: { s: 'The helpdesk was drowning in repetitive Tier-1 tickets \u2014 passwords, VPN, access \u2014 with ~4h response times and overloaded staff.', t: 'Ship an agent that safely auto-resolves the repetitive Tier-1 load and escalates the rest with full context.', a: 'Trained on 18 months of real resolutions; a cheap classifier routes before the expensive reasoning; every fix runs behind a permission check + audit log; shipped narrow and widened per error budget.', r: '~40% of Tier-1 auto-resolved and a 94% response-time cut across 800+ monthly tickets.', followUp: 'How do you prevent an automated fix from masking or causing a larger incident?' },
    metrics: [
      { name: 'Auto-resolution rate', target: '\u2265 40% \u2192 grow', why: 'The core value metric; each safe category added moves it.' },
      { name: 'Unsafe-action rate', target: '0', why: 'A single bad automated fix erodes all trust \u2014 a hard gate, not a target.' },
      { name: 'First-response time', target: '\u221290%', why: 'Employees feel speed before they feel resolution rate.' },
      { name: 'Escalation quality (context accepted)', target: '\u2265 90%', why: 'Escalations must save specialists time, not add triage work.' }
    ],
    sections: [
      { title: 'Guardrails', items: ['Permission check before every automated fix', 'Immutable audit log on every action', 'Ambiguous tickets escalate with a diagnostic summary'] },
      { title: 'Rollout / GTM', items: ['Shipped resolving only the safest Tier-1 patterns', 'Coverage widened ticket-type by ticket-type', 'Each type gated on its own error budget'] },
      { title: 'Risks', items: ['A fix that masks a bigger incident', 'Training on documentation instead of real resolutions', 'Over-automation eroding the human escalation path'] },
      { title: 'Prioritisation', items: ['Highest-volume repeat categories first', 'Safety over coverage on every call', 'Deflection beats faster handling where possible'] }
    ]
  },
  gpt_erp: {
    northStar: '% of business-user ERP questions answered correctly without an analyst',
    northStarWhy: 'The product removes analysts from the loop for routine questions. Correct, self-served answers are the only proof it worked \u2014 raw query volume could just mean confusion.',
    star: { s: 'ERP data was locked behind specialists; simple questions became support tickets and multi-day report backlogs.', t: 'Give business users a plain-English query layer over Dynamics 365 with audit-grade citations.', a: 'Mapped D365 entities and relationships; GPT-4 translates questions into read-only queries grounded strictly on the records returned; every figure carries a citation \u2014 no citation, no answer.', r: 'Self-serve answers in seconds instead of a days-long backlog, each with a source citation for audit.', followUp: 'How do you stop the model from confidently answering a question the data cannot support?' },
    metrics: [
      { name: 'Answer correctness', target: '\u2265 95%', why: 'Wrong ERP numbers are worse than no answer; correctness is the licence to operate.' },
      { name: 'Citation coverage', target: '100%', why: 'Every figure traceable to a record \u2014 the audit contract that makes finance trust it.' },
      { name: 'Analyst tickets deflected', target: '\u2265 70%', why: 'The efficiency payoff: routine asks that no longer reach a human.' },
      { name: 'Time-to-answer', target: 'seconds', why: 'The felt difference against a multi-day report request.' }
    ],
    sections: [
      { title: 'Guardrails', items: ['Read-only scope \u2014 never writes to the ERP', 'No citation, no answer', 'Refuses figures it cannot ground in a record'] },
      { title: 'Rollout / GTM', items: ['Launched to operations & finance first', 'A question bank of real queries scored before rollout', 'Analyst corrections fed back into the prompt and evals'] },
      { title: 'Risks', items: ['Confident answers on unsupported data', 'Entity-mapping drift as the ERP schema changes', 'Users over-trusting an uncited figure'] },
      { title: 'Prioritisation', items: ['The ~20 questions that were 70% of asks, first', 'Correctness and citations before breadth', 'Write-back deferred until read-trust is proven'] }
    ]
  }
};
